-- Generated by NextActionGuide Data Generator
-- Product: Cataclysm Classic
-- Build: 4.4.2.60895
-- Generated: 2025-09-22 09:19:41
-- Flavor: cata
-- product: cata

local _, ns = ...
ns.data = ns.data or {}
ns.data.cata = ns.data.cata or {}

ns.data.cata.BattlePets = {

    [39] = {
        speciesId = 39, creatureId = 2671, summonSpellId = 4055, iconFileDataId = 132761, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28,
    },
    [40] = {
        speciesId = 40, creatureId = 7385, summonSpellId = 10673, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [41] = {
        speciesId = 41, creatureId = 7384, summonSpellId = 10674, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [42] = {
        speciesId = 42, creatureId = 7383, summonSpellId = 10675, iconFileDataId = 236547, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [43] = {
        speciesId = 43, creatureId = 7382, summonSpellId = 10676, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [44] = {
        speciesId = 44, creatureId = 7380, summonSpellId = 10677, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [45] = {
        speciesId = 45, creatureId = 7381, summonSpellId = 10678, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [46] = {
        speciesId = 46, creatureId = 7386, summonSpellId = 10679, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [47] = {
        speciesId = 47, creatureId = 7390, summonSpellId = 10680, iconFileDataId = 132921, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [49] = {
        speciesId = 49, creatureId = 7391, summonSpellId = 10682, iconFileDataId = 132921, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [50] = {
        speciesId = 50, creatureId = 7387, summonSpellId = 10683, iconFileDataId = 132925, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [51] = {
        speciesId = 51, creatureId = 7389, summonSpellId = 10684, iconFileDataId = 132924, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [52] = {
        speciesId = 52, creatureId = 7394, summonSpellId = 10685, iconFileDataId = 135996, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [55] = {
        speciesId = 55, creatureId = 7395, summonSpellId = 10688, iconFileDataId = 294474, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [56] = {
        speciesId = 56, creatureId = 7543, summonSpellId = 10695, iconFileDataId = 134154, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [57] = {
        speciesId = 57, creatureId = 7547, summonSpellId = 10696, iconFileDataId = 134155, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [58] = {
        speciesId = 58, creatureId = 7544, summonSpellId = 10697, iconFileDataId = 134158, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [59] = {
        speciesId = 59, creatureId = 7545, summonSpellId = 10698, iconFileDataId = 134157, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [64] = {
        speciesId = 64, creatureId = 7550, summonSpellId = 10703, iconFileDataId = 237579, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [65] = {
        speciesId = 65, creatureId = 7549, summonSpellId = 10704, iconFileDataId = 237579, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [67] = {
        speciesId = 67, creatureId = 7555, summonSpellId = 10706, iconFileDataId = 132150, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [68] = {
        speciesId = 68, creatureId = 7553, summonSpellId = 10707, iconFileDataId = 132150, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [69] = {
        speciesId = 69, creatureId = 7554, summonSpellId = 10708, iconFileDataId = 132150, petTypeEnum = 10, battlepetFlags = 58, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [70] = {
        speciesId = 70, creatureId = 14421, summonSpellId = 10709, iconFileDataId = 132161, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [72] = {
        speciesId = 72, creatureId = 7560, summonSpellId = 10711, iconFileDataId = 132762, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [74] = {
        speciesId = 74, creatureId = 7561, summonSpellId = 10713, iconFileDataId = 136040, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [75] = {
        speciesId = 75, creatureId = 7565, summonSpellId = 10714, iconFileDataId = 136040, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [77] = {
        speciesId = 77, creatureId = 7562, summonSpellId = 10716, iconFileDataId = 136040, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [78] = {
        speciesId = 78, creatureId = 7567, summonSpellId = 10717, iconFileDataId = 136040, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [83] = {
        speciesId = 83, creatureId = 8376, summonSpellId = 12243, iconFileDataId = 135996, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [84] = {
        speciesId = 84, creatureId = 30379, summonSpellId = 13548, iconFileDataId = 135996, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [85] = {
        speciesId = 85, creatureId = 9656, summonSpellId = 15048, iconFileDataId = 133712, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [86] = {
        speciesId = 86, creatureId = 9657, summonSpellId = 15049, iconFileDataId = 294476, petTypeEnum = 10, battlepetFlags = 16386, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [87] = {
        speciesId = 87, creatureId = 9662, summonSpellId = 15067, iconFileDataId = 132833, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [89] = {
        speciesId = 89, creatureId = 10259, summonSpellId = 15999, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 2050, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [90] = {
        speciesId = 90, creatureId = 10598, summonSpellId = 16450, iconFileDataId = 132598, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [92] = {
        speciesId = 92, creatureId = 11325, summonSpellId = 17707, iconFileDataId = 132494, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [93] = {
        speciesId = 93, creatureId = 11326, summonSpellId = 17708, iconFileDataId = 132787, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [94] = {
        speciesId = 94, creatureId = 11327, summonSpellId = 17709, iconFileDataId = 136217, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [95] = {
        speciesId = 95, creatureId = 12419, summonSpellId = 19772, iconFileDataId = 237579, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [106] = {
        speciesId = 106, creatureId = 14878, summonSpellId = 23811, iconFileDataId = 237579, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [107] = {
        speciesId = 107, creatureId = 15186, summonSpellId = 24696, iconFileDataId = 134169, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [111] = {
        speciesId = 111, creatureId = 15358, summonSpellId = 24988, iconFileDataId = 132834, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [114] = {
        speciesId = 114, creatureId = 15429, summonSpellId = 25162, iconFileDataId = 132107, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [116] = {
        speciesId = 116, creatureId = 15699, summonSpellId = 26010, iconFileDataId = 132189, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [117] = {
        speciesId = 117, creatureId = 15710, summonSpellId = 26045, iconFileDataId = 133650, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28,
    },
    [118] = {
        speciesId = 118, creatureId = 15706, summonSpellId = 26529, iconFileDataId = 133706, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28,
    },
    [119] = {
        speciesId = 119, creatureId = 15698, summonSpellId = 26533, iconFileDataId = 133204, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28,
    },
    [120] = {
        speciesId = 120, creatureId = 15705, summonSpellId = 26541, iconFileDataId = 133202, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28,
    },
    [121] = {
        speciesId = 121, creatureId = 16069, summonSpellId = 27241, iconFileDataId = 294479, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [122] = {
        speciesId = 122, creatureId = 16085, summonSpellId = 27570, iconFileDataId = 132311, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [124] = {
        speciesId = 124, creatureId = 16456, summonSpellId = 28505, iconFileDataId = 132498, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [125] = {
        speciesId = 125, creatureId = 16547, summonSpellId = 28738, iconFileDataId = 132763, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [126] = {
        speciesId = 126, creatureId = 16548, summonSpellId = 28739, iconFileDataId = 132514, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [127] = {
        speciesId = 127, creatureId = 16549, summonSpellId = 28740, iconFileDataId = 294480, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [128] = {
        speciesId = 128, creatureId = 16701, summonSpellId = 28871, iconFileDataId = 134813, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [130] = {
        speciesId = 130, creatureId = 17255, summonSpellId = 30156, iconFileDataId = 132833, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [131] = {
        speciesId = 131, creatureId = 18381, summonSpellId = 32298, iconFileDataId = 134539, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [132] = {
        speciesId = 132, creatureId = 18839, summonSpellId = 33050, iconFileDataId = 133900, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [136] = {
        speciesId = 136, creatureId = 20408, summonSpellId = 35156, iconFileDataId = 136006, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [137] = {
        speciesId = 137, creatureId = 20472, summonSpellId = 35239, iconFileDataId = 132762, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [138] = {
        speciesId = 138, creatureId = 21010, summonSpellId = 35907, iconFileDataId = 236193, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [139] = {
        speciesId = 139, creatureId = 21009, summonSpellId = 35909, iconFileDataId = 236193, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [140] = {
        speciesId = 140, creatureId = 21008, summonSpellId = 35910, iconFileDataId = 236193, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [141] = {
        speciesId = 141, creatureId = 21018, summonSpellId = 35911, iconFileDataId = 236193, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [142] = {
        speciesId = 142, creatureId = 21055, summonSpellId = 36027, iconFileDataId = 132188, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [143] = {
        speciesId = 143, creatureId = 21064, summonSpellId = 36028, iconFileDataId = 132188, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [144] = {
        speciesId = 144, creatureId = 21063, summonSpellId = 36029, iconFileDataId = 132188, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [145] = {
        speciesId = 145, creatureId = 21056, summonSpellId = 36031, iconFileDataId = 132188, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [146] = {
        speciesId = 146, creatureId = 21076, summonSpellId = 36034, iconFileDataId = 236196, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [149] = {
        speciesId = 149, creatureId = 22445, summonSpellId = 39181, iconFileDataId = 132598, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [153] = {
        speciesId = 153, creatureId = 22943, summonSpellId = 39709, iconFileDataId = 132800, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [155] = {
        speciesId = 155, creatureId = 23198, summonSpellId = 40405, iconFileDataId = 133858, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [156] = {
        speciesId = 156, creatureId = 23234, summonSpellId = 40549, iconFileDataId = 133980, petTypeEnum = 10, battlepetFlags = 16386, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [157] = {
        speciesId = 157, creatureId = 23231, summonSpellId = 40613, iconFileDataId = 294482, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [158] = {
        speciesId = 158, creatureId = 23258, summonSpellId = 40614, iconFileDataId = 294475, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [159] = {
        speciesId = 159, creatureId = 23266, summonSpellId = 40634, iconFileDataId = 132505, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [160] = {
        speciesId = 160, creatureId = 23274, summonSpellId = 40990, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [162] = {
        speciesId = 162, creatureId = 23909, summonSpellId = 42609, iconFileDataId = 134015, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [163] = {
        speciesId = 163, creatureId = 24388, summonSpellId = 43697, iconFileDataId = 132806, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [164] = {
        speciesId = 164, creatureId = 24389, summonSpellId = 43698, iconFileDataId = 132806, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [165] = {
        speciesId = 165, creatureId = 24480, summonSpellId = 43918, iconFileDataId = 237579, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [166] = {
        speciesId = 166, creatureId = 24753, summonSpellId = 44369, iconFileDataId = 132256, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [167] = {
        speciesId = 167, creatureId = 25062, summonSpellId = 45082, iconFileDataId = 132197, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [168] = {
        speciesId = 168, creatureId = 25109, summonSpellId = 45125, iconFileDataId = 133883, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [169] = {
        speciesId = 169, creatureId = 25110, summonSpellId = 45127, iconFileDataId = 133838, petTypeEnum = 10, battlepetFlags = 18514, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [170] = {
        speciesId = 170, creatureId = 25146, summonSpellId = 45174, iconFileDataId = 133784, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [171] = {
        speciesId = 171, creatureId = 25147, summonSpellId = 45175, iconFileDataId = 133786, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [172] = {
        speciesId = 172, creatureId = 25706, summonSpellId = 45890, iconFileDataId = 294481, petTypeEnum = 10, battlepetFlags = 16386, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [173] = {
        speciesId = 173, creatureId = 26050, summonSpellId = 46425, iconFileDataId = 132806, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [174] = {
        speciesId = 174, creatureId = 26056, summonSpellId = 46426, iconFileDataId = 132806, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [175] = {
        speciesId = 175, creatureId = 26119, summonSpellId = 46599, iconFileDataId = 134373, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [179] = {
        speciesId = 179, creatureId = 27217, summonSpellId = 48406, iconFileDataId = 133278, petTypeEnum = 10, battlepetFlags = 16402, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [180] = {
        speciesId = 180, creatureId = 27346, summonSpellId = 48408, iconFileDataId = 133443, petTypeEnum = 10, battlepetFlags = 16402, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [183] = {
        speciesId = 183, creatureId = 27914, summonSpellId = 49964, iconFileDataId = 136039, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [186] = {
        speciesId = 186, creatureId = 28470, summonSpellId = 51716, iconFileDataId = 132191, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [187] = {
        speciesId = 187, creatureId = 28513, summonSpellId = 51851, iconFileDataId = 132182, petTypeEnum = 10, battlepetFlags = 16402, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [188] = {
        speciesId = 188, creatureId = 28883, summonSpellId = 52615, iconFileDataId = 237441, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [189] = {
        speciesId = 189, creatureId = 29089, summonSpellId = 53082, iconFileDataId = 135277, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [190] = {
        speciesId = 190, creatureId = 29147, summonSpellId = 53316, iconFileDataId = 133730, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [191] = {
        speciesId = 191, creatureId = 24968, summonSpellId = 45048, iconFileDataId = 133000, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28,
    },
    [192] = {
        speciesId = 192, creatureId = 29726, summonSpellId = 55068, iconFileDataId = 327502, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [193] = {
        speciesId = 193, creatureId = 31575, summonSpellId = 59250, iconFileDataId = 134324, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [194] = {
        speciesId = 194, creatureId = 32589, summonSpellId = 61348, iconFileDataId = 132192, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [195] = {
        speciesId = 195, creatureId = 32590, summonSpellId = 61349, iconFileDataId = 132192, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [196] = {
        speciesId = 196, creatureId = 32592, summonSpellId = 61350, iconFileDataId = 236233, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [197] = {
        speciesId = 197, creatureId = 32591, summonSpellId = 61351, iconFileDataId = 236177, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [198] = {
        speciesId = 198, creatureId = 32595, summonSpellId = 61357, iconFileDataId = 294478, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [199] = {
        speciesId = 199, creatureId = 32643, summonSpellId = 61472, iconFileDataId = 132102, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [200] = {
        speciesId = 200, creatureId = 32791, summonSpellId = 61725, iconFileDataId = 134010, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28,
    },
    [201] = {
        speciesId = 201, creatureId = 32818, summonSpellId = 61773, iconFileDataId = 250626, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28,
    },
    [202] = {
        speciesId = 202, creatureId = 32841, summonSpellId = 61855, iconFileDataId = 294471, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [203] = {
        speciesId = 203, creatureId = 32939, summonSpellId = 61991, iconFileDataId = 134111, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [204] = {
        speciesId = 204, creatureId = 33188, summonSpellId = 62491, iconFileDataId = 134183, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [205] = {
        speciesId = 205, creatureId = 33194, summonSpellId = 62508, iconFileDataId = 236243, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [206] = {
        speciesId = 206, creatureId = 33197, summonSpellId = 62510, iconFileDataId = 132182, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [207] = {
        speciesId = 207, creatureId = 33198, summonSpellId = 62513, iconFileDataId = 132195, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [209] = {
        speciesId = 209, creatureId = 33200, summonSpellId = 62516, iconFileDataId = 136071, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [210] = {
        speciesId = 210, creatureId = 33219, summonSpellId = 62542, iconFileDataId = 132198, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [211] = {
        speciesId = 211, creatureId = 33226, summonSpellId = 62561, iconFileDataId = 132186, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [212] = {
        speciesId = 212, creatureId = 33205, summonSpellId = 62562, iconFileDataId = 133941, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [213] = {
        speciesId = 213, creatureId = 33227, summonSpellId = 62564, iconFileDataId = 135147, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [214] = {
        speciesId = 214, creatureId = 33238, summonSpellId = 62609, iconFileDataId = 236689, petTypeEnum = 10, battlepetFlags = 659, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [215] = {
        speciesId = 215, creatureId = 33274, summonSpellId = 62674, iconFileDataId = 132247, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [216] = {
        speciesId = 216, creatureId = 33239, summonSpellId = 62746, iconFileDataId = 236689, petTypeEnum = 10, battlepetFlags = 403, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [217] = {
        speciesId = 217, creatureId = 33578, summonSpellId = 63318, iconFileDataId = 135128, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [218] = {
        speciesId = 218, creatureId = 33810, summonSpellId = 63712, iconFileDataId = 133798, petTypeEnum = 10, battlepetFlags = 2050, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [220] = {
        speciesId = 220, creatureId = 34278, summonSpellId = 65046, iconFileDataId = 132129, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [224] = {
        speciesId = 224, creatureId = 34364, summonSpellId = 65358, iconFileDataId = 132599, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [225] = {
        speciesId = 225, creatureId = 33530, summonSpellId = 65381, iconFileDataId = 252780, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [226] = {
        speciesId = 226, creatureId = 33529, summonSpellId = 65382, iconFileDataId = 236698, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [227] = {
        speciesId = 227, creatureId = 34587, summonSpellId = 65682, iconFileDataId = 134239, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [228] = {
        speciesId = 228, creatureId = 34694, summonSpellId = 66030, iconFileDataId = 132834, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [229] = {
        speciesId = 229, creatureId = 34724, summonSpellId = 66096, iconFileDataId = 132849, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [231] = {
        speciesId = 231, creatureId = 34930, summonSpellId = 66520, iconFileDataId = 134134, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [232] = {
        speciesId = 232, creatureId = 35396, summonSpellId = 67413, iconFileDataId = 132193, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [233] = {
        speciesId = 233, creatureId = 35395, summonSpellId = 67414, iconFileDataId = 132193, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [234] = {
        speciesId = 234, creatureId = 35400, summonSpellId = 67415, iconFileDataId = 132253, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [235] = {
        speciesId = 235, creatureId = 35387, summonSpellId = 67416, iconFileDataId = 132253, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [236] = {
        speciesId = 236, creatureId = 35399, summonSpellId = 67417, iconFileDataId = 132253, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [237] = {
        speciesId = 237, creatureId = 35397, summonSpellId = 67418, iconFileDataId = 132253, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [238] = {
        speciesId = 238, creatureId = 35398, summonSpellId = 67419, iconFileDataId = 132193, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [239] = {
        speciesId = 239, creatureId = 35394, summonSpellId = 67420, iconFileDataId = 132193, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [240] = {
        speciesId = 240, creatureId = 35468, summonSpellId = 67527, iconFileDataId = 134399, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [241] = {
        speciesId = 241, creatureId = 36482, summonSpellId = 68767, iconFileDataId = 318523, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [242] = {
        speciesId = 242, creatureId = 36511, summonSpellId = 68810, iconFileDataId = 298591, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [243] = {
        speciesId = 243, creatureId = 36607, summonSpellId = 69002, iconFileDataId = 134154, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [244] = {
        speciesId = 244, creatureId = 36871, summonSpellId = 69452, iconFileDataId = 236191, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [245] = {
        speciesId = 245, creatureId = 36908, summonSpellId = 69535, iconFileDataId = 327735, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [246] = {
        speciesId = 246, creatureId = 36909, summonSpellId = 69536, iconFileDataId = 328270, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [247] = {
        speciesId = 247, creatureId = 36910, summonSpellId = 69539, iconFileDataId = 237194, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [248] = {
        speciesId = 248, creatureId = 36911, summonSpellId = 69541, iconFileDataId = 328269, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [249] = {
        speciesId = 249, creatureId = 36979, summonSpellId = 69677, iconFileDataId = 254094, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [250] = {
        speciesId = 250, creatureId = 37865, summonSpellId = 70613, iconFileDataId = 133718, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [251] = {
        speciesId = 251, creatureId = 38374, summonSpellId = 71840, iconFileDataId = 134437, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [253] = {
        speciesId = 253, creatureId = 40198, summonSpellId = 74932, iconFileDataId = 135851, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [254] = {
        speciesId = 254, creatureId = 40295, summonSpellId = 75134, iconFileDataId = 133000, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [255] = {
        speciesId = 255, creatureId = 40624, summonSpellId = 75613, iconFileDataId = 133443, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [256] = {
        speciesId = 256, creatureId = 40703, summonSpellId = 75906, iconFileDataId = 254104, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [257] = {
        speciesId = 257, creatureId = 40721, summonSpellId = 75936, iconFileDataId = 135128, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [258] = {
        speciesId = 258, creatureId = 42078, summonSpellId = 78381, iconFileDataId = 387415, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [259] = {
        speciesId = 259, creatureId = 42177, summonSpellId = 78683, iconFileDataId = 132188, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [260] = {
        speciesId = 260, creatureId = 42183, summonSpellId = 78685, iconFileDataId = 132200, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [261] = {
        speciesId = 261, creatureId = 43800, summonSpellId = 81937, iconFileDataId = 133861, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [262] = {
        speciesId = 262, creatureId = 43916, summonSpellId = 82173, iconFileDataId = 466036, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [264] = {
        speciesId = 264, creatureId = 45128, summonSpellId = 84263, iconFileDataId = 134555, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [265] = {
        speciesId = 265, creatureId = 45247, summonSpellId = 84492, iconFileDataId = 136024, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [266] = {
        speciesId = 266, creatureId = 45340, summonSpellId = 84752, iconFileDataId = 458255, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [267] = {
        speciesId = 267, creatureId = 46898, summonSpellId = 93836, iconFileDataId = 134249, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [268] = {
        speciesId = 268, creatureId = 46896, summonSpellId = 87344, iconFileDataId = 441880, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [270] = {
        speciesId = 270, creatureId = 47944, summonSpellId = 89039, iconFileDataId = 464139, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [271] = {
        speciesId = 271, creatureId = 48107, summonSpellId = 89472, iconFileDataId = 464160, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [272] = {
        speciesId = 272, creatureId = 48242, summonSpellId = 89670, iconFileDataId = 464159, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [277] = {
        speciesId = 277, creatureId = 48609, summonSpellId = 90523, iconFileDataId = 134152, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [278] = {
        speciesId = 278, creatureId = 48641, summonSpellId = 90637, iconFileDataId = 462532, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [279] = {
        speciesId = 279, creatureId = 48982, summonSpellId = 91343, iconFileDataId = 134395, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [280] = {
        speciesId = 280, creatureId = 49586, summonSpellId = 92395, iconFileDataId = 413584, petTypeEnum = 10, battlepetFlags = 17047, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [281] = {
        speciesId = 281, creatureId = 49588, summonSpellId = 92396, iconFileDataId = 413584, petTypeEnum = 10, battlepetFlags = 16791, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [282] = {
        speciesId = 282, creatureId = 49587, summonSpellId = 92397, iconFileDataId = 413585, petTypeEnum = 10, battlepetFlags = 16535, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [283] = {
        speciesId = 283, creatureId = 49590, summonSpellId = 92398, iconFileDataId = 413585, petTypeEnum = 10, battlepetFlags = 16535, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [285] = {
        speciesId = 285, creatureId = 50468, summonSpellId = 93624, iconFileDataId = 254104, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [286] = {
        speciesId = 286, creatureId = 50586, summonSpellId = 93739, iconFileDataId = 134892, petTypeEnum = 7, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [287] = {
        speciesId = 287, creatureId = 51632, summonSpellId = 93813, iconFileDataId = 237146, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [289] = {
        speciesId = 289, creatureId = 51635, summonSpellId = 93817, iconFileDataId = 134434, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [291] = {
        speciesId = 291, creatureId = 51090, summonSpellId = 93823, iconFileDataId = 133939, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [292] = {
        speciesId = 292, creatureId = 50545, summonSpellId = 93837, iconFileDataId = 134971, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [293] = {
        speciesId = 293, creatureId = 50722, summonSpellId = 93838, iconFileDataId = 399040, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [294] = {
        speciesId = 294, creatureId = 51122, summonSpellId = 94070, iconFileDataId = 134430, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [296] = {
        speciesId = 296, creatureId = 51601, summonSpellId = 95786, iconFileDataId = 467893, petTypeEnum = 10, battlepetFlags = 594, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [297] = {
        speciesId = 297, creatureId = 51600, summonSpellId = 95787, iconFileDataId = 254652, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [298] = {
        speciesId = 298, creatureId = 51649, summonSpellId = 95909, iconFileDataId = 467894, petTypeEnum = 10, battlepetFlags = 338, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [301] = {
        speciesId = 301, creatureId = 52226, summonSpellId = 96571, iconFileDataId = 132225, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [302] = {
        speciesId = 302, creatureId = 52343, summonSpellId = 96817, iconFileDataId = 254094, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [303] = {
        speciesId = 303, creatureId = 52344, summonSpellId = 96819, iconFileDataId = 132242, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [306] = {
        speciesId = 306, creatureId = 52831, summonSpellId = 97638, iconFileDataId = 132252, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [307] = {
        speciesId = 307, creatureId = 52894, summonSpellId = 97779, iconFileDataId = 132193, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [308] = {
        speciesId = 308, creatureId = 53048, summonSpellId = 98079, iconFileDataId = 132197, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [309] = {
        speciesId = 309, creatureId = 53225, summonSpellId = 98571, iconFileDataId = 516665, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [310] = {
        speciesId = 310, creatureId = 53232, summonSpellId = 98587, iconFileDataId = 516666, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [311] = {
        speciesId = 311, creatureId = 53283, summonSpellId = 98736, iconFileDataId = 519402, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [316] = {
        speciesId = 316, creatureId = 53623, summonSpellId = 99578, iconFileDataId = 132833, petTypeEnum = 10, battlepetFlags = 4178, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [317] = {
        speciesId = 317, creatureId = 53658, summonSpellId = 99663, iconFileDataId = 446127, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [318] = {
        speciesId = 318, creatureId = 53661, summonSpellId = 99668, iconFileDataId = 133941, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [319] = {
        speciesId = 319, creatureId = 53884, summonSpellId = 100330, iconFileDataId = 236547, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [320] = {
        speciesId = 320, creatureId = 54027, summonSpellId = 100576, iconFileDataId = 524050, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [321] = {
        speciesId = 321, creatureId = 54128, summonSpellId = 100684, iconFileDataId = 132762, petTypeEnum = 10, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [323] = {
        speciesId = 323, creatureId = 54227, summonSpellId = 100970, iconFileDataId = 133944, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [325] = {
        speciesId = 325, creatureId = 54374, summonSpellId = 101424, iconFileDataId = 132926, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [328] = {
        speciesId = 328, creatureId = 54383, summonSpellId = 101493, iconFileDataId = 133920, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [329] = {
        speciesId = 329, creatureId = 54438, summonSpellId = 101606, iconFileDataId = 528288, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [330] = {
        speciesId = 330, creatureId = 54491, summonSpellId = 101733, iconFileDataId = 132159, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [331] = {
        speciesId = 331, creatureId = 54539, summonSpellId = 101986, iconFileDataId = 236592, petTypeEnum = 10, battlepetFlags = 658, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [332] = {
        speciesId = 332, creatureId = 54541, summonSpellId = 101989, iconFileDataId = 236627, petTypeEnum = 10, battlepetFlags = 402, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [333] = {
        speciesId = 333, creatureId = 54730, summonSpellId = 102317, iconFileDataId = 136218, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [335] = {
        speciesId = 335, creatureId = 54487, summonSpellId = 103074, iconFileDataId = 133935, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [336] = {
        speciesId = 336, creatureId = 55187, summonSpellId = 103076, iconFileDataId = 133640, petTypeEnum = 10, battlepetFlags = 144, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [337] = {
        speciesId = 337, creatureId = 55215, summonSpellId = 103125, iconFileDataId = 134579, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [338] = {
        speciesId = 338, creatureId = 55356, summonSpellId = 103544, iconFileDataId = 133015, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [339] = {
        speciesId = 339, creatureId = 55367, summonSpellId = 103549, iconFileDataId = 133015, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [340] = {
        speciesId = 340, creatureId = 55386, summonSpellId = 103588, iconFileDataId = 433440, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [341] = {
        speciesId = 341, creatureId = 55571, summonSpellId = 104047, iconFileDataId = 134971, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [342] = {
        speciesId = 342, creatureId = 55574, summonSpellId = 104049, iconFileDataId = 134971, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [343] = {
        speciesId = 343, creatureId = 56031, summonSpellId = 105122, iconFileDataId = 132242, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [344] = {
        speciesId = 344, creatureId = 56082, summonSpellId = 105228, iconFileDataId = 133642, petTypeEnum = 10, battlepetFlags = 160, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [345] = {
        speciesId = 345, creatureId = 56083, summonSpellId = 105229, iconFileDataId = 133639, petTypeEnum = 10, battlepetFlags = 160, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [346] = {
        speciesId = 346, creatureId = 56266, summonSpellId = 105633, iconFileDataId = 135128, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [347] = {
        speciesId = 347, creatureId = 58163, summonSpellId = 110029, iconFileDataId = 574806, petTypeEnum = 10, battlepetFlags = 82, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [348] = {
        speciesId = 348, creatureId = 59020, summonSpellId = 112994, iconFileDataId = 136155, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [665] = {
        speciesId = 665, creatureId = 54745, summonSpellId = 102353, iconFileDataId = 134931, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [757] = {
        speciesId = 757, creatureId = 14755, summonSpellId = 23531, iconFileDataId = 134333, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [758] = {
        speciesId = 758, creatureId = 14756, summonSpellId = 23530, iconFileDataId = 134337, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [1073] = {
        speciesId = 1073, creatureId = 16445, summonSpellId = 28487, iconFileDataId = 132834, petTypeEnum = 10, battlepetFlags = 114, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [1168] = {
        speciesId = 1168, creatureId = 15361, summonSpellId = 24987, iconFileDataId = 132834, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [1351] = {
        speciesId = 1351, creatureId = 34770, summonSpellId = 66175, iconFileDataId = 237272, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [1563] = {
        speciesId = 1563, creatureId = 7546, summonSpellId = 10699, iconFileDataId = 134156, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [1927] = {
        speciesId = 1927, creatureId = 17254, summonSpellId = 30152, iconFileDataId = 134176, petTypeEnum = 10, battlepetFlags = 16450, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4172] = {
        speciesId = 4172, creatureId = 7388, summonSpellId = 10681, iconFileDataId = 132916, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4180] = {
        speciesId = 4180, creatureId = 7559, summonSpellId = 10712, iconFileDataId = 132766, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4182] = {
        speciesId = 4182, creatureId = 7569, summonSpellId = 10718, iconFileDataId = 136040, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4183] = {
        speciesId = 4183, creatureId = 7568, summonSpellId = 10719, iconFileDataId = 136040, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4184] = {
        speciesId = 4184, creatureId = 7566, summonSpellId = 10720, iconFileDataId = 136040, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4185] = {
        speciesId = 4185, creatureId = 7570, summonSpellId = 10721, iconFileDataId = 136116, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4204] = {
        speciesId = 4204, creatureId = 21266, summonSpellId = 36467, iconFileDataId = 132311, petTypeEnum = 10, battlepetFlags = 16386, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4206] = {
        speciesId = 4206, creatureId = 22328, summonSpellId = 38842, iconFileDataId = 133015, petTypeEnum = 10, battlepetFlags = 34, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [4211] = {
        speciesId = 4211, creatureId = 23114, summonSpellId = 40319, iconFileDataId = 133858, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [4228] = {
        speciesId = 4228, creatureId = 33199, summonSpellId = 62514, iconFileDataId = 133871, petTypeEnum = 10, battlepetFlags = 16386, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4229] = {
        speciesId = 4229, creatureId = 34031, summonSpellId = 64351, iconFileDataId = 254104, petTypeEnum = 10, battlepetFlags = 16386, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4233] = {
        speciesId = 4233, creatureId = 181485, summonSpellId = 359755, iconFileDataId = 294473, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 1,
    },
    [4234] = {
        speciesId = 4234, creatureId = 194870, summonSpellId = 384796, iconFileDataId = 134575, petTypeEnum = 10, battlepetFlags = 16450, sourceTypeEnum = -1, effect = 28,
    },
    [4235] = {
        speciesId = 4235, creatureId = 196534, summonSpellId = 388541, iconFileDataId = 4680677, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28,
    },
    [4236] = {
        speciesId = 4236, creatureId = 200900, summonSpellId = 407786, iconFileDataId = 4777763, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28,
    },
    [4273] = {
        speciesId = 4273, creatureId = 211012, summonSpellId = 423843, iconFileDataId = 5373378, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28,
    },
    [4274] = {
        speciesId = 4274, creatureId = 211025, summonSpellId = 423868, iconFileDataId = 5210737, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28,
    },
    [4329] = {
        speciesId = 4329, creatureId = 213605, summonSpellId = 428053, iconFileDataId = 5279604, petTypeEnum = 7, battlepetFlags = 18, sourceTypeEnum = -1, effect = 28,
    },
    [4532] = {
        speciesId = 4532, creatureId = 222858, summonSpellId = 446916, iconFileDataId = 5617452, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28,
    },
    [4585] = {
        speciesId = 4585, creatureId = 224065, summonSpellId = 450535, iconFileDataId = 5770411, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28,
    },
    [4683] = {
        speciesId = 4683, creatureId = 232527, summonSpellId = 468201, iconFileDataId = 6124234, petTypeEnum = 10, battlepetFlags = 16466, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [4685] = {
        speciesId = 4685, creatureId = 232536, summonSpellId = 468247, iconFileDataId = 6124702, petTypeEnum = 10, battlepetFlags = 2, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
    [4734] = {
        speciesId = 4734, creatureId = 237248, summonSpellId = 1217380, iconFileDataId = 6243478, petTypeEnum = 10, battlepetFlags = 16386, sourceTypeEnum = -1, effect = 28, effectBasePoints = 2,
    },
}