--[[
                                ----o----(||)----oo----(||)----o----

                                                Runes
                                         Localisation Module

                                      v1.30 - 29th January 2024
                                Copyright (C) Taraezor / Chris Birch
                                         All Rights Reserved

                                ----o----(||)----oo----(||)----o----
]]

local _, ns = ...
L = {}
ns.L = L

ns.locale = GetLocale()

ns.realm = GetNormalizedRealmName() -- On a fresh login this will return null
ns.oceania = { AmanThul = true, Barthilas = true, Caelestrasz = true, DathRemar = true,
			Dreadmaul = true, Frostmourne = true, Gundrak = true, JubeiThos = true, 
			Khazgoroth = true, Nagrand = true, Saurfang = true, Thaurissan = true,
			Yojamba = true, Remulos = true, Arugal = true, Felstriker = true,
			Penance = true, Shadowstrike = true }			
if ns.oceania[ ns.realm ] then
	ns.locale = "enGB"
end

setmetatable( L, { __index = function( L, key ) return key end } )

-- Firstly, translations I often use in all my AddOns

if ns.locale == "deDE" then
	ns.L["Character"] = "Charakter"
	ns.L["Account"] = "Accountweiter"
	ns.L["Completed"] = "Abgeschlossen"
	ns.L["Not Completed"] = "Nicht Abgeschlossen"
	ns.L["Options"] = "Optionen"
	ns.L["Map Pin Size"] = "Pin-Größe"
	ns.L["The Map Pin Size"] = "Die Größe der Karten-Pins"
	ns.L["Map Pin Alpha"] = "Kartenpin Alpha"
	ns.L["The alpha transparency of the map pins"] = "Die Alpha-Transparenz der Karten-Pins"
	ns.L["Show Coordinates"] = "Koordinaten anzeigen"
	ns.L["Show Coordinates Description"] = "Zeigen sie die koordinaten in QuickInfos auf "
		.."der Weltkarte und auf der Minikarte an"
	ns.L["Map Pin Selections"] = "Karten-Pin-Auswahl"
	ns.L["Gold"] = "Gold"
	ns.L["Red"] = "Rot"
	ns.L["Blue"] = "Blau"
	ns.L["Green"] = "Grün"
	ns.L["Ring"] = "Ring"
	ns.L["Cross"] = "Kreuz"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Frost"
	ns.L["Cogwheel"] = "Zahnrad"
	ns.L["White"] = "Weiß"
	ns.L["Purple"] = "Lila"
	ns.L["Yellow"] = "Gelb"
	ns.L["Grey"] = "Grau"
	ns.L["Mana Orb"] = "Manakugel"
	ns.L["Phasing"] = "Synchronisieren"
	ns.L["Raptor egg"] = "Raptor-Ei"
	ns.L["Stars"] = "Sternen"
	ns.L["Screw"] = "Schraube"
	ns.L["Left"] = "Links"
	ns.L["Right"] = "Rechts"
	ns.L["Try later"] = "Derzeit nicht möglich. Versuche es späte"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["Character"] = "Personaje"
	ns.L["Account"] = "la Cuenta"
	ns.L["Completed"] = "Completado"
	ns.L["Not Completed"] = ( ns.locale == "esES" ) and "Sin Completar" or "Incompleto"
	ns.L["Options"] = "Opciones"
	ns.L["Map Pin Size"] = "Tamaño de alfiler"
	ns.L["The Map Pin Size"] = "Tamaño de los pines del mapa"
	ns.L["Map Pin Alpha"] = "Alfa de los pines del mapa"
	ns.L["The alpha transparency of the map pins"] = "La transparencia alfa de los pines del mapa"
	ns.L["Show Coordinates"] = "Mostrar coordenadas"
	ns.L["Show Coordinates Description"] = "Mostrar coordenadas en información sobre "
		.."herramientas en el mapa del mundo y en el minimapa"
	ns.L["Map Pin Selections"] = "Selecciones de pines de mapa"
	ns.L["Gold"] = "Oro"
	ns.L["Red"] = "Rojo"
	ns.L["Blue"] = "Azul"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Anillo"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Escarcha"
	ns.L["Cogwheel"] = "Rueda dentada"
	ns.L["White"] = "Blanco"
	ns.L["Purple"] = "Púrpura"
	ns.L["Yellow"] = "Amarillo"
	ns.L["Grey"] = "Gris"
	ns.L["Mana Orb"] = "Orbe de maná"
	ns.L["Phasing"] = "Sincronización"	
	ns.L["Raptor egg"] = "Huevo de raptor"	
	ns.L["Stars"] = "Estrellas"
	ns.L["Screw"] = "Tornillo"
	ns.L["Left"] = "Izquierda"
	ns.L["Right"] = "Derecha"
	ns.L["Try later"] = "No es posible en este momento. Intenta más tarde"

elseif ns.locale == "frFR" then
	ns.L["Character"] = "Personnage"
	ns.L["Account"] = "le Compte"
	ns.L["Completed"] = "Achevé"
	ns.L["Not Completed"] = "Non achevé"
	ns.L["Options"] = "Options"
	ns.L["Map Pin Size"] = "Taille des épingles"
	ns.L["The Map Pin Size"] = "La taille des épingles de carte"
	ns.L["Map Pin Alpha"] = "Alpha des épingles de carte"
	ns.L["The alpha transparency of the map pins"] = "La transparence alpha des épingles de la carte"
	ns.L["Show Coordinates"] = "Afficher les coordonnées"
	ns.L["Show Coordinates Description"] = "Afficher les coordonnées\124r dans les info-bulles sur "
		.."la carte du monde et la mini-carte"
	ns.L["Map Pin Selections"] = "Sélections de broches de carte"
	ns.L["Gold"] = "Or"
	ns.L["Red"] = "Rouge"
	ns.L["Blue"] = "Bleue"
	ns.L["Green"] = "Vert"
	ns.L["Ring"] = "Bague"
	ns.L["Cross"] = "Traverser"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Givre"
	ns.L["Cogwheel"] = "Roue dentée"
	ns.L["White"] = "Blanc"
	ns.L["Purple"] = "Violet"
	ns.L["Yellow"] = "Jaune"
	ns.L["Grey"] = "Gris"
	ns.L["Mana Orb"] = "Orbe de mana"
	ns.L["Phasing"] = "Synchronisation"
	ns.L["Raptor egg"] = "Œuf de Rapace"
	ns.L["Stars"] = "Étoiles"
	ns.L["Screw"] = "Vis"
	ns.L["Left"] = "Gauche"
	ns.L["Right"] = "Droite"
	ns.L["Try later"] = "Pas possible pour le moment. Essayer plus tard"

elseif ns.locale == "itIT" then
	ns.L["Character"] = "Personaggio"
	ns.L["Account"] = "Account"
	ns.L["Completed"] = "Completo"
	ns.L["Not Completed"] = "Non Compiuto"
	ns.L["Options"] = "Opzioni"
	ns.L["Map Pin Size"] = "Dimensione del pin"
	ns.L["The Map Pin Size"] = "La dimensione dei Pin della mappa"
	ns.L["Map Pin Alpha"] = "Mappa pin alfa"
	ns.L["The alpha transparency of the map pins"] = "La trasparenza alfa dei pin della mappa"
	ns.L["Show Coordinates"] = "Mostra coordinate"
	ns.L["Show Coordinates Description"] = "Visualizza le coordinate\124r nelle descrizioni "
		.."comandi sulla mappa del mondo e sulla minimappa"
	ns.L["Map Pin Selections"] = "Selezioni pin mappa"
	ns.L["Gold"] = "Oro"
	ns.L["Red"] = "Rosso"
	ns.L["Blue"] = "Blu"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Squillo"
	ns.L["Cross"] = "Attraverso"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gelo"
	ns.L["Cogwheel"] = "Ruota dentata"
	ns.L["White"] = "Bianca"
	ns.L["Purple"] = "Viola"
	ns.L["Yellow"] = "Giallo"
	ns.L["Grey"] = "Grigio"
	ns.L["Mana Orb"] = "Globo di Mana"
	ns.L["Phasing"] = "Sincronizzazione"
	ns.L["Raptor egg"] = "Raptor Uovo"
	ns.L["Stars"] = "Stelle"
	ns.L["Screw"] = "Vite"
	ns.L["Left"] = "Sinistra"
	ns.L["Right"] = "Destra"
	ns.L["Try later"] = "Non è possibile in questo momento. Prova più tardi"

elseif ns.locale == "koKR" then
	ns.L["Character"] = "캐릭터"
	ns.L["Account"] = "계정"
	ns.L["Completed"] = "완료"
	ns.L["Not Completed"] = "미완료"
	ns.L["Options"] = "설정"
	ns.L["Map Pin Size"] = "지도 핀의 크기"
	ns.L["The Map Pin Size"] = "지도 핀의 크기"
	ns.L["Map Pin Alpha"] = "지도 핀의 알파"
	ns.L["The alpha transparency of the map pins"] = "지도 핀의 알파 투명도"
	ns.L["Show Coordinates"] = "좌표 표시"
	ns.L["Show Coordinates Description"] = "세계지도 및 미니지도의 도구 설명에 좌표를 표시합니다."
	ns.L["Map Pin Selections"] = "지도 핀 선택"
	ns.L["Gold"] = "금"
	ns.L["Red"] = "빨간"
	ns.L["Blue"] = "푸른"
	ns.L["Green"] = "녹색"
	ns.L["Ring"] = "반지"
	ns.L["Cross"] = "십자가"
	ns.L["Diamond"] = "다이아몬드"
	ns.L["Frost"] = "냉기"
	ns.L["Cogwheel"] = "톱니 바퀴"
	ns.L["White"] = "화이트"
	ns.L["Purple"] = "보라색"
	ns.L["Yellow"] = "노랑"
	ns.L["Grey"] = "회색"
	ns.L["Mana Orb"] = "마나 보주"
	ns.L["Phasing"] = "동기화 중"
	ns.L["Raptor egg"] = "랩터의 알"
	ns.L["Stars"] = "별"
	ns.L["Screw"] = "나사"
	ns.L["Left"] = "왼쪽"
	ns.L["Right"] = "오른쪽"
	ns.L["Try later"] = "지금은 불가능합니다. 나중에 시도하세요"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["Character"] = "Personagem"
	ns.L["Account"] = "à Conta"
	ns.L["Completed"] = "Concluído"
	ns.L["Not Completed"] = "Não Concluído"
	ns.L["Options"] = "Opções"
	ns.L["Map Pin Size"] = "Tamanho do pino"
	ns.L["The Map Pin Size"] = "O tamanho dos pinos do mapa"
	ns.L["Map Pin Alpha"] = "Alfa dos pinos do mapa"
	ns.L["The alpha transparency of the map pins"] = "A transparência alfa dos pinos do mapa"
	ns.L["Show Coordinates"] = "Mostrar coordenadas"
	ns.L["Show Coordinates Description"] = "Exibir coordenadas\124r em dicas de ferramentas "
		.."no mapa mundial e no minimapa"
	ns.L["Map Pin Selections"] = "Seleções de pinos de mapa"
	ns.L["Gold"] = "Ouro"
	ns.L["Red"] = "Vermelho"
	ns.L["Blue"] = "Azul"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Anel"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gélido"
	ns.L["Cogwheel"] = "Roda dentada"
	ns.L["White"] = "Branco"
	ns.L["Purple"] = "Roxa"
	ns.L["Yellow"] = "Amarelo"
	ns.L["Grey"] = "Cinzento"
	ns.L["Mana Orb"] = "Orbe de Mana"
	ns.L["Phasing"] = "Sincronização"
	ns.L["Raptor egg"] = "Ovo de raptor"
	ns.L["Stars"] = "Estrelas"
	ns.L["Screw"] = "Parafuso"
	ns.L["Left"] = "Esquerda"
	ns.L["Right"] = "Direita"
	ns.L["Try later"] = "Não é possível neste momento. Tente depois"

elseif ns.locale == "ruRU" then
	ns.L["Character"] = "Персонажа"
	ns.L["Account"] = "Счет"
	ns.L["Completed"] = "Выполнено"
	ns.L["Not Completed"] = "Не Выполнено"
	ns.L["Options"] = "Параметры"
	ns.L["Map Pin Size"] = "Размер булавки"
	ns.L["The Map Pin Size"] = "Размер булавок на карте"
	ns.L["Map Pin Alpha"] = "Альфа булавок карты"
	ns.L["The alpha transparency of the map pins"] = "Альфа-прозрачность булавок карты"
	ns.L["Show Coordinates"] = "Показать Координаты"
	ns.L["Show Coordinates Description"] = "Отображает координаты\124r во всплывающих "
		.."подсказках на карте мира и мини-карте"
	ns.L["Map Pin Selections"] = "Выбор булавки карты"
	ns.L["Gold"] = "Золото"
	ns.L["Red"] = "Красный"
	ns.L["Blue"] = "Синий"
	ns.L["Green"] = "Зеленый"
	ns.L["Ring"] = "Звенеть"
	ns.L["Cross"] = "Крест"
	ns.L["Diamond"] = "Ромб"
	ns.L["Frost"] = "Лед"
	ns.L["Cogwheel"] = "Зубчатое колесо"
	ns.L["White"] = "белый"
	ns.L["Purple"] = "Пурпурный"
	ns.L["Yellow"] = "Желтый"
	ns.L["Grey"] = "Серый"
	ns.L["Mana Orb"] = "Cфера маны"
	ns.L["Phasing"] = "Синхронизация"
	ns.L["Raptor egg"] = "Яйцо ящера"
	ns.L["Stars"] = "Звезды"
	ns.L["Screw"] = "Винт"
	ns.L["Left"] = "Налево"
	ns.L["Right"] = "Направо"
	ns.L["Try later"] = "В настоящее время это невозможно. Попробуй позже"

elseif ns.locale == "zhCN" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "账号"
	ns.L["Completed"] = "已完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Options"] = "选项"
	ns.L["Map Pin Size"] = "地图图钉的大小"
	ns.L["The Map Pin Size"] = "地图图钉的大小"
	ns.L["Map Pin Alpha"] = "地图图钉的透明度"
	ns.L["The alpha transparency of the map pins"] = "地图图钉的透明度"
	ns.L["Show Coordinates"] = "显示坐标"
	ns.L["Show Coordinates Description"] = "在世界地图和迷你地图上的工具提示中显示坐标"
	ns.L["Map Pin Selections"] = "地图图钉选择"
	ns.L["Gold"] = "金子"
	ns.L["Red"] = "红"
	ns.L["Blue"] = "蓝"
	ns.L["Green"] = "绿色"
	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "冰霜"
	ns.L["Cogwheel"] = "齿轮"
	ns.L["White"] = "白色"
	ns.L["Purple"] = "紫色"
	ns.L["Yellow"] = "黄色"
	ns.L["Grey"] = "灰色"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor egg"] = "迅猛龙蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "拧"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Try later"] = "目前不可能。稍后再试"

elseif ns.locale == "zhTW" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "賬號"
	ns.L["Completed"] = "完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Options"] = "選項"
	ns.L["Map Pin Size"] = "地圖圖釘的大小"
	ns.L["The Map Pin Size"] = "地圖圖釘的大小"
	ns.L["Map Pin Alpha"] = "地圖圖釘的透明度"
	ns.L["The alpha transparency of the map pins"] = "地圖圖釘的透明度"
	ns.L["Show Coordinates"] = "顯示坐標"
	ns.L["Show Coordinates Description"] = "在世界地圖和迷你地圖上的工具提示中顯示坐標"
	ns.L["Map Pin Selections"] = "地圖圖釘選擇"
	ns.L["Gold"] = "金子"
	ns.L["Red"] = "紅"
	ns.L["Blue"] = "藍"
	ns.L["Green"] = "綠色"
	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "霜"
	ns.L["Cogwheel"] = "齒輪"
	ns.L["White"] = "白色"
	ns.L["Purple"] = "紫色"
	ns.L["Yellow"] = "黃色"
	ns.L["Grey"] = "灰色"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor egg"] = "迅猛龍蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "擰"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Try later"] = "目前不可能。稍後再試"

else
	ns.L["Character"] = "Character"
	ns.L["Account"] = "Account"
	ns.L["Completed"] = "Completed"
	ns.L["Not Completed"] = "Not Completed"
	ns.L["Options"] = "Options"
	ns.L["Map Pin Size"] = "Map Pin Size"
	ns.L["The Map Pin Size"] = "The Map Pin Size"
	ns.L["Map Pin Alpha"] = "Map Pin Alpha"
	ns.L["The alpha transparency of the map pins"] = "The alpha transparency of the map pins"
	ns.L["Show Coordinates"] = "Show Coordinates"
	ns.L["Show Coordinates Description"] = "Display coordinates in tooltips on the world map and the mini map"
	ns.L["Map Pin Selections"] = "Map Pin Selections"
	ns.L["Gold"] = "Gold"
	ns.L["Red"] = "Red"
	ns.L["Blue"] = "Blue"
	ns.L["Green"] = "Green"
	ns.L["Ring"] = "Ring"
	ns.L["Cross"] = "Cross"
	ns.L["Diamond"] = "Diamond"
	ns.L["Frost"] = "Frost"
	ns.L["Cogwheel"] = "Cogwheel"
	ns.L["White"] = "White"
	ns.L["Purple"] = "Purple"
	ns.L["Yellow"] = "Yellow"
	ns.L["Grey"] = ( ( ns.locale == "enUS" ) and "Gray" or "Grey" )
	ns.L["Mana Orb"] = "Mana Orb"
	ns.L["Phasing"] = "Phasing"
	ns.L["Raptor egg"] = "Raptor egg"
	ns.L["Stars"] = "Stars"
	ns.L["Screw"] = "Screw"
	ns.L["Left"] = "Left"
	ns.L["Right"] = "Right"
	ns.L["Try later"] = "Not possible at this time. Try later"
end

-- Translations specific to the Runes AddOn

if ns.locale == "deDE" then
	ns.L["AddOn Description"] = "Hilft Ihnen, Runen der Saison der Entdeckungen zu sammeln"
	ns.L["Arcane"] = "Arkane"
	ns.L["Demonic"] = "Dämonische"
	ns.L["Duty"] = "Pflicht"
	ns.L["Mjolnir"] = "Mjolnir"
	-- Druid
	ns.L["Fury of Stormrage"] = "Furor von Sturmgrimm"
	ns.L["Lacerate"] = "Aufschlitzen"
	ns.L["Lifebloom"] = "Blühendes Leben"
	ns.L["Living Seed"] = "Samenkorn des Lebens"
	ns.L["Mangle"] = "Zerfleischen"
	ns.L["Savage Roar"] = "Wildes Brüllen"
	ns.L["Skull Bash"] = "Schädelstoß"
	ns.L["Starsurge"] = "Sternensog"
	ns.L["Sunfire"] = "Sonnenfeuer"
	ns.L["Survival of the Fittest"] = "Überleben des Stärkeren"
	ns.L["Wild Growth"] = "Wildwuchs"
	ns.L["Wild Strikes"] = "Wilde Stöße"
	-- Hunter
	ns.L["Beast Mastery"] = "Meister der Tiere"
	ns.L["Carve"] = "Zerlegen"
	ns.L["Chimera Shot"] = "Schimärenschuss"
	ns.L["Cobra Strikes"] = "Kobrastöße"
	ns.L["Explosive Shot"] = "Explosivschuss"
	ns.L["Flanking Strike"] = "Flankenangriff"
	ns.L["Heart of the Lion"] = "Löwenherz"
	ns.L["Kill Command"] = "Tötungsbefehl"
	ns.L["Lone Wolf"] = "Einsamer Wolf"
	ns.L["Master Marksman"] = "Meister der Treffsicherheit"
	ns.L["Serpent Spread"] = "Schlangenspur"
	ns.L["Sniper Training"] = "Scharfschützentraining"
	-- Mage
	ns.L["Arcane Blast"] = "Arkanschlag"
	ns.L["Arcane Surge"] = "Arkane Woge"
	ns.L["Burnout"] = "Feuerfontäne"
	ns.L["Enlightenment"] = "Erleuchtung"
	ns.L["Fingers of Frost"] = "Eisige Finger"
	ns.L["Ice Lance"] = "Eislanze"
	ns.L["Icy Veins"] = "Eisige Adern"
	ns.L["Living Bomb"] = "Lebende Bombe"
	ns.L["Living Flame"] = "Lebende Flamme"
	ns.L["Mass Regeneration"] = "Massenregeneration"
	ns.L["Regeneration"] = "Regeneration"
	ns.L["Rewind Time"] = "Zeit zurückdrehen"
	-- Paladin
	ns.L["Aegis"] = "Aegis"
	ns.L["Avenger's Shield"] = "Schild des Rächers"
	ns.L["Beacon of Light"] = "Flamme des Glaubens"
	ns.L["Crusader Strike"] = "Kreuzfahrerstoß"
	ns.L["Exorcist"] = "Exorzist"
	ns.L["Divine Sacrifice"] = "Heilige Opferung"
	ns.L["Divine Storm"] = "Göttlicher Sturm"
	ns.L["Hand of Reckoning"] = "Hand der Abrechnung"
	ns.L["Horn of Lordaeron"] = "Horn von Lordaeron"
	ns.L["Inspiration Exemplar"] = "Inspirationsvorbild"
	ns.L["Rebuke"] = "Zurechtweisung"
	ns.L["Seal of Martyrdom"] = "Siegel des Märtyrertums"
	-- Priest
	ns.L["Circle of Healing"] = "Kreis der Heilung"
	ns.L["Homunculi"] = "Homunculi"
	ns.L["Mind Sear"] = "Gedankenbrand"
	ns.L["Penance"] = "Sühne"
	ns.L["Power Word: Barrier"] = "Machtwort: Barriere"
	ns.L["Prayer of Mending"] = "Gebet der Besserung"
	ns.L["Serendipity"] = "Glücksfall"
	ns.L["Shadow Word: Death"] = "Schattenwort: Tod"
	ns.L["Shared Pain"] = "Geteilter Schmerz"
	ns.L["Strength of Soul"] = "Kraftvolle Seele"
	ns.L["Twisted Faith"] = "Okkultismus"
	ns.L["Void Plague"] = "Pest der Leere"
	-- Rogue
	ns.L["Between the Eyes"] = "Zwischen die Augen"
	ns.L["Blade Dance"] = "Klingentanz"
	ns.L["Deadly Brew"] = "Tödliche Mischung"
	ns.L["Envenom"] = "Vergiften"
	ns.L["Just a Flesh Wound"] = "Nur eine Fleischwunde"
	ns.L["Main Gauche"] = "Parierdolch"
	ns.L["Mutilate"] = "Verstümmeln"
	ns.L["Quick Draw"] = "Pistolenheld"
	ns.L["Saber Slash"] = "Säbelschlitzer"
	ns.L["Shadowstrike"] = "Schattenschlag"
	ns.L["Slaughter from the Shadows"] = "Hinterhältiger Mord"
	ns.L["Shiv"] = "Tückische Klinge"
	-- Shaman
	ns.L["Ancestral Guidance"] = "Führung der Ahnen"
	ns.L["Dual Wield Specialization"] = "Beidhändigkeitsspezialisierung"
	ns.L["Earth Shield"] = "Erdschild"
	ns.L["Healing Rain"] = "Heilender Regen"
	ns.L["Lava Burst"] = "Lavaeruption"
	ns.L["Lava Lash"] = "Lavapeitsche"
	ns.L["Molten Blast"] = "Schmelzschlag"
	ns.L["Overload"] = "Überladung"
	ns.L["Shamanistic Rage"] = "Schamanistische Wut"
	ns.L["Shield Mastery"] = "Schildmeisterschaft"
	ns.L["Way of Earth"] = "Weg der Erde"
	ns.L["Water Shield"] = "Wasserschild"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["AddOn Description"] = "Te ayuda a recolectar runas de Season of Discovery"
	ns.L["Arcane"] = "Arcana"
	ns.L["Demonic"] = "Demoníaca"
	ns.L["Duty"] = "Deber"
	ns.L["Mjolnir"] = "Mjolnir"
	-- Druid
	ns.L["Fury of Stormrage"] = "Furia de Tempestira"
	ns.L["Lacerate"] = "Lacerar"
	ns.L["Lifebloom"] = "Flor de vida"
	ns.L["Living Seed"] = "Semilla viviente"
	ns.L["Mangle"] = "Destrozar"
	ns.L["Savage Roar"] = "Rugido salvaje"
	ns.L["Skull Bash"] = "Testarazo"
	ns.L["Starsurge"] = "Oleada de estrellas"
	ns.L["Sunfire"] = "Fuego solar"
	ns.L["Survival of the Fittest"] = "Supervivencia del más fuerte"
	ns.L["Wild Growth"] = "Crecimiento salvaje"
	ns.L["Wild Strikes"] = "Golpes descontrolados"
	-- Hunter
	ns.L["Beast Mastery"] = "Maestría en bestias"
	ns.L["Carve"] = "Trinchar"
	ns.L["Chimera Shot"] = "Disparo de quimera"
	ns.L["Cobra Strikes"] = "Golpes de cobra"
	ns.L["Explosive Shot"] = "Disparo explosivo"
	ns.L["Flanking Strike"] = "Golpe de flanco"
	ns.L["Heart of the Lion"] = "Corazón del león"
	ns.L["Kill Command"] = "Matar"
	ns.L["Lone Wolf"] = "Lobo solitario"
	ns.L["Master Marksman"] = "Maestro tirador"
	ns.L["Serpent Spread"] = "Propagar serpientes"
	ns.L["Sniper Training"] = "Instrucción de francotirador"
	-- Mage
	ns.L["Arcane Blast"] = "Explosión Arcana"
	ns.L["Arcane Surge"] = "Oleada Arcana"
	ns.L["Burnout"] = "Consunción"
	ns.L["Enlightenment"] = "Esclarecimiento"
	ns.L["Fingers of Frost"] = "Dedos de Escarcha"
	ns.L["Ice Lance"] = "Lanza de hielo"
	ns.L["Icy Veins"] = "Venas heladas"
	ns.L["Living Bomb"] = "Bomba viva"
	ns.L["Living Flame"] = "Llama viva"
	ns.L["Mass Regeneration"] = "Regeneración en masa"
	ns.L["Regeneration"] = "Regeneración"
	ns.L["Rewind Time"] = "Retroceder en el tiempo"
	-- Paladin
	ns.L["Aegis"] = "Égida"
	ns.L["Avenger's Shield"] = "Escudo de vengador"
	ns.L["Beacon of Light"] = "Señal de la Luz"
	ns.L["Crusader Strike"] = "Golpe de cruzado"
	ns.L["Exorcist"] = "Exorcista"
	ns.L["Divine Sacrifice"] = "Sacrificio divino"
	ns.L["Divine Storm"] = "Tormenta divina"
	ns.L["Hand of Reckoning"] = "Mano de expiación"
	ns.L["Horn of Lordaeron"] = "Cuerno de Lordaeron"
	ns.L["Inspiration Exemplar"] = "Inspiración ejemplar"
	ns.L["Rebuke"] = "Reprimenda"
	ns.L["Seal of Martyrdom"] = "Sello de martirio"
	-- Priest
	ns.L["Circle of Healing"] = "Círculo de sanación"
	ns.L["Homunculi"] = "Homúnculos"
	ns.L["Mind Sear"] = "Abrasamiento mental"
	ns.L["Penance"] = "Penitencia"
	ns.L["Power Word: Barrier"] = "Palabra de poder: barrera"
	ns.L["Prayer of Mending"] = "Rezo de alivio"
	ns.L["Serendipity"] = "Serendipia"
	ns.L["Shadow Word: Death"] = "Palabra de las Sombras: muerte"
	ns.L["Shared Pain"] = "Dolor compartido"
	ns.L["Strength of Soul"] = "Fuerza del alma"
	ns.L["Twisted Faith"] = "Fe retorcida"
	ns.L["Void Plague"] = "Plaga del Vacío"
	-- Rogue
	ns.L["Between the Eyes"] = "Entre ceja y ceja"
	ns.L["Blade Dance"] = "Danza de hojas"
	ns.L["Deadly Brew"] = "Brebaje letal"
	ns.L["Envenom"] = "Envenenar"
	ns.L["Just a Flesh Wound"] = "Una simple herida superficial"
	ns.L["Main Gauche"] = "Daga de guardamano"
	ns.L["Mutilate"] = "Mutilar"
	ns.L["Quick Draw"] = "Desenvainado rápido"
	ns.L["Saber Slash"] = "Tajo de sable"
	ns.L["Shadowstrike"] = "Tenebrosa"
	ns.L["Slaughter from the Shadows"] = "Matanza desde las Sombras"
	ns.L["Shiv"] = "Puyazo"
	-- Shaman
	ns.L["Ancestral Guidance"] = "Guía ancestral"
	ns.L["Dual Wield Specialization"] = "Especialización en doble empuñadura"
	ns.L["Earth Shield"] = "Escudo de tierra"
	ns.L["Healing Rain"] = "Lluvia de sanación"
	ns.L["Lava Burst"] = "Ráfaga de lava"
	ns.L["Lava Lash"] = "Latigazo de lava"
	ns.L["Molten Blast"] = "Explosión de arrabio"
	ns.L["Overload"] = "Sobrecarga"
	ns.L["Shamanistic Rage"] = "Ira del chamán"
	ns.L["Shield Mastery"] = "Maestría con escudos"
	ns.L["Way of Earth"] = "Camino de la tierra"
	ns.L["Water Shield"] = "Escudo de agua"

elseif ns.locale == "frFR" then
	ns.L["AddOn Description"] = "Vous aide à collecter les runes Season of Discovery"
	ns.L["Arcane"] = "Arcanes"
	ns.L["Demonic"] = "Démoniaque"
	ns.L["Duty"] = "Devoir"
	ns.L["Mjolnir"] = "Mjolnir"
	-- Druid
	ns.L["Fury of Stormrage"] = "Fureur de Hurlorage"
	ns.L["Lacerate"] = "Lacérer"
	ns.L["Lifebloom"] = "Fleur de vie"
	ns.L["Living Seed"] = "Graine de vie"
	ns.L["Mangle"] = "Mutilation"
	ns.L["Savage Roar"] = "Rugissement sauvage"
	ns.L["Skull Bash"] = "Coup de crâne"
	ns.L["Starsurge"] = "Éruption stellaire"
	ns.L["Sunfire"] = "Éclat solaire"
	ns.L["Survival of the Fittest"] = "Survie du plus fort"
	ns.L["Wild Growth"] = "Croissance sauvage"
	ns.L["Wild Strikes"] = "Frappes féroces"
	-- Hunter
	ns.L["Beast Mastery"] = "Maîtrise des bêtes"
	ns.L["Carve"] = "Écharper"
	ns.L["Chimera Shot"] = "Tir de la chimère"
	ns.L["Cobra Strikes"] = "Frappes de cobra"
	ns.L["Explosive Shot"] = "Tir explosif"
	ns.L["Flanking Strike"] = "Frappe latérale"
	ns.L["Heart of the Lion"] = "Cœur de lion"
	ns.L["Kill Command"] = "Ordre de tuer"
	ns.L["Lone Wolf"] = "Loup solitaire"
	ns.L["Master Marksman"] = "Maître tireur"
	ns.L["Serpent Spread"] = "Propagation du serpent"
	ns.L["Sniper Training"] = "Entraînement de sniper"
	-- Mage
	ns.L["Arcane Blast"] = "Déflagration des arcanes"
	ns.L["Arcane Surge"] = "Éruption d’arcanes"
	ns.L["Burnout"] = "Ardeur épuisante"
	ns.L["Enlightenment"] = "Illumination"
	ns.L["Fingers of Frost"] = "Doigts de givre"
	ns.L["Ice Lance"] = "Javelot de glace"
	ns.L["Icy Veins"] = "Veines glaciales"
	ns.L["Living Bomb"] = "Bombe vivante"
	ns.L["Living Flame"] = "Flamme vivante"
	ns.L["Mass Regeneration"] = "Régénération de masse"
	ns.L["Regeneration"] = "Régénération"
	ns.L["Rewind Time"] = "Remonter le temps"
	-- Paladin
	ns.L["Aegis"] = "Egide"
	ns.L["Avenger's Shield"] = "Bouclier du vengeur"
	ns.L["Beacon of Light"] = "Guide de lumière"
	ns.L["Crusader Strike"] = "Frappe du croisé"
	ns.L["Exorcist"] = "Exorciste"
	ns.L["Divine Sacrifice"] = "Sacrifice divin"
	ns.L["Divine Storm"] = "Tempête divine"
	ns.L["Hand of Reckoning"] = "Main de rétribution"
	ns.L["Horn of Lordaeron"] = "Cor de Lordaeron"
	ns.L["Inspiration Exemplar"] = "Source d’inspiration"
	ns.L["Rebuke"] = "Réprimandes"
	ns.L["Seal of Martyrdom"] = "Sceau du martyr"
	-- Priest
	ns.L["Circle of Healing"] = "Cercle de soins"
	ns.L["Homunculi"] = "Homoncules"
	ns.L["Mind Sear"] = "Incandescence mentale"
	ns.L["Penance"] = "Pénitence"
	ns.L["Power Word: Barrier"] = "Mot de pouvoir : Barrière"
	ns.L["Prayer of Mending"] = "Prière de guérison"
	ns.L["Serendipity"] = "Heureux hasard"
	ns.L["Shadow Word: Death"] = "Mot de l’ombre : Mort"
	ns.L["Shared Pain"] = "Souffrance partagée"
	ns.L["Strength of Soul"] = "Force d’âme"
	ns.L["Twisted Faith"] = "Foi distordue"
	ns.L["Void Plague"] = "Fléau du Vide"
	-- Rogue
	ns.L["Between the Eyes"] = "Entre les deux yeux"
	ns.L["Blade Dance"] = "Danse des lames"
	ns.L["Deadly Brew"] = "Breuvage mortel"
	ns.L["Envenom"] = "Envenimer"
	ns.L["Just a Flesh Wound"] = "Juste une égratignure"
	ns.L["Main Gauche"] = "Main gauche"
	ns.L["Mutilate"] = "Estropier"
	ns.L["Quick Draw"] = "Tireur rapide"
	ns.L["Saber Slash"] = "Coup de sabre"
	ns.L["Shadowstrike"] = "Frappe-ténèbres"
	ns.L["Slaughter from the Shadows"] = "Ombres meurtrières"
	ns.L["Shiv"] = "Kriss"
	-- Shaman
	ns.L["Ancestral Guidance"] = "Soutien ancestral"
	ns.L["Dual Wield Specialization"] = "Spécialisation Ambidextrie"
	ns.L["Earth Shield"] = "Bouclier de terre"
	ns.L["Healing Rain"] = "Pluie guérisseuse"
	ns.L["Lava Burst"] = "Explosion de lave"
	ns.L["Lava Lash"] = "Latigazo de lava"
	ns.L["Molten Blast"] = "Éclair de lave"
	ns.L["Overload"] = "Surcharge"
	ns.L["Shamanistic Rage"] = "Rage du chaman"
	ns.L["Shield Mastery"] = "Maîtrise du bouclier"
	ns.L["Way of Earth"] = "Voie de la terre"
	ns.L["Water Shield"] = "Bouclier d’eau"

elseif ns.locale == "itIT" then
	ns.L["AddOn Description"] = "Ti aiuta a raccogliere le rune della Season of Discovery"
	ns.L["Arcane"] = "Arcana"
	ns.L["Demonic"] = "Demoniaca"
	ns.L["Duty"] = "Dovere"
	ns.L["Mjolnir"] = "Mjolnir"
	-- Druid
	ns.L["Fury of Stormrage"] = "Fury of Stormrage"
	ns.L["Lacerate"] = "Lacerazione"
	ns.L["Lifebloom"] = "Bocciolo di Vita"
	ns.L["Living Seed"] = "Living Seed"
	ns.L["Mangle"] = "Dilaniamento"
	ns.L["Savage Roar"] = "Ruggito Selvaggio"
	ns.L["Skull Bash"] = "Craniata"
	ns.L["Starsurge"] = "Cometa Arcana"
	ns.L["Sunfire"] = "Fuoco Solare"
	ns.L["Survival of the Fittest"] = "Legge del Più Forte"
	ns.L["Wild Growth"] = "Crescita Rigogliosa"
	ns.L["Wild Strikes"] = "Assalti Selvaggi"
	-- Hunter
	ns.L["Beast Mastery"] = "Affinità Animale"
	ns.L["Carve"] = "Scorticatura"
	ns.L["Chimera Shot"] = "Tiro della Chimera"
	ns.L["Cobra Strikes"] = "Tiro della Chimera"
	ns.L["Explosive Shot"] = "Tiro Esplosivo"
	ns.L["Flanking Strike"] = "Assalto Fiancheggiato"
	ns.L["Heart of the Lion"] = "Cuore del Leone"
	ns.L["Kill Command"] = "Ordine di Morte"
	ns.L["Lone Wolf"] = "Lupo Solitario"
	ns.L["Master Marksman"] = "Precisione da Cecchino"
	ns.L["Serpent Spread"] = "Serpent Spread"
	ns.L["Sniper Training"] = "Tiratore Scelto"
	-- Mage
	ns.L["Arcane Blast"] = "Detonazione Arcana"
	ns.L["Arcane Surge"] = "Eruzione Arcana"
	ns.L["Burnout"] = "Surriscaldamento"
	ns.L["Enlightenment"] = "Illuminazione"
	ns.L["Fingers of Frost"] = "Dita di Gelo"
	ns.L["Ice Lance"] = "Lancia di Ghiaccio"
	ns.L["Icy Veins"] = "Vene Gelide"
	ns.L["Living Bomb"] = "Bomba Vivente"
	ns.L["Living Flame"] = "Fiamma Vivente"
	ns.L["Mass Regeneration"] = "Rigenerazione di Massa"
	ns.L["Regeneration"] = "Rigenerazione"
	ns.L["Rewind Time"] = "Riavvolgimento Temporale"
	-- Paladin
	ns.L["Aegis"] = "Scudo"
	ns.L["Avenger's Shield"] = "Scudo del Vendicatore"
	ns.L["Beacon of Light"] = "Faro di Luce"
	ns.L["Crusader Strike"] = "Assalto del Crociato"
	ns.L["Exorcist"] = "Esorcista"
	ns.L["Divine Sacrifice"] = "Divine Sacrifice"
	ns.L["Divine Storm"] = "Tempesta Divina"
	ns.L["Hand of Reckoning"] = "Imposizione della Sfida"
	ns.L["Horn of Lordaeron"] = "Horn of Lordaeron"
	ns.L["Inspiration Exemplar"] = "Inspiration Exemplar"
	ns.L["Rebuke"] = "Predica"
	ns.L["Seal of Martyrdom"] = "Seal of Martyrdom"
	-- Priest
	ns.L["Circle of Healing"] = "Circolo di Guarigione"
	ns.L["Homunculi"] = "Homunculi"
	ns.L["Mind Sear"] = "Risonanza Mentale"
	ns.L["Penance"] = "Contrizione"
	ns.L["Power Word: Barrier"] = "Parola del Potere: Barriera"
	ns.L["Prayer of Mending"] = "Preghiera di Guarigione"
	ns.L["Serendipity"] = "Provvidenza"
	ns.L["Shadow Word: Death"] = "Parola d'Ombra: Morte"
	ns.L["Shared Pain"] = "Pena Condivisa"
	ns.L["Strength of Soul"] = "Forza d'Animo"
	ns.L["Twisted Faith"] = "Fede Distorta"
	ns.L["Void Plague"] = "Void Plague"
	-- Rogue
	ns.L["Between the Eyes"] = "In Mezzo agli Occhi"
	ns.L["Blade Dance"] = "Lame Danzanti"
	ns.L["Deadly Brew"] = "Miscela Letale"
	ns.L["Envenom"] = "Affondo Venefico"
	ns.L["Just a Flesh Wound"] = "È solo un graffio"
	ns.L["Main Gauche"] = "Doppio Attacco"
	ns.L["Mutilate"] = "Mutilazione"
	ns.L["Quick Draw"] = "Estrazione Rapida"
	ns.L["Saber Slash"] = "Fendente di Sciabola"
	ns.L["Shadowstrike"] = "Assalto d'Ombra"
	ns.L["Slaughter from the Shadows"] = "Slaughter from the Shadows"
	ns.L["Shiv"] = "Stilettata"
	-- Shaman
	ns.L["Ancestral Guidance"] = "Guida Ancestrale"
	ns.L["Dual Wield Specialization"] = "Specializzazione: Combattimento con Due Armi"
	ns.L["Earth Shield"] = "Scudo di Terra"
	ns.L["Healing Rain"] = "Pioggia Curativa"
	ns.L["Lava Burst"] = "Getto di Lava"
	ns.L["Lava Lash"] = "Sferzata Lavica"
	ns.L["Molten Blast"] = "Detonazione Fusa"
	ns.L["Overload"] = "Sovraccarico"
	ns.L["Shamanistic Rage"] = "Shamanistic Rage"
	ns.L["Shield Mastery"] = "Maestria nello Scudo"
	ns.L["Way of Earth"] = "Way of Earth"
	ns.L["Water Shield"] = "Scudo d'Acqua"

elseif ns.locale == "koKR" then
	ns.L["AddOn Description"] = "디스커버리 시즌 룬을 수집하는 데 도움이 됩니다."
	ns.L["Arcane"] = "비전"
	ns.L["Demonic"] = "악마의"
	ns.L["Duty"] = ""
	ns.L["Mjolnir"] = "묠니르"
	-- Druid
	ns.L["Fury of Stormrage"] = "스톰레이지의 격노"
	ns.L["Lacerate"] = "가르기"
	ns.L["Lifebloom"] = "피어나는 생명"
	ns.L["Living Seed"] = "살아있는 씨앗"
	ns.L["Mangle"] = "짓이기기"
	ns.L["Savage Roar"] = "야생의 포효"
	ns.L["Skull Bash"] = "두개골 강타"
	ns.L["Starsurge"] = "별빛쇄도"
	ns.L["Sunfire"] = "태양섬광"
	ns.L["Survival of the Fittest"] = "적자 생존"
	ns.L["Wild Growth"] = "급속 성장"
	ns.L["Wild Strikes"] = "야생의 강타"
	-- Hunter
	ns.L["Beast Mastery"] = "야수 숙련"
	ns.L["Carve"] = "저미기"
	ns.L["Chimera Shot"] = "키메라 사격"
	ns.L["Cobra Strikes"] = "코브라의 일격"
	ns.L["Explosive Shot"] = "폭발 사격"
	ns.L["Flanking Strike"] = "측방 강타"
	ns.L["Heart of the Lion"] = "사자의 심장"
	ns.L["Kill Command"] = "살상 명령"
	ns.L["Lone Wolf"] = "고독한 늑대"
	ns.L["Master Marksman"] = "사격의 명수"
	ns.L["Serpent Spread"] = "독사 확산"
	ns.L["Sniper Training"] = "저격 훈련"
	-- Mage
	ns.L["Arcane Blast"] = "비전 작렬"
	ns.L["Arcane Surge"] = "비전 쇄도"
	ns.L["Burnout"] = "완전 연소"
	ns.L["Enlightenment"] = "깨달음"
	ns.L["Fingers of Frost"] = "서리의 손가락"
	ns.L["Ice Lance"] = "얼음창"
	ns.L["Icy Veins"] = "얼음 핏줄"
	ns.L["Living Bomb"] = "살아있는 폭탄"
	ns.L["Living Flame"] = "살아있는 불꽃"
	ns.L["Mass Regeneration"] = "대규모 재생력"
	ns.L["Regeneration"] = "재생"
	ns.L["Rewind Time"] = "시간 되돌리기"
	-- Paladin
	ns.L["Aegis"] = "보호"
	ns.L["Avenger's Shield"] = "응징의 방패"
	ns.L["Beacon of Light"] = "빛의 봉화"
	ns.L["Crusader Strike"] = "성전사의 일격"
	ns.L["Exorcist"] = "퇴마사"
	ns.L["Divine Sacrifice"] = "성스러운 희생"
	ns.L["Divine Storm"] = "천상의 폭풍"
	ns.L["Hand of Reckoning"] = "심판의 손길"
	ns.L["Horn of Lordaeron"] = "로데론의 뿔피리"
	ns.L["Inspiration Exemplar"] = "영감의 모범"
	ns.L["Rebuke"] = "비난"
	ns.L["Seal of Martyrdom"] = "헌신의 문장"
	-- Priest
	ns.L["Circle of Healing"] = "치유의 마법진"
	ns.L["Homunculi"] = "호문쿨루스"
	ns.L["Mind Sear"] = "정신 불태우기"
	ns.L["Penance"] = "회개"
	ns.L["Power Word: Barrier"] = "신의 권능: 방벽"
	ns.L["Prayer of Mending"] = "회복의 기원"
	ns.L["Serendipity"] = "우연한 행운"
	ns.L["Shadow Word: Death"] = "어둠의 권능: 죽음"
	ns.L["Shared Pain"] = "나누는 고통"
	ns.L["Strength of Soul"] = "굳건한 정신"
	ns.L["Twisted Faith"] = "뒤틀린 믿음"
	ns.L["Void Plague"] = "공허의 역병"
	-- Rogue
	ns.L["Between the Eyes"] = "미간 적중"
	ns.L["Blade Dance"] = "칼춤"
	ns.L["Deadly Brew"] = "맹독 조합"
	ns.L["Envenom"] = "독살"
	ns.L["Just a Flesh Wound"] = "얕은 상처일 뿐"
	ns.L["Main Gauche"] = "맹고쉬"
	ns.L["Mutilate"] = "절단"
	ns.L["Quick Draw"] = "빠른 사격"
	ns.L["Saber Slash"] = "사브르 베기"
	ns.L["Shadowstrike"] = "그림자 일격"
	ns.L["Slaughter from the Shadows"] = "어둠의 학살자"
	ns.L["Shiv"] = "독칼"
	-- Shaman
	ns.L["Ancestral Guidance"] = "고대의 인도"
	ns.L["Dual Wield Specialization"] = "쌍수 무기 전문화"
	ns.L["Earth Shield"] = "대지의 보호막"
	ns.L["Healing Rain"] = "치유의 비"
	ns.L["Lava Burst"] = "용암 폭발"
	ns.L["Lava Lash"] = "용암 채찍"
	ns.L["Molten Blast"] = "용암 작열"
	ns.L["Overload"] = "과부하"
	ns.L["Shamanistic Rage"] = "주술의 분노"
	ns.L["Shield Mastery"] = "방패 숙련"
	ns.L["Way of Earth"] = "대지의 길"
	ns.L["Water Shield"] = "물의 보호막"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["AddOn Description"] = "Ajuda você a coletar runas da Temporada de Descoberta"
	ns.L["Arcane"] = "Arcana"
	ns.L["Demonic"] = "Demoníaca"
	ns.L["Duty"] = "Dever"
	ns.L["Mjolnir"] = "Mjolnir"
	-- Druid
	ns.L["Fury of Stormrage"] = "Fúria de Tempesfúria"
	ns.L["Lacerate"] = "Lacerar"
	ns.L["Lifebloom"] = "Brotar da Vida"
	ns.L["Living Seed"] = "Semente Viva"
	ns.L["Mangle"] = "Destroçar"
	ns.L["Savage Roar"] = "Rugido Selvagem"
	ns.L["Skull Bash"] = "Esmagar Crânio"
	ns.L["Starsurge"] = "Surto Estelar"
	ns.L["Sunfire"] = "Fogo Solar"
	ns.L["Survival of the Fittest"] = "A Lei da Selva"
	ns.L["Wild Growth"] = "Crescimento Silvestre"
	ns.L["Wild Strikes"] = "Golpes Selvagens"
	-- Hunter
	ns.L["Beast Mastery"] = "Domínio das Feras"
	ns.L["Carve"] = "Trinchar"
	ns.L["Chimera Shot"] = "Tiro Quimérico"
	ns.L["Cobra Strikes"] = "Golpes de Naja"
	ns.L["Explosive Shot"] = "Tiro Explosivo"
	ns.L["Flanking Strike"] = "Ataque Flanqueante"
	ns.L["Heart of the Lion"] = "Coração de Leão"
	ns.L["Kill Command"] = "Comando para Matar"
	ns.L["Lone Wolf"] = "Lobo Solitário"
	ns.L["Master Marksman"] = "Mestre Atirador Perito"
	ns.L["Serpent Spread"] = "Espalhar de Serpente"
	ns.L["Sniper Training"] = "Treinamento de Franco-atirador"
	-- Mage
	ns.L["Arcane Blast"] = "Impacto Arcano"
	ns.L["Arcane Surge"] = "Surto Arcano"
	ns.L["Burnout"] = "Combustão"
	ns.L["Enlightenment"] = "Esclarecimento"
	ns.L["Fingers of Frost"] = "Dedos Glaciais"
	ns.L["Ice Lance"] = "Lança de Gelo"
	ns.L["Icy Veins"] = "Veias Gélidas"
	ns.L["Living Bomb"] = "Bomba Viva"
	ns.L["Living Flame"] = "Chama Viva"
	ns.L["Mass Regeneration"] = "Regeneração em Massa"
	ns.L["Regeneration"] = "Regeneração"
	ns.L["Rewind Time"] = "Retroceder Tempo"
	-- Paladin
	ns.L["Aegis"] = "Égide"
	ns.L["Avenger's Shield"] = "Escudo do Vingador"
	ns.L["Beacon of Light"] = "Foco de Luz"
	ns.L["Crusader Strike"] = "Golpe do Cruzado"
	ns.L["Exorcist"] = "Exorcista"
	ns.L["Divine Sacrifice"] = "Sacrifício Divino"
	ns.L["Divine Storm"] = "Tempestade Divina"
	ns.L["Hand of Reckoning"] = "Mão da Desforra"
	ns.L["Horn of Lordaeron"] = "Trompa de Lordaeron"
	ns.L["Inspiration Exemplar"] = "Modelo de Inspiração"
	ns.L["Rebuke"] = "Repreensão"
	ns.L["Seal of Martyrdom"] = "Selo do Martírio"
	-- Priest
	ns.L["Circle of Healing"] = "Círculo de Cura"
	ns.L["Homunculi"] = "Homúnculos"
	ns.L["Mind Sear"] = "Calcinação Mental"
	ns.L["Penance"] = "Penitência"
	ns.L["Power Word: Barrier"] = "Palavra de Poder: Barreira"
	ns.L["Prayer of Mending"] = "Prece da Recomposição"
	ns.L["Serendipity"] = "Serendipidade"
	ns.L["Shadow Word: Death"] = "Palavra Sombria: Morte"
	ns.L["Shared Pain"] = "Dor Compartilhada"
	ns.L["Strength of Soul"] = "Força da Alma"
	ns.L["Twisted Faith"] = "Fé Corrompida"
	ns.L["Void Plague"] = "Peste do Caos"
	-- Rogue
	ns.L["Between the Eyes"] = "No Meio da Testa"
	ns.L["Blade Dance"] = "Dança de Lâminas"
	ns.L["Deadly Brew"] = "Mistura Mortífera"
	ns.L["Envenom"] = "Envenenar"
	ns.L["Just a Flesh Wound"] = "Só Um Arranhão"
	ns.L["Main Gauche"] = "Adaga de Bloqueio"
	ns.L["Mutilate"] = "Mutilar"
	ns.L["Quick Draw"] = "Saque Rápido"
	ns.L["Saber Slash"] = "Talho de Sabre"
	ns.L["Shadowstrike"] = "Golpe Sombrio"
	ns.L["Slaughter from the Shadows"] = "Atacar das Sombras"
	ns.L["Shiv"] = "Estocada"
	-- Shaman
	ns.L["Ancestral Guidance"] = "Conselho dos Ancestrais"
	ns.L["Dual Wield Specialization"] = "Especialização em Duas Armas"
	ns.L["Earth Shield"] = "Escudo da Terra"
	ns.L["Healing Rain"] = "Chuva Curativa"
	ns.L["Lava Burst"] = "Estouro de Lava"
	ns.L["Lava Lash"] = "Açoite de Lava"
	ns.L["Molten Blast"] = "Impacto Derretido"
	ns.L["Overload"] = "Sobrecarga"
	ns.L["Shamanistic Rage"] = "Fúria Xamanística"
	ns.L["Shield Mastery"] = "Proficiência em Escudo"
	ns.L["Way of Earth"] = "Caminho Telúrico"
	ns.L["Water Shield"] = "Escudo de Água"

elseif ns.locale == "ruRU" then
	ns.L["AddOn Description"] = "Помогает вам собирать руны сезона открытий"
	ns.L["Arcane"] = "Чародейская"
	ns.L["Demonic"] = "Демоническая"
	ns.L["Duty"] = "долга"
	ns.L["Mjolnir"] = "Мьольнира"
	-- Druid
	ns.L["Fury of Stormrage"] = "Гнев Ярости Бури"
	ns.L["Lacerate"] = "Растерзать"
	ns.L["Lifebloom"] = "Жизнецвет"
	ns.L["Living Seed"] = "Семя жизни"
	ns.L["Mangle"] = "Увечье"
	ns.L["Savage Roar"] = "Дикий рев"
	ns.L["Skull Bash"] = "Лобовая атака"
	ns.L["Starsurge"] = "Звездный поток"
	ns.L["Sunfire"] = "Солнечный огонь"
	ns.L["Survival of the Fittest"] = "Выживание сильнейших"
	ns.L["Wild Growth"] = "Буйный рост"
	ns.L["Wild Strikes"] = "Дикие удары"
	-- Hunter
	ns.L["Beast Mastery"] = "Повелитель зверей"
	ns.L["Carve"] = "Разделка туши"
	ns.L["Chimera Shot"] = "Выстрел химеры"
	ns.L["Cobra Strikes"] = "Бросок кобры"
	ns.L["Explosive Shot"] = "Разрывной выстрел"
	ns.L["Flanking Strike"] = "Обходной удар"
	ns.L["Heart of the Lion"] = "Львиное сердце"
	ns.L["Kill Command"] = "Команда \"Взять!\""
	ns.L["Lone Wolf"] = "Одинокий волк"
	ns.L["Master Marksman"] = "Мастер стрельбы"
	ns.L["Serpent Spread"] = "Распространяющийся укус"
	ns.L["Sniper Training"] = "Навыки снайпера"
	-- Mage
	ns.L["Arcane Blast"] = "Чародейская вспышка"
	ns.L["Arcane Surge"] = "Чародейский выброс"
	ns.L["Burnout"] = "Выгорание"
	ns.L["Enlightenment"] = "Просветление"
	ns.L["Fingers of Frost"] = "Ледяные пальцы"
	ns.L["Ice Lance"] = "Ледяное копье"
	ns.L["Icy Veins"] = "Стылая кровь"
	ns.L["Living Bomb"] = "Живая бомба"
	ns.L["Living Flame"] = "Живой жар"
	ns.L["Mass Regeneration"] = "Массовая регенерация"
	ns.L["Regeneration"] = "Регенерация"
	ns.L["Rewind Time"] = "Перемотка времени"
	-- Paladin
	ns.L["Aegis"] = "Эгида"
	ns.L["Avenger's Shield"] = "Щит мстителя"
	ns.L["Beacon of Light"] = "Частица Света"
	ns.L["Crusader Strike"] = "Удар воина Света"
	ns.L["Exorcist"] = "Экзорцист"
	ns.L["Divine Sacrifice"] = "Священная жертва"
	ns.L["Divine Storm"] = "Божественная буря"
	ns.L["Hand of Reckoning"] = "Длань возмездия"
	ns.L["Horn of Lordaeron"] = "Горн Лордерона"
	ns.L["Inspiration Exemplar"] = "Пример для подражания"
	ns.L["Rebuke"] = "Укор"
	ns.L["Seal of Martyrdom"] = "Печать мученичества"
	-- Priest
	ns.L["Circle of Healing"] = "Круг исцеления"
	ns.L["Homunculi"] = "Гомункулы"
	ns.L["Mind Sear"] = "Иссушение разума"
	ns.L["Penance"] = "Исповедь"
	ns.L["Power Word: Barrier"] = "Слово Силы: Барьер"
	ns.L["Prayer of Mending"] = "Молитва восстановления"
	ns.L["Serendipity"] = "Прозорливость"
	ns.L["Shadow Word: Death"] = "Слово Тьмы: Смерть"
	ns.L["Shared Pain"] = "Общая боль"
	ns.L["Strength of Soul"] = "Сила души"
	ns.L["Twisted Faith"] = "Обман разума"
	ns.L["Void Plague"] = "Чума Бездны"
	-- Rogue
	ns.L["Between the Eyes"] = "Промеж глаз"
	ns.L["Blade Dance"] = "Танец клинков"
	ns.L["Deadly Brew"] = "Смертельное варево"
	ns.L["Envenom"] = "Отравление"
	ns.L["Just a Flesh Wound"] = "Просто царапина"
	ns.L["Main Gauche"] = "Главный аргумент"
	ns.L["Mutilate"] = "Расправа"
	ns.L["Quick Draw"] = "Быстрая реакция"
	ns.L["Saber Slash"] = "Удар саблей"
	ns.L["Shadowstrike"] = "Теневой удар"
	ns.L["Slaughter from the Shadows"] = "Резня во тьме"
	ns.L["Shiv"] = "Отравляющий укол"
	-- Shaman
	ns.L["Ancestral Guidance"] = "Наставления предков"
	ns.L["Dual Wield Specialization"] = "Специализация на бое с оружием в обеих руках"
	ns.L["Earth Shield"] = "Щит земли"
	ns.L["Healing Rain"] = "Целительный ливень"
	ns.L["Lava Burst"] = "Выброс лавы"
	ns.L["Lava Lash"] = "Вскипание лавы"
	ns.L["Molten Blast"] = "Всплеск лавы"
	ns.L["Overload"] = "Перегрузка"
	ns.L["Shamanistic Rage"] = "Ярость шамана"
	ns.L["Shield Mastery"] = "Мастерское владение щитом"
	ns.L["Way of Earth"] = "Путь земли"
	ns.L["Water Shield"] = "Водный щит"

elseif ns.locale == "zhCN" then
	ns.L["AddOn Description"] = "帮助您收集发现季节符文"
	ns.L["Arcane"] = "奥术"
	ns.L["Demonic"] = "恶魔"
	ns.L["Duty"] = "义务"
	ns.L["Mjolnir"] = "雷神"
	-- Druid
	ns.L["Fury of Stormrage"] = "怒风之怒"
	ns.L["Lacerate"] = "割伤"
	ns.L["Lifebloom"] = "生命绽放"
	ns.L["Living Seed"] = "生命之种"
	ns.L["Mangle"] = "割碎"
	ns.L["Savage Roar"] = "野蛮咆哮"
	ns.L["Skull Bash"] = "迎头痛击"
	ns.L["Starsurge"] = "星涌术"
	ns.L["Sunfire"] = "阳炎术"
	ns.L["Survival of the Fittest"] = "优胜劣汰"
	ns.L["Wild Growth"] = "野性成长"
	ns.L["Wild Strikes"] = "狂野打击"
	-- Hunter
	ns.L["Beast Mastery"] = "野兽控制"
	ns.L["Carve"] = "削凿"
	ns.L["Chimera Shot"] = "奇美拉射击"
	ns.L["Cobra Strikes"] = "眼镜蛇打击"
	ns.L["Explosive Shot"] = "爆炸射击"
	ns.L["Flanking Strike"] = "侧翼打击"
	ns.L["Heart of the Lion"] = "雄狮之心"
	ns.L["Kill Command"] = "杀戮命令"
	ns.L["Lone Wolf"] = "独来独往"
	ns.L["Master Marksman"] = "神射手"
	ns.L["Serpent Spread"] = "毒蛇扩散"
	ns.L["Sniper Training"] = "狙击训练"
	-- Mage
	ns.L["Arcane Blast"] = "奥术冲击"
	ns.L["Arcane Surge"] = "奥术涌动"
	ns.L["Burnout"] = "燃尽"
	ns.L["Enlightenment"] = "启迪"
	ns.L["Fingers of Frost"] = "寒冰指"
	ns.L["Ice Lance"] = "冰枪术"
	ns.L["Icy Veins"] = "冰冷血脉"
	ns.L["Living Bomb"] = "活动炸弹"
	ns.L["Living Flame"] = "活体烈焰"
	ns.L["Mass Regeneration"] = "群体再生"
	ns.L["Regeneration"] = "再生"
	ns.L["Rewind Time"] = "时光倒转"
	-- Paladin
	ns.L["Aegis"] = "神盾"
	ns.L["Avenger's Shield"] = "复仇者之盾"
	ns.L["Beacon of Light"] = "圣光道标"
	ns.L["Crusader Strike"] = "十字军打击"
	ns.L["Exorcist"] = "驱魔人"
	ns.L["Divine Sacrifice"] = "神圣牺牲"
	ns.L["Divine Storm"] = "神圣风暴"
	ns.L["Hand of Reckoning"] = "清算之手"
	ns.L["Horn of Lordaeron"] = "洛丹伦号角"
	ns.L["Inspiration Exemplar"] = "激励典范"
	ns.L["Rebuke"] = "责难"
	ns.L["Seal of Martyrdom"] = "殉道圣印"
	-- Priest
	ns.L["Circle of Healing"] = "治疗之环"
	ns.L["Homunculi"] = "裂魂魔"
	ns.L["Mind Sear"] = "精神灼烧"
	ns.L["Penance"] = "苦修"
	ns.L["Power Word: Barrier"] = "真言术：障"
	ns.L["Prayer of Mending"] = "愈合祷言"
	ns.L["Serendipity"] = "妙手回春"
	ns.L["Shadow Word: Death"] = "暗言术：灭"
	ns.L["Shared Pain"] = "分担痛苦"
	ns.L["Strength of Soul"] = "灵魂之力"
	ns.L["Twisted Faith"] = "扭曲信仰"
	ns.L["Void Plague"] = "虚空疫病"
	-- Rogue
	ns.L["Between the Eyes"] = "正中眉心"
	ns.L["Blade Dance"] = "刃舞"
	ns.L["Deadly Brew"] = "致命阴谋"
	ns.L["Envenom"] = "毒伤"
	ns.L["Just a Flesh Wound"] = "只是皮肉伤"
	ns.L["Main Gauche"] = "左右开弓"
	ns.L["Mutilate"] = "毁伤"
	ns.L["Quick Draw"] = "速射"
	ns.L["Saber Slash"] = "军刀猛刺"
	ns.L["Shadowstrike"] = "暗影打击"
	ns.L["Slaughter from the Shadows"] = "暗影杀手"
	ns.L["Shiv"] = "毒刃"
	-- Shaman
	ns.L["Ancestral Guidance"] = "先祖指引"
	ns.L["Dual Wield Specialization"] = "双武器专精"
	ns.L["Earth Shield"] = "大地之盾"
	ns.L["Healing Rain"] = "治疗之雨"
	ns.L["Lava Burst"] = "熔岩爆裂"
	ns.L["Lava Lash"] = "熔岩猛击"
	ns.L["Molten Blast"] = "熔火爆裂"
	ns.L["Overload"] = "过载"
	ns.L["Shamanistic Rage"] = "萨满之怒"
	ns.L["Shield Mastery"] = "盾牌精通"
	ns.L["Way of Earth"] = "土之道"
	ns.L["Water Shield"] = "水之护盾"
	
elseif ns.locale == "zhTW" then
	ns.L["AddOn Description"] = "幫助您收集發現季節符文"
	ns.L["Arcane"] = "奧術"
	ns.L["Demonic"] = "惡魔"
	ns.L["Duty"] = "義務"
	ns.L["Mjolnir"] = "雷神"
	-- Druid
	ns.L["Fury of Stormrage"] = "怒風之怒"
	ns.L["Lacerate"] = "割傷"
	ns.L["Lifebloom"] = "生命綻放"
	ns.L["Living Seed"] = "生命之種"
	ns.L["Mangle"] = "割碎"
	ns.L["Savage Roar"] = "野蠻咆哮"
	ns.L["Skull Bash"] = "迎頭痛擊"
	ns.L["Starsurge"] = "星湧術"
	ns.L["Sunfire"] = "陽炎術"
	ns.L["Survival of the Fittest"] = "優勝劣汰"
	ns.L["Wild Growth"] = "野性成長"
	ns.L["Wild Strikes"] = "狂野打擊"
	-- Hunter
	ns.L["Beast Mastery"] = "野獸控制"
	ns.L["Carve"] = "削鑿"
	ns.L["Chimera Shot"] = "奇美拉射擊"
	ns.L["Cobra Strikes"] = "眼鏡蛇打擊"
	ns.L["Explosive Shot"] = "爆炸射擊"
	ns.L["Flanking Strike"] = "側翼打擊"
	ns.L["Heart of the Lion"] = "雄獅之心"
	ns.L["Kill Command"] = "殺戮命令"
	ns.L["Lone Wolf"] = "獨來獨往"
	ns.L["Master Marksman"] = "神射手"
	ns.L["Serpent Spread"] = "毒蛇擴散"
	ns.L["Sniper Training"] = "狙擊訓練"
	-- Mage
	ns.L["Arcane Blast"] = "奧術衝擊"
	ns.L["Arcane Surge"] = "奧術湧動"
	ns.L["Burnout"] = "燃盡"
	ns.L["Enlightenment"] = "啟迪"
	ns.L["Fingers of Frost"] = "寒冰指"
	ns.L["Ice Lance"] = "冰槍術"
	ns.L["Icy Veins"] = "冰冷血脈"
	ns.L["Living Bomb"] = "活動炸彈"
	ns.L["Living Flame"] = "活體烈焰"
	ns.L["Mass Regeneration"] = "群體再生"
	ns.L["Regeneration"] = "再生"
	ns.L["Rewind Time"] = "時光倒轉"
	-- Paladin
	ns.L["Aegis"] = "神盾"
	ns.L["Avenger's Shield"] = "復仇者之盾"
	ns.L["Beacon of Light"] = "聖道標"
	ns.L["Crusader Strike"] = "十字軍打擊"
	ns.L["Exorcist"] = "驅魔人"
	ns.L["Divine Sacrifice"] = "神聖犧牲"
	ns.L["Divine Storm"] = "神聖風暴"
	ns.L["Hand of Reckoning"] = "清算之手"
	ns.L["Horn of Lordaeron"] = "洛丹倫號角"
	ns.L["Inspiration Exemplar"] = "激勵典範"
	ns.L["Rebuke"] = "責難"
	ns.L["Seal of Martyrdom"] = "殉道聖印"
	-- Priest
	ns.L["Circle of Healing"] = "治療之環"
	ns.L["Homunculi"] = "裂魂魔"
	ns.L["Mind Sear"] = "精神灼燒"
	ns.L["Penance"] = "苦修"
	ns.L["Power Word: Barrier"] = "真言術：障"
	ns.L["Prayer of Mending"] = "癒合禱言"
	ns.L["Serendipity"] = "妙手回春"
	ns.L["Shadow Word: Death"] = "暗言術：滅"
	ns.L["Shared Pain"] = "分擔痛苦"
	ns.L["Strength of Soul"] = "靈魂之力"
	ns.L["Twisted Faith"] = "扭曲信仰"
	ns.L["Void Plague"] = "虛空疫病"
	-- Rogue
	ns.L["Between the Eyes"] = "正中眉心"
	ns.L["Blade Dance"] = "刃舞"
	ns.L["Deadly Brew"] = "致命陰謀"
	ns.L["Envenom"] = "毒傷"
	ns.L["Just a Flesh Wound"] = "只是皮肉傷"
	ns.L["Main Gauche"] = "左右開弓"
	ns.L["Mutilate"] = "毀傷"
	ns.L["Quick Draw"] = "速射"
	ns.L["Saber Slash"] = "軍刀猛刺"
	ns.L["Shadowstrike"] = "暗影打擊"
	ns.L["Slaughter from the Shadows"] = "暗影殺手"
	ns.L["Shiv"] = "毒刃"
	-- Shaman
	ns.L["Ancestral Guidance"] = "先祖指引"
	ns.L["Dual Wield Specialization"] = "雙武器專精"
	ns.L["Earth Shield"] = "大地之盾"
	ns.L["Healing Rain"] = "治療之雨"
	ns.L["Lava Burst"] = "熔岩爆裂"
	ns.L["Lava Lash"] = "熔岩猛擊"
	ns.L["Molten Blast"] = "熔火爆裂"
	ns.L["Overload"] = "過載"
	ns.L["Shamanistic Rage"] = "薩滿之怒"
	ns.L["Shield Mastery"] = "盾牌精通"
	ns.L["Way of Earth"] = "土之道"
	ns.L["Water Shield"] = "水之護盾"

else
	ns.L["AddOn Description"] = "Helps you to collect Season of Discovery runes"	
end