-- Generated by NextActionGuide Data Generator
-- Product: The Burning Crusade Classic
-- Build: 2.5.5.64912
-- Generated: 2025-12-19 07:22:41

local _, ns = ...
ns.data = ns.data or {}
ns.data.tbc = ns.data.tbc or {}

ns.data.tbc.TierSets = {
    [1] = {
        name = "The Gladiator",
        bonuses = {            [2] = { spellId = 41863 },            [3] = { spellId = 41864 },            [4] = { spellId = 41861 },            [5] = { spellId = 41862 },        }
    },
    [41] = {
        name = "Dal'Rend's Arms",
        bonuses = {            [2] = { spellId = 41719 },        }
    },
    [65] = {
        name = "Spider's Kiss",
        bonuses = {            [2] = { spellId = 17332 },        }
    },
    [81] = {
        name = "The Postmaster",
        bonuses = {            [2] = { spellId = 41873 },            [3] = { spellId = { 41870, 41871 } },            [4] = { spellId = 41872 },            [5] = { spellId = { 41869, 17498 } },        }
    },
    [121] = {
        name = "Cadaverous Garb",
        bonuses = {            [2] = { spellId = 41681 },            [3] = { spellId = 41645 },            [4] = { spellId = 41680 },            [5] = { spellId = 41679 },        }
    },
    [122] = {
        name = "Necropile Raiment",
        bonuses = {            [2] = { spellId = 41642 },            [3] = { spellId = 41827 },            [4] = { spellId = 41826 },            [5] = { spellId = 41825 },        }
    },
    [123] = {
        name = "Bloodmail Regalia",
        bonuses = {            [2] = { spellId = 41671 },            [3] = { spellId = 41672 },            [4] = { spellId = 41673 },            [5] = { spellId = 41674 },        }
    },
    [124] = {
        name = "Deathbone Guardian",
        bonuses = {            [2] = { spellId = 41726 },            [3] = { spellId = 41725 },            [4] = { spellId = 41724 },            [5] = { spellId = 41723 },        }
    },
    [141] = {
        name = "Volcanic Armor",
        bonuses = {            [3] = { spellId = 9233 },        }
    },
    [142] = {
        name = "Stormshroud Armor",
        bonuses = {            [2] = { spellId = 18979 },            [3] = { spellId = 23863 },            [4] = { spellId = 41845 },        }
    },
    [143] = {
        name = "Devilsaur Armor",
        bonuses = {            [2] = { spellId = 39516 },        }
    },
    [144] = {
        name = "Ironfeather Armor",
        bonuses = {            [2] = { spellId = 41780 },        }
    },
    [161] = {
        name = "Defias Leather",
        bonuses = {            [2] = { spellId = 41731 },            [3] = { spellId = 41732 },            [4] = { spellId = 41730 },            [5] = { spellId = 41733 },        }
    },
    [162] = {
        name = "Embrace of the Viper",
        bonuses = {            [2] = { spellId = 41740 },            [3] = { spellId = 41739 },            [4] = { spellId = 41644 },            [5] = { spellId = 41741 },        }
    },
    [163] = {
        name = "Chain of the Scarlet Crusade",
        bonuses = {            [2] = { spellId = 41686 },            [3] = { spellId = 41641 },            [4] = { spellId = 41685 },            [5] = { spellId = 41684 },            [6] = { spellId = 41683 },        }
    },
    [181] = {
        name = "Magister's Regalia",
        bonuses = {            [2] = { spellId = 29091 },            [4] = { spellId = 30777 },            [6] = { spellId = 27867 },            [8] = { spellId = 41822 },        }
    },
    [182] = {
        name = "Vestments of the Devout",
        bonuses = {            [2] = { spellId = 41881 },            [4] = { spellId = 41879 },            [6] = { spellId = 27778 },            [8] = { spellId = 41880 },        }
    },
    [183] = {
        name = "Dreadmist Raiment",
        bonuses = {            [2] = { spellId = 41738 },            [4] = { spellId = 41736 },            [6] = { spellId = 27780 },            [8] = { spellId = 41737 },        }
    },
    [184] = {
        name = "Shadowcraft Armor",
        bonuses = {            [2] = { spellId = 29096 },            [4] = { spellId = 41835 },            [6] = { spellId = 27787 },            [8] = { spellId = 41836 },        }
    },
    [185] = {
        name = "Wildheart Raiment",
        bonuses = {            [2] = { spellId = 29097 },            [4] = { spellId = { 41892, 41891 } },            [6] = { spellId = 27781 },            [8] = { spellId = 41893 },        }
    },
    [186] = {
        name = "Beaststalker Armor",
        bonuses = {            [2] = { spellId = 29094 },            [4] = { spellId = 30772 },            [6] = { spellId = 27785 },            [8] = { spellId = 41668 },        }
    },
    [187] = {
        name = "The Elements",
        bonuses = {            [2] = { spellId = 29095 },            [4] = { spellId = 41856 },            [6] = { spellId = 27774 },            [8] = { spellId = 41857 },        }
    },
    [188] = {
        name = "Lightforge Armor",
        bonuses = {            [2] = { spellId = 29093 },            [4] = { spellId = 41818 },            [6] = { spellId = 27498 },            [8] = { spellId = 41819 },        }
    },
    [189] = {
        name = "Battlegear of Valor",
        bonuses = {            [2] = { spellId = 29092 },            [4] = { spellId = 30770 },            [6] = { spellId = 27419 },            [8] = { spellId = 18679 },        }
    },
    [201] = {
        name = "Arcanist Regalia",
        bonuses = {            [3] = { spellId = 41657 },            [5] = { spellId = 41656 },            [8] = { spellId = 23545 },        }
    },
    [202] = {
        name = "Vestments of Prophecy",
        bonuses = {            [3] = { spellId = 21973 },            [5] = { spellId = 21092 },            [8] = { spellId = 23550 },        }
    },
    [203] = {
        name = "Felheart Raiment",
        bonuses = {            [3] = { spellId = 23554 },            [5] = { spellId = 21741 },            [8] = { spellId = 23553 },        }
    },
    [204] = {
        name = "Nightslayer Armor",
        bonuses = {            [3] = { spellId = 21874 },            [5] = { spellId = 21975 },            [8] = { spellId = 23582 },        }
    },
    [205] = {
        name = "Cenarion Raiment",
        bonuses = {            [3] = { spellId = 23557 },            [5] = { spellId = 39507 },            [8] = { spellId = 23556 },        }
    },
    [206] = {
        name = "Giantstalker Armor",
        bonuses = {            [3] = { spellId = 23560 },            [5] = { spellId = 21926 },            [8] = { spellId = 23566 },        }
    },
    [207] = {
        name = "The Earthfury",
        bonuses = {            [3] = { spellId = 21895 },            [5] = { spellId = 23572 },            [8] = { spellId = 23573 },        }
    },
    [208] = {
        name = "Lawbringer Armor",
        bonuses = {            [3] = { spellId = 23564 },            [5] = { spellId = { 41784, 41785 } },            [8] = { spellId = 21747 },        }
    },
    [209] = {
        name = "Battlegear of Might",
        bonuses = {            [3] = { spellId = 23562 },            [5] = { spellId = 21838 },            [8] = { spellId = 23561 },        }
    },
    [210] = {
        name = "Netherwind Regalia",
        bonuses = {            [3] = { spellId = 21879 },            [5] = { spellId = 23549 },            [8] = { spellId = 22007 },        }
    },
    [211] = {
        name = "Vestments of Transcendence",
        bonuses = {            [3] = { spellId = 21894 },            [5] = { spellId = 21853 },            [8] = { spellId = 22010 },        }
    },
    [212] = {
        name = "Nemesis Raiment",
        bonuses = {            [3] = { spellId = 32449 },            [5] = { spellId = 21922 },            [8] = { spellId = 23555 },        }
    },
    [213] = {
        name = "Bloodfang Armor",
        bonuses = {            [3] = { spellId = 21881 },            [5] = { spellId = 23558 },            [8] = { spellId = 23581 },        }
    },
    [214] = {
        name = "Stormrage Raiment",
        bonuses = {            [3] = { spellId = 21894 },            [5] = { spellId = 21872 },            [8] = { spellId = 21871 },        }
    },
    [215] = {
        name = "Dragonstalker Armor",
        bonuses = {            [3] = { spellId = 23559 },            [5] = { spellId = 21928 },            [8] = { spellId = 23578 },        }
    },
    [216] = {
        name = "The Ten Storms",
        bonuses = {            [3] = { spellId = 21899 },            [5] = { spellId = 23570 },            [8] = { spellId = 23551 },        }
    },
    [217] = {
        name = "Judgement Armor",
        bonuses = {            [3] = { spellId = 23565 },            [5] = { spellId = 41782 },            [8] = { spellId = 23591 },        }
    },
    [218] = {
        name = "Battlegear of Wrath",
        bonuses = {            [3] = { spellId = 23563 },            [5] = { spellId = 21890 },            [8] = { spellId = 23548 },        }
    },
    [221] = {
        name = "Garb of Thero-shan",
        bonuses = {            [6] = { spellId = 41772 },        }
    },
    [241] = {
        name = "Shard of the Gods",
        bonuses = {            [2] = { spellId = 41838 },        }
    },
    [261] = {
        name = "Spirit of Eskhandar",
        bonuses = {            [4] = { spellId = 22648 },        }
    },
    [281] = {
        name = "Champion's Battlegear",
        bonuses = {            [2] = { spellId = 41690 },            [4] = { spellId = 22738 },            [6] = { spellId = 41653 },        }
    },
    [282] = {
        name = "Lieutenant Commander's Battlegear",
        bonuses = {            [2] = { spellId = 41793 },            [4] = { spellId = 22738 },            [6] = { spellId = 41792 },        }
    },
    [301] = {
        name = "Champion's Earthshaker",
        bonuses = {            [2] = { spellId = 41693 },            [4] = { spellId = 22804 },            [6] = { spellId = 41692 },        }
    },
    [321] = {
        name = "Imperial Plate",
        bonuses = {            [2] = { spellId = 41779 },            [4] = { spellId = 41647 },            [6] = { spellId = 41778 },        }
    },
    [341] = {
        name = "Champion's Regalia",
        bonuses = {            [2] = { spellId = 41709 },            [4] = { spellId = 23025 },            [6] = { spellId = 41708 },        }
    },
    [342] = {
        name = "Champion's Raiment",
        bonuses = {            [2] = { spellId = 41703 },            [4] = { spellId = 23044 },            [6] = { spellId = 41702 },        }
    },
    [343] = {
        name = "Lieutenant Commander's Regalia",
        bonuses = {            [2] = { spellId = 41811 },            [4] = { spellId = 23025 },            [6] = { spellId = 41810 },        }
    },
    [344] = {
        name = "Lieutenant Commander's Raiment",
        bonuses = {            [2] = { spellId = 41805 },            [4] = { spellId = 23044 },            [6] = { spellId = 41804 },        }
    },
    [345] = {
        name = "Champion's Threads",
        bonuses = {            [2] = { spellId = 41715 },            [4] = { spellId = 23047 },            [6] = { spellId = 41714 },        }
    },
    [346] = {
        name = "Lieutenant Commander's Threads",
        bonuses = {            [2] = { spellId = 41815 },            [4] = { spellId = 23047 },            [6] = { spellId = 41814 },        }
    },
    [347] = {
        name = "Champion's Vestments",
        bonuses = {            [2] = { spellId = 41717 },            [4] = { spellId = 23048 },            [6] = { spellId = 41716 },        }
    },
    [348] = {
        name = "Lieutenant Commander's Vestments",
        bonuses = {            [2] = { spellId = 41817 },            [4] = { spellId = 23048 },            [6] = { spellId = 41816 },        }
    },
    [361] = {
        name = "Champion's Pursuit",
        bonuses = {            [2] = { spellId = 41701 },            [4] = { spellId = 23158 },            [6] = { spellId = 41700 },        }
    },
    [362] = {
        name = "Lieutenant Commander's Pursuit",
        bonuses = {            [2] = { spellId = 41803 },            [4] = { spellId = 23158 },            [6] = { spellId = 41802 },        }
    },
    [381] = {
        name = "Lieutenant Commander's Sanctuary",
        bonuses = {            [2] = { spellId = 41813 },            [4] = { spellId = 23218 },            [6] = { spellId = 41812 },        }
    },
    [382] = {
        name = "Champion's Sanctuary",
        bonuses = {            [2] = { spellId = 41711 },            [4] = { spellId = 23218 },            [6] = { spellId = 41710 },        }
    },
    [383] = {
        name = "Warlord's Battlegear",
        bonuses = {            [2] = { spellId = 41887 },            [3] = { spellId = 22738 },            [6] = { spellId = 41888 },        }
    },
    [384] = {
        name = "Field Marshal's Battlegear",
        bonuses = {            [2] = { spellId = 41756 },            [3] = { spellId = 22738 },            [6] = { spellId = 41755 },        }
    },
    [386] = {
        name = "Warlord's Earthshaker",
        bonuses = {            [2] = { spellId = 41896 },            [3] = { spellId = 22804 },            [6] = { spellId = 41895 },        }
    },
    [387] = {
        name = "Warlord's Regalia",
        bonuses = {            [2] = { spellId = 41901 },            [3] = { spellId = 23025 },            [6] = { spellId = 41902 },        }
    },
    [388] = {
        name = "Field Marshal's Regalia",
        bonuses = {            [2] = { spellId = 41761 },            [3] = { spellId = 23025 },            [6] = { spellId = 41762 },        }
    },
    [389] = {
        name = "Field Marshal's Raiment",
        bonuses = {            [2] = { spellId = 41759 },            [3] = { spellId = 23044 },            [6] = { spellId = 41760 },        }
    },
    [390] = {
        name = "Warlord's Raiment",
        bonuses = {            [2] = { spellId = 41899 },            [3] = { spellId = 23044 },            [6] = { spellId = 41900 },        }
    },
    [391] = {
        name = "Warlord's Threads",
        bonuses = {            [2] = { spellId = 41906 },            [3] = { spellId = 23047 },            [6] = { spellId = 41905 },        }
    },
    [392] = {
        name = "Field Marshal's Threads",
        bonuses = {            [2] = { spellId = 41765 },            [3] = { spellId = 23047 },            [6] = { spellId = 41766 },        }
    },
    [393] = {
        name = "Warlord's Vestments",
        bonuses = {            [2] = { spellId = 41908 },            [3] = { spellId = 23048 },            [6] = { spellId = 41907 },        }
    },
    [394] = {
        name = "Field Marshal's Vestments",
        bonuses = {            [2] = { spellId = 41767 },            [3] = { spellId = 23048 },            [6] = { spellId = 41768 },        }
    },
    [395] = {
        name = "Field Marshal's Pursuit",
        bonuses = {            [2] = { spellId = 41757 },            [3] = { spellId = 23158 },            [6] = { spellId = 41758 },        }
    },
    [396] = {
        name = "Warlord's Pursuit",
        bonuses = {            [2] = { spellId = 41898 },            [3] = { spellId = 23158 },            [6] = { spellId = 41897 },        }
    },
    [397] = {
        name = "Field Marshal's Sanctuary",
        bonuses = {            [2] = { spellId = 41764 },            [3] = { spellId = 23218 },            [6] = { spellId = 41763 },        }
    },
    [398] = {
        name = "Warlord's Sanctuary",
        bonuses = {            [2] = { spellId = 41903 },            [3] = { spellId = 23218 },            [6] = { spellId = 41904 },        }
    },
    [401] = {
        name = "Lieutenant Commander's Aegis",
        bonuses = {            [2] = { spellId = { 41636, 41787 } },            [4] = { spellId = 23302 },            [6] = { spellId = 41786 },        }
    },
    [402] = {
        name = "Field Marshal's Aegis",
        bonuses = {            [2] = { spellId = 41754 },            [3] = { spellId = 23302 },            [6] = { spellId = 41753 },        }
    },
    [421] = {
        name = "Bloodvine Garb",
        bonuses = {            [3] = { spellId = 41676 },        }
    },
    [441] = {
        name = "Primal Batskin",
        bonuses = {            [3] = { spellId = 24090 },        }
    },
    [442] = {
        name = "Blood Tiger Harness",
        bonuses = {            [2] = { spellId = { 41670, 41650 } },        }
    },
    [443] = {
        name = "Bloodsoul Embrace",
        bonuses = {            [3] = { spellId = 41675 },        }
    },
    [444] = {
        name = "The Darksoul",
        bonuses = {            [3] = { spellId = 41847 },        }
    },
    [461] = {
        name = "The Twin Blades of Hakkari",
        bonuses = {            [2] = { spellId = 41874 },        }
    },
    [462] = {
        name = "Zanzil's Concentration",
        bonuses = {            [2] = { spellId = { 41894, 39702 } },        }
    },
    [463] = {
        name = "Primal Blessing",
        bonuses = {            [2] = { spellId = 24256 },        }
    },
    [464] = {
        name = "Overlord's Resolution",
        bonuses = {            [2] = { spellId = 39880 },        }
    },
    [465] = {
        name = "Prayer of the Primal",
        bonuses = {            [2] = { spellId = 41830 },        }
    },
    [466] = {
        name = "Major Mojo Infusion",
        bonuses = {            [2] = { spellId = 41823 },        }
    },
    [467] = {
        name = "The Highlander's Resolution",
        bonuses = {            [2] = { spellId = 41868 },            [3] = { spellId = 39548 },        }
    },
    [468] = {
        name = "The Highlander's Resolve",
        bonuses = {            [2] = { spellId = 41640 },            [3] = { spellId = 41041 },        }
    },
    [469] = {
        name = "The Highlander's Determination",
        bonuses = {            [2] = { spellId = 41865 },            [3] = { spellId = 39418 },        }
    },
    [470] = {
        name = "The Highlander's Fortitude",
        bonuses = {            [2] = { spellId = 41638 },            [3] = { spellId = 39447 },        }
    },
    [471] = {
        name = "The Highlander's Purpose",
        bonuses = {            [2] = { spellId = 41867 },            [3] = { spellId = 39433 },        }
    },
    [472] = {
        name = "The Highlander's Will",
        bonuses = {            [2] = { spellId = 41639 },            [3] = { spellId = 39420 },        }
    },
    [473] = {
        name = "The Highlander's Intent",
        bonuses = {            [2] = { spellId = 41866 },            [3] = { spellId = 39422 },        }
    },
    [474] = {
        name = "Vindicator's Battlegear",
        bonuses = {            [2] = { spellId = 41885 },            [3] = { spellId = 24456 },            [5] = { spellId = 24431 },        }
    },
    [475] = {
        name = "Freethinker's Armor",
        bonuses = {            [2] = { spellId = 41770 },            [3] = { spellId = 24457 },            [5] = { spellId = 24460 },        }
    },
    [476] = {
        name = "Augur's Regalia",
        bonuses = {            [2] = { spellId = 41659 },            [3] = { spellId = 24461 },            [5] = { spellId = 24462 },        }
    },
    [477] = {
        name = "Predator's Armor",
        bonuses = {            [2] = { spellId = 41831 },            [3] = { spellId = 24465 },            [5] = { spellId = 24467 },        }
    },
    [478] = {
        name = "Madcap's Outfit",
        bonuses = {            [2] = { spellId = 41821 },            [3] = { spellId = 24469 },            [5] = { spellId = 24471 },        }
    },
    [479] = {
        name = "Haruspex's Garb",
        bonuses = {            [2] = { spellId = 41776 },            [3] = { spellId = 24479 },            [5] = { spellId = 24480 },        }
    },
    [480] = {
        name = "Confessor's Raiment",
        bonuses = {            [2] = { spellId = 41718 },            [3] = { spellId = 24482 },            [5] = { spellId = 24483 },        }
    },
    [481] = {
        name = "Demoniac's Threads",
        bonuses = {            [2] = { spellId = 41734 },            [3] = { spellId = 24486 },            [5] = { spellId = 24487 },        }
    },
    [482] = {
        name = "Illusionist's Attire",
        bonuses = {            [2] = { spellId = 41777 },            [3] = { spellId = 24489 },            [5] = { spellId = 24491 },        }
    },
    [483] = {
        name = "The Defiler's Determination",
        bonuses = {            [2] = { spellId = 41848 },            [3] = { spellId = 39884 },        }
    },
    [484] = {
        name = "The Defiler's Fortitude",
        bonuses = {            [2] = { spellId = 41849 },            [3] = { spellId = 41643 },        }
    },
    [485] = {
        name = "The Defiler's Intent",
        bonuses = {            [2] = { spellId = 41851 },            [3] = { spellId = 41850 },        }
    },
    [486] = {
        name = "The Defiler's Purpose",
        bonuses = {            [2] = { spellId = 41852 },            [3] = { spellId = 39545 },        }
    },
    [487] = {
        name = "The Defiler's Resolution",
        bonuses = {            [2] = { spellId = 41853 },            [3] = { spellId = 39486 },        }
    },
    [488] = {
        name = "The Defiler's Will",
        bonuses = {            [2] = { spellId = 41855 },            [3] = { spellId = 41854 },        }
    },
    [489] = {
        name = "Black Dragon Mail",
        bonuses = {            [2] = { spellId = 39510 },            [3] = { spellId = 39509 },            [4] = { spellId = 41669 },        }
    },
    [490] = {
        name = "Green Dragon Mail",
        bonuses = {            [2] = { spellId = 41775 },            [3] = { spellId = 21894 },        }
    },
    [491] = {
        name = "Blue Dragon Mail",
        bonuses = {            [2] = { spellId = 41677 },            [3] = { spellId = 41651 },        }
    },
    [492] = {
        name = "Twilight Trappings",
        bonuses = {            [3] = { spellId = 24746 },        }
    },
    [493] = {
        name = "Genesis Raiment",
        bonuses = {            [3] = { spellId = { 41774, 41773 } },            [5] = { spellId = 26106 },        }
    },
    [494] = {
        name = "Symbols of Unending Life",
        bonuses = {            [3] = { spellId = 26107 },        }
    },
    [495] = {
        name = "Battlegear of Unyielding Strength",
        bonuses = {            [3] = { spellId = 26111 },        }
    },
    [496] = {
        name = "Conqueror's Battlegear",
        bonuses = {            [3] = { spellId = 26109 },            [5] = { spellId = 26110 },        }
    },
    [497] = {
        name = "Deathdealer's Embrace",
        bonuses = {            [3] = { spellId = 26112 },            [5] = { spellId = 26113 },        }
    },
    [498] = {
        name = "Emblems of Veiled Shadows",
        bonuses = {            [3] = { spellId = 26114 },        }
    },
    [499] = {
        name = "Doomcaller's Attire",
        bonuses = {            [3] = { spellId = 26116 },            [5] = { spellId = 26117 },        }
    },
    [500] = {
        name = "Implements of Unspoken Names",
        bonuses = {            [3] = { spellId = 26118 },        }
    },
    [501] = {
        name = "Stormcaller's Garb",
        bonuses = {            [3] = { spellId = 26119 },            [5] = { spellId = 26122 },        }
    },
    [502] = {
        name = "Gift of the Gathering Storm",
        bonuses = {            [3] = { spellId = 26123 },        }
    },
    [503] = {
        name = "Enigma Vestments",
        bonuses = {            [3] = { spellId = 26127 },            [5] = { spellId = 26128 },        }
    },
    [504] = {
        name = "Trappings of Vaulted Secrets",
        bonuses = {            [3] = { spellId = 26131 },        }
    },
    [505] = {
        name = "Avenger's Battlegear",
        bonuses = {            [3] = { spellId = 26130 },            [5] = { spellId = 41648 },        }
    },
    [506] = {
        name = "Battlegear of Eternal Justice",
        bonuses = {            [3] = { spellId = 26135 },        }
    },
    [507] = {
        name = "Garments of the Oracle",
        bonuses = {            [3] = { spellId = 26169 },            [5] = { spellId = 26171 },        }
    },
    [508] = {
        name = "Finery of Infinite Wisdom",
        bonuses = {            [3] = { spellId = 26172 },        }
    },
    [509] = {
        name = "Striker's Garb",
        bonuses = {            [3] = { spellId = 26173 },            [5] = { spellId = 26174 },        }
    },
    [510] = {
        name = "Trappings of the Unseen Path",
        bonuses = {            [3] = { spellId = 26176 },        }
    },
    [511] = {
        name = "Battlegear of Heroism",
        bonuses = {            [2] = { spellId = 41662 },            [4] = { spellId = 27419 },            [6] = { spellId = 41649 },            [8] = { spellId = 41661 },        }
    },
    [512] = {
        name = "Darkmantle Armor",
        bonuses = {            [2] = { spellId = 41721 },            [4] = { spellId = 27787 },            [6] = { spellId = 41722 },            [8] = { spellId = 41720 },        }
    },
    [513] = {
        name = "Feralheart Raiment",
        bonuses = {            [2] = { spellId = 41751 },            [4] = { spellId = 27781 },            [6] = { spellId = { 41646, 41752 } },            [8] = { spellId = 41750 },        }
    },
    [514] = {
        name = "Vestments of the Virtuous",
        bonuses = {            [2] = { spellId = 41883 },            [4] = { spellId = 27778 },            [6] = { spellId = 41884 },            [8] = { spellId = 41882 },        }
    },
    [515] = {
        name = "Beastmaster Armor",
        bonuses = {            [2] = { spellId = 41666 },            [4] = { spellId = 27785 },            [6] = { spellId = 41667 },            [8] = { spellId = 41665 },        }
    },
    [516] = {
        name = "Soulforge Armor",
        bonuses = {            [2] = { spellId = 41843 },            [4] = { spellId = 27498 },            [6] = { spellId = 41844 },            [8] = { spellId = 41842 },        }
    },
    [517] = {
        name = "Sorcerer's Regalia",
        bonuses = {            [2] = { spellId = 41839 },            [4] = { spellId = 27867 },            [6] = { spellId = 32451 },            [8] = { spellId = 41840 },        }
    },
    [518] = {
        name = "Deathmist Raiment",
        bonuses = {            [2] = { spellId = 41728 },            [4] = { spellId = 27780 },            [6] = { spellId = 41729 },            [8] = { spellId = 41727 },        }
    },
    [519] = {
        name = "The Five Thunders",
        bonuses = {            [2] = { spellId = 41859 },            [4] = { spellId = 27774 },            [6] = { spellId = 41860 },            [8] = { spellId = 41858 },        }
    },
    [520] = {
        name = "Ironweave Battlesuit",
        bonuses = {            [4] = { spellId = 27733 },            [8] = { spellId = 41781 },        }
    },
    [521] = {
        name = "Dreamwalker Raiment",
        bonuses = {            [2] = { spellId = 28716 },            [4] = { spellId = 28743 },            [6] = { spellId = 28744 },            [8] = { spellId = 28719 },        }
    },
    [522] = {
        name = "Champion's Guard",
        bonuses = {            [2] = { spellId = 41695 },            [4] = { spellId = 23048 },            [6] = { spellId = 41694 },        }
    },
    [523] = {
        name = "Dreadnaught's Battlegear",
        bonuses = {            [2] = { spellId = 28844 },            [4] = { spellId = 28843 },            [6] = { spellId = 28842 },            [8] = { spellId = 28845 },        }
    },
    [524] = {
        name = "Bonescythe Armor",
        bonuses = {            [2] = { spellId = 28816 },            [4] = { spellId = 28812 },            [6] = { spellId = 28811 },            [8] = { spellId = 28814 },        }
    },
    [525] = {
        name = "Vestments of Faith",
        bonuses = {            [2] = { spellId = 28807 },            [4] = { spellId = 28809 },            [6] = { spellId = 28808 },            [8] = { spellId = 28802 },        }
    },
    [526] = {
        name = "Frostfire Regalia",
        bonuses = {            [2] = { spellId = 28763 },            [4] = { spellId = 28764 },            [6] = { spellId = 28771 },            [8] = { spellId = 28761 },        }
    },
    [527] = {
        name = "The Earthshatterer",
        bonuses = {            [2] = { spellId = 28818 },            [4] = { spellId = 29171 },            [6] = { spellId = 28823 },            [8] = { spellId = 28821 },        }
    },
    [528] = {
        name = "Redemption Armor",
        bonuses = {            [2] = { spellId = 28775 },            [4] = { spellId = 28774 },            [6] = { spellId = 28789 },            [8] = { spellId = 28787 },        }
    },
    [529] = {
        name = "Plagueheart Raiment",
        bonuses = {            [2] = { spellId = 28831 },            [4] = { spellId = 28829 },            [6] = { spellId = 28746 },            [8] = { spellId = 28830 },        }
    },
    [530] = {
        name = "Cryptstalker Armor",
        bonuses = {            [2] = { spellId = 28755 },            [4] = { spellId = 28756 },            [6] = { spellId = 28752 },            [8] = { spellId = 28751 },        }
    },
    [533] = {
        name = "Battlegear of Undead Slaying",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [534] = {
        name = "Undead Slayer's Armor",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [535] = {
        name = "Garb of the Undead Slayer",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [536] = {
        name = "Regalia of Undead Cleansing",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [537] = {
        name = "Champion's Battlearmor",
        bonuses = {            [2] = { spellId = 41689 },            [4] = { spellId = 22738 },            [6] = { spellId = 41688 },        }
    },
    [538] = {
        name = "Champion's Stormcaller",
        bonuses = {            [2] = { spellId = 41713 },            [4] = { spellId = 22804 },            [6] = { spellId = 41712 },        }
    },
    [539] = {
        name = "Champion's Refuge",
        bonuses = {            [2] = { spellId = 41707 },            [4] = { spellId = 23218 },            [6] = { spellId = 41706 },        }
    },
    [540] = {
        name = "Champion's Investiture",
        bonuses = {            [2] = { spellId = 41697 },            [4] = { spellId = 23044 },            [6] = { spellId = 41696 },        }
    },
    [541] = {
        name = "Champion's Dreadgear",
        bonuses = {            [2] = { spellId = 41654 },            [4] = { spellId = 23047 },            [6] = { spellId = 41691 },        }
    },
    [542] = {
        name = "Champion's Arcanum",
        bonuses = {            [2] = { spellId = 41687 },            [4] = { spellId = 23025 },            [6] = { spellId = 41652 },        }
    },
    [543] = {
        name = "Champion's Pursuance",
        bonuses = {            [2] = { spellId = 41698 },            [4] = { spellId = 23158 },            [6] = { spellId = 41699 },        }
    },
    [544] = {
        name = "Lieutenant Commander's Redoubt",
        bonuses = {            [2] = { spellId = 41807 },            [4] = { spellId = 23302 },            [6] = { spellId = 41806 },        }
    },
    [545] = {
        name = "Lieutenant Commander's Battlearmor",
        bonuses = {            [2] = { spellId = 41790 },            [4] = { spellId = 22738 },            [6] = { spellId = 41791 },        }
    },
    [546] = {
        name = "Lieutenant Commander's Arcanum",
        bonuses = {            [2] = { spellId = 41789 },            [4] = { spellId = 23025 },            [6] = { spellId = 41788 },        }
    },
    [547] = {
        name = "Lieutenant Commander's Dreadgear",
        bonuses = {            [2] = { spellId = 41795 },            [4] = { spellId = 23047 },            [6] = { spellId = 41794 },        }
    },
    [548] = {
        name = "Lieutenant Commander's Guard",
        bonuses = {            [2] = { spellId = 41796 },            [4] = { spellId = 23048 },            [6] = { spellId = 41797 },        }
    },
    [549] = {
        name = "Lieutenant Commander's Investiture",
        bonuses = {            [2] = { spellId = 41799 },            [4] = { spellId = 23044 },            [6] = { spellId = 41798 },        }
    },
    [550] = {
        name = "Lieutenant Commander's Pursuance",
        bonuses = {            [2] = { spellId = 41800 },            [4] = { spellId = 23158 },            [6] = { spellId = 41801 },        }
    },
    [551] = {
        name = "Lieutenant Commander's Refuge",
        bonuses = {            [2] = { spellId = 41808 },            [4] = { spellId = 23218 },            [6] = { spellId = 41809 },        }
    },
    [552] = {
        name = "Wrath of Spellfire",
        bonuses = {            [3] = { spellId = 32196 },        }
    },
    [553] = {
        name = "Shadow's Embrace",
        bonuses = {            [3] = { spellId = 39372 },        }
    },
    [554] = {
        name = "Primal Mooncloth",
        bonuses = {            [3] = { spellId = 32102 },        }
    },
    [555] = {
        name = "Netherweave Vestments",
        bonuses = {            [2] = { spellId = 39543 },            [4] = { spellId = 41829 },        }
    },
    [556] = {
        name = "Imbued Netherweave",
        bonuses = {            [3] = { spellId = 39881 },        }
    },
    [557] = {
        name = "Soulcloth Embrace",
        bonuses = {            [3] = { spellId = 41841 },        }
    },
    [558] = {
        name = "Arcanoweave Vestments",
        bonuses = {            [3] = { spellId = 41658 },        }
    },
    [559] = {
        name = "Spellstrike Infusion",
        bonuses = {            [2] = { spellId = 32106 },        }
    },
    [560] = {
        name = "Fel Iron Plate",
        bonuses = {            [2] = { spellId = 42155 },            [4] = { spellId = 41744 },        }
    },
    [561] = {
        name = "Fel Iron Chain",
        bonuses = {            [2] = { spellId = 41561 },            [4] = { spellId = 41562 },        }
    },
    [562] = {
        name = "Adamantite Battlegear",
        bonuses = {            [3] = { spellId = 41655 },        }
    },
    [563] = {
        name = "Enchanted Adamantite Armor",
        bonuses = {            [3] = { spellId = 41742 },        }
    },
    [564] = {
        name = "Flame Guard",
        bonuses = {            [3] = { spellId = 41769 },        }
    },
    [565] = {
        name = "Khorium Ward",
        bonuses = {            [3] = { spellId = 41783 },        }
    },
    [566] = {
        name = "Burning Rage",
        bonuses = {            [2] = { spellId = 41678 },        }
    },
    [567] = {
        name = "Gladiator's Battlegear",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 22738 },        }
    },
    [568] = {
        name = "Gladiator's Dreadgear",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 23047 },        }
    },
    [569] = {
        name = "Faith in Felsteel",
        bonuses = {            [3] = { spellId = 41743 },        }
    },
    [570] = {
        name = "The Unyielding",
        bonuses = {            [2] = { spellId = 41876 },        }
    },
    [571] = {
        name = "Whitemend Wisdom",
        bonuses = {            [2] = { spellId = 32200 },        }
    },
    [572] = {
        name = "Battlecast Garb",
        bonuses = {            [2] = { spellId = 41660 },        }
    },
    [573] = {
        name = "Fel Skin",
        bonuses = {            [3] = { spellId = 41746 },        }
    },
    [574] = {
        name = "Strength of the Clefthoof",
        bonuses = {            [3] = { spellId = 41846 },        }
    },
    [575] = {
        name = "Felstalker Armor",
        bonuses = {            [3] = { spellId = 41749 },        }
    },
    [576] = {
        name = "Fury of the Nether",
        bonuses = {            [3] = { spellId = 41771 },        }
    },
    [577] = {
        name = "Gladiator's Vestments",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 21975 },        }
    },
    [578] = {
        name = "Gladiator's Earthshaker",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 33018 },        }
    },
    [579] = {
        name = "Gladiator's Regalia",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 44302 },        }
    },
    [580] = {
        name = "Gladiator's Thunderfist",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 44296 },        }
    },
    [581] = {
        name = "Gladiator's Raiment",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 33333 },        }
    },
    [582] = {
        name = "Gladiator's Aegis",
        bonuses = {            [2] = { spellId = 40044 },            [4] = { spellId = 23302 },        }
    },
    [583] = {
        name = "Gladiator's Vindication",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 23302 },        }
    },
    [584] = {
        name = "Gladiator's Sanctuary",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 23218 },        }
    },
    [585] = {
        name = "Gladiator's Wildhide",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 46832 },        }
    },
    [586] = {
        name = "Gladiator's Pursuit",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 44292 },        }
    },
    [587] = {
        name = "High Warlord's Aegis",
        bonuses = {            [2] = { spellId = 40052 },            [4] = { spellId = 23302 },        }
    },
    [588] = {
        name = "High Warlord's Battlegear",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 22738 },        }
    },
    [589] = {
        name = "Grand Marshal's Aegis",
        bonuses = {            [2] = { spellId = 40048 },            [4] = { spellId = 23302 },        }
    },
    [590] = {
        name = "Grand Marshal's Battlegear",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 22738 },        }
    },
    [591] = {
        name = "Grand Marshal's Dreadgear",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 23047 },        }
    },
    [592] = {
        name = "High Warlord's Dreadgear",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 23047 },        }
    },
    [593] = {
        name = "Grand Marshal's Earthshaker",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 33018 },        }
    },
    [594] = {
        name = "High Warlord's Earthshaker",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 33018 },        }
    },
    [595] = {
        name = "Grand Marshal's Pursuit",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23158 },        }
    },
    [596] = {
        name = "High Warlord's Pursuit",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 23158 },        }
    },
    [597] = {
        name = "Grand Marshal's Raiment",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 33333 },        }
    },
    [598] = {
        name = "High Warlord's Raiment",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 33333 },        }
    },
    [599] = {
        name = "Grand Marshal's Regalia",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 23025 },        }
    },
    [600] = {
        name = "High Warlord's Regalia",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 23025 },        }
    },
    [601] = {
        name = "Grand Marshal's Sanctuary",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23218 },        }
    },
    [602] = {
        name = "High Warlord's Sanctuary",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 23218 },        }
    },
    [603] = {
        name = "Grand Marshal's Thunderfist",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 22804 },        }
    },
    [604] = {
        name = "High Warlord's Thunderfist",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 22804 },        }
    },
    [605] = {
        name = "Grand Marshal's Vestments",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23048 },        }
    },
    [606] = {
        name = "High Warlord's Vestments",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 23048 },        }
    },
    [607] = {
        name = "Grand Marshal's Vindication",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23302 },        }
    },
    [608] = {
        name = "High Warlord's Vindication",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 23302 },        }
    },
    [609] = {
        name = "Grand Marshal's Wildhide",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 33877 },        }
    },
    [610] = {
        name = "High Warlord's Wildhide",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 33877 },        }
    },
    [611] = {
        name = "Felscale Armor",
        bonuses = {            [2] = { spellId = 41748 },            [4] = { spellId = 41747 },        }
    },
    [612] = {
        name = "Scaled Draenic Armor",
        bonuses = {            [2] = { spellId = 41833 },            [4] = { spellId = 41834 },        }
    },
    [613] = {
        name = "Thick Draenic Armor",
        bonuses = {            [2] = { spellId = 41878 },            [4] = { spellId = 41877 },        }
    },
    [614] = {
        name = "Wild Draenish Armor",
        bonuses = {            [2] = { spellId = 41890 },            [4] = { spellId = 41889 },        }
    },
    [615] = {
        name = "Gladiator's Felshroud",
        bonuses = {            [2] = { spellId = 40053 },            [4] = { spellId = 23047 },        }
    },
    [616] = {
        name = "Netherscale Armor",
        bonuses = {            [3] = { spellId = 39982 },        }
    },
    [617] = {
        name = "Netherstrike Armor",
        bonuses = {            [3] = { spellId = 41828 },        }
    },
    [618] = {
        name = "Windhawk Armor",
        bonuses = {            [3] = { spellId = 41591 },        }
    },
    [619] = {
        name = "Primal Intent",
        bonuses = {            [3] = { spellId = 41832 },        }
    },
    [620] = {
        name = "Assassination Armor",
        bonuses = {            [2] = { spellId = 37165 },            [4] = { spellId = 37166 },        }
    },
    [621] = {
        name = "Netherblade",
        bonuses = {            [2] = { spellId = 37167 },            [4] = { spellId = 37168 },        }
    },
    [622] = {
        name = "Deathmantle",
        bonuses = {            [2] = { spellId = 37169 },            [4] = { spellId = 37170 },        }
    },
    [623] = {
        name = "Righteous Armor",
        bonuses = {            [2] = { spellId = 37180 },            [4] = { spellId = 37181 },        }
    },
    [624] = {
        name = "Justicar Raiment",
        bonuses = {            [2] = { spellId = 37182 },            [4] = { spellId = 37183 },        }
    },
    [625] = {
        name = "Justicar Armor",
        bonuses = {            [2] = { spellId = 37184 },            [4] = { spellId = 37185 },        }
    },
    [626] = {
        name = "Justicar Battlegear",
        bonuses = {            [2] = { spellId = 37186 },            [4] = { spellId = 37187 },        }
    },
    [627] = {
        name = "Crystalforge Raiment",
        bonuses = {            [2] = { spellId = 37188 },            [4] = { spellId = 37189 },        }
    },
    [628] = {
        name = "Crystalforge Armor",
        bonuses = {            [2] = { spellId = 37190 },            [4] = { spellId = 37191 },        }
    },
    [629] = {
        name = "Crystalforge Battlegear",
        bonuses = {            [2] = { spellId = 37194 },            [4] = { spellId = 37195 },        }
    },
    [630] = {
        name = "Tidefury Raiment",
        bonuses = {            [2] = { spellId = 37207 },            [4] = { spellId = 37209 },        }
    },
    [631] = {
        name = "Cyclone Raiment",
        bonuses = {            [2] = { spellId = 37210 },            [4] = { spellId = 37211 },        }
    },
    [632] = {
        name = "Cyclone Regalia",
        bonuses = {            [2] = { spellId = 37212 },            [4] = { spellId = 37213 },        }
    },
    [633] = {
        name = "Cyclone Harness",
        bonuses = {            [2] = { spellId = 37223 },            [4] = { spellId = 37224 },        }
    },
    [634] = {
        name = "Cataclysm Raiment",
        bonuses = {            [2] = { spellId = 37225 },            [4] = { spellId = 37227 },        }
    },
    [635] = {
        name = "Cataclysm Regalia",
        bonuses = {            [2] = { spellId = 37228 },            [4] = { spellId = 37237 },        }
    },
    [636] = {
        name = "Cataclysm Harness",
        bonuses = {            [2] = { spellId = 37239 },            [4] = { spellId = 37241 },        }
    },
    [637] = {
        name = "Moonglade Raiment",
        bonuses = {            [2] = { spellId = 37286 },            [4] = { spellId = 37287 },        }
    },
    [638] = {
        name = "Malorne Raiment",
        bonuses = {            [2] = { spellId = 37288 },            [4] = { spellId = 37292 },        }
    },
    [639] = {
        name = "Malorne Regalia",
        bonuses = {            [2] = { spellId = 37295 },            [4] = { spellId = 37297 },        }
    },
    [640] = {
        name = "Malorne Harness",
        bonuses = {            [2] = { spellId = { 37311, 37306 } },            [4] = { spellId = { 37298, 37299 } },        }
    },
    [641] = {
        name = "Nordrassil Harness",
        bonuses = {            [2] = { spellId = 37315 },            [4] = { spellId = 37333 },        }
    },
    [642] = {
        name = "Nordrassil Raiment",
        bonuses = {            [2] = { spellId = 37313 },            [4] = { spellId = 37314 },        }
    },
    [643] = {
        name = "Nordrassil Regalia",
        bonuses = {            [2] = { spellId = 37324 },            [4] = { spellId = 37327 },        }
    },
    [644] = {
        name = "Oblivion Raiment",
        bonuses = {            [2] = { spellId = 37375 },            [4] = { spellId = 37376 },        }
    },
    [645] = {
        name = "Voidheart Raiment",
        bonuses = {            [2] = { spellId = { 37377, 39437 } },            [4] = { spellId = 37380 },        }
    },
    [646] = {
        name = "Corruptor Raiment",
        bonuses = {            [2] = { spellId = 37381 },            [4] = { spellId = 37384 },        }
    },
    [647] = {
        name = "Incanter's Regalia",
        bonuses = {            [2] = { spellId = 37423 },            [4] = { spellId = 37424 },        }
    },
    [648] = {
        name = "Aldor Regalia",
        bonuses = {            [2] = { spellId = 37438 },            [4] = { spellId = 37439 },        }
    },
    [649] = {
        name = "Tirisfal Regalia",
        bonuses = {            [2] = { spellId = 37441 },            [4] = { spellId = 37443 },        }
    },
    [650] = {
        name = "Beast Lord Armor",
        bonuses = {            [2] = { spellId = 37481 },            [4] = { spellId = 37483 },        }
    },
    [651] = {
        name = "Demon Stalker Armor",
        bonuses = {            [2] = { spellId = 37484 },            [4] = { spellId = 37485 },        }
    },
    [652] = {
        name = "Rift Stalker Armor",
        bonuses = {            [2] = { spellId = 37381 },            [4] = { spellId = 37505 },        }
    },
    [653] = {
        name = "Bold Armor",
        bonuses = {            [2] = { spellId = 37512 },            [4] = { spellId = 37513 },        }
    },
    [654] = {
        name = "Warbringer Armor",
        bonuses = {            [2] = { spellId = 37514 },            [4] = { spellId = 37516 },        }
    },
    [655] = {
        name = "Warbringer Battlegear",
        bonuses = {            [2] = { spellId = 37518 },            [4] = { spellId = 37519 },        }
    },
    [656] = {
        name = "Destroyer Armor",
        bonuses = {            [2] = { spellId = 37522 },            [4] = { spellId = 37525 },        }
    },
    [657] = {
        name = "Destroyer Battlegear",
        bonuses = {            [2] = { spellId = 37528 },            [4] = { spellId = 37535 },        }
    },
    [658] = {
        name = "Mana-Etched Regalia",
        bonuses = {            [2] = { spellId = 37607 },            [4] = { spellId = 37619 },        }
    },
    [659] = {
        name = "Wastewalker Armor",
        bonuses = {            [2] = { spellId = 37608 },            [4] = { spellId = 37618 },        }
    },
    [660] = {
        name = "Desolation Battlegear",
        bonuses = {            [2] = { spellId = 37609 },            [4] = { spellId = 37617 },        }
    },
    [661] = {
        name = "Doomplate Battlegear",
        bonuses = {            [2] = { spellId = 37610 },            [4] = { spellId = 37611 },        }
    },
    [662] = {
        name = "Hallowed Raiment",
        bonuses = {            [2] = { spellId = 37556 },            [4] = { spellId = 37558 },        }
    },
    [663] = {
        name = "Incarnate Raiment",
        bonuses = {            [2] = { spellId = 37564 },            [4] = { spellId = 37568 },        }
    },
    [664] = {
        name = "Incarnate Regalia",
        bonuses = {            [2] = { spellId = 37570 },            [4] = { spellId = 37571 },        }
    },
    [665] = {
        name = "Avatar Raiment",
        bonuses = {            [2] = { spellId = 37594 },            [4] = { spellId = 26171 },        }
    },
    [666] = {
        name = "Avatar Regalia",
        bonuses = {            [2] = { spellId = 37600 },            [4] = { spellId = 37603 },        }
    },
    [667] = {
        name = "The Twin Stars",
        bonuses = {            [2] = { spellId = 41875 },        }
    },
    [668] = {
        name = "Slayer's Armor",
        bonuses = {            [2] = { spellId = 38388 },            [4] = { spellId = 38389 },        }
    },
    [669] = {
        name = "Gronnstalker's Armor",
        bonuses = {            [2] = { spellId = 38390 },            [4] = { spellId = 38392 },        }
    },
    [670] = {
        name = "Malefic Raiment",
        bonuses = {            [2] = { spellId = 38394 },            [4] = { spellId = 38393 },        }
    },
    [671] = {
        name = "Tempest Regalia",
        bonuses = {            [2] = { spellId = 38396 },            [4] = { spellId = 38397 },        }
    },
    [672] = {
        name = "Onslaught Battlegear",
        bonuses = {            [2] = { spellId = 38398 },            [4] = { spellId = 38399 },        }
    },
    [673] = {
        name = "Onslaught Armor",
        bonuses = {            [2] = { spellId = 38408 },            [4] = { spellId = 38407 },        }
    },
    [674] = {
        name = "Absolution Regalia",
        bonuses = {            [2] = { spellId = 38413 },            [4] = { spellId = 38412 },        }
    },
    [675] = {
        name = "Vestments of Absolution",
        bonuses = {            [2] = { spellId = 38410 },            [4] = { spellId = 38411 },        }
    },
    [676] = {
        name = "Thunderheart Harness",
        bonuses = {            [2] = { spellId = 38447 },            [4] = { spellId = 38416 },        }
    },
    [677] = {
        name = "Thunderheart Regalia",
        bonuses = {            [2] = { spellId = 38414 },            [4] = { spellId = 38415 },        }
    },
    [678] = {
        name = "Thunderheart Raiment",
        bonuses = {            [2] = { spellId = 38417 },            [4] = { spellId = 38420 },        }
    },
    [679] = {
        name = "Lightbringer Armor",
        bonuses = {            [2] = { spellId = 38421 },            [4] = { spellId = 38422 },        }
    },
    [680] = {
        name = "Lightbringer Battlegear",
        bonuses = {            [2] = { spellId = 38427 },            [4] = { spellId = 38424 },        }
    },
    [681] = {
        name = "Lightbringer Raiment",
        bonuses = {            [2] = { spellId = 38426 },            [4] = { spellId = 38425 },        }
    },
    [682] = {
        name = "Skyshatter Harness",
        bonuses = {            [2] = { spellId = 38429 },            [4] = { spellId = 38432 },        }
    },
    [683] = {
        name = "Skyshatter Raiment",
        bonuses = {            [2] = { spellId = 38434 },            [4] = { spellId = 38435 },        }
    },
    [684] = {
        name = "Skyshatter Regalia",
        bonuses = {            [2] = { spellId = 38443 },            [4] = { spellId = 38436 },        }
    },
    [685] = {
        name = "Gladiator's Refuge",
        bonuses = {            [2] = { spellId = 40043 },            [4] = { spellId = 46834 },        }
    },
    [686] = {
        name = "Gladiator's Wartide",
        bonuses = {            [2] = { spellId = 40043 },            [4] = { spellId = 44299 },        }
    },
    [687] = {
        name = "Gladiator's Investiture",
        bonuses = {            [2] = { spellId = 40043 },            [4] = { spellId = 33333 },        }
    },
    [688] = {
        name = "Grand Marshal's Refuge",
        bonuses = {            [2] = { spellId = 40045 },            [4] = { spellId = 46834 },        }
    },
    [689] = {
        name = "High Warlord's Refuge",
        bonuses = {            [2] = { spellId = 40049 },            [4] = { spellId = 46834 },        }
    },
    [690] = {
        name = "Gladiator's Redemption",
        bonuses = {            [2] = { spellId = 40043 },            [4] = { spellId = 46851 },        }
    },
    [691] = {
        name = "Grand Marshal's Investiture",
        bonuses = {            [2] = { spellId = 40045 },            [4] = { spellId = 33333 },        }
    },
    [692] = {
        name = "High Warlord's Investiture",
        bonuses = {            [2] = { spellId = 40049 },            [4] = { spellId = 33333 },        }
    },
    [693] = {
        name = "Grand Marshal's Redemption",
        bonuses = {            [2] = { spellId = 40045 },            [4] = { spellId = 46851 },        }
    },
    [694] = {
        name = "High Warlord's Redemption",
        bonuses = {            [2] = { spellId = 40049 },            [4] = { spellId = 46851 },        }
    },
    [695] = {
        name = "Grand Marshal's Wartide",
        bonuses = {            [2] = { spellId = 40045 },            [4] = { spellId = 38499 },        }
    },
    [696] = {
        name = "High Warlord's Wartide",
        bonuses = {            [2] = { spellId = 40049 },            [4] = { spellId = 38499 },        }
    },
    [697] = {
        name = "Champion's Redoubt",
        bonuses = {            [2] = { spellId = 41705 },            [3] = { spellId = 23302 },            [6] = { spellId = 41704 },        }
    },
    [698] = {
        name = "Warlord's Aegis",
        bonuses = {            [2] = { spellId = 41886 },            [3] = { spellId = 23302 },            [6] = { spellId = 30778 },        }
    },
    [699] = {
        name = "The Twin Blades of Azzinoth",
        bonuses = {            [2] = { spellId = { 41433, 41434 } },        }
    },
    [700] = {
        name = "Merciless Gladiator's Aegis",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 23302 },        }
    },
    [701] = {
        name = "Merciless Gladiator's Battlegear",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 22738 },        }
    },
    [702] = {
        name = "Merciless Gladiator's Dreadgear",
        bonuses = {            [2] = { spellId = 41474 },            [4] = { spellId = 23047 },        }
    },
    [703] = {
        name = "Merciless Gladiator's Earthshaker",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 33018 },        }
    },
    [704] = {
        name = "Merciless Gladiator's Felshroud",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 23047 },        }
    },
    [705] = {
        name = "Merciless Gladiator's Investiture",
        bonuses = {            [2] = { spellId = 41463 },            [4] = { spellId = 33333 },        }
    },
    [706] = {
        name = "Merciless Gladiator's Pursuit",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 44292 },        }
    },
    [707] = {
        name = "Merciless Gladiator's Raiment",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 33333 },        }
    },
    [708] = {
        name = "Merciless Gladiator's Redemption",
        bonuses = {            [2] = { spellId = 41463 },            [4] = { spellId = 46851 },        }
    },
    [709] = {
        name = "Merciless Gladiator's Refuge",
        bonuses = {            [2] = { spellId = 41463 },            [4] = { spellId = 23218 },        }
    },
    [710] = {
        name = "Merciless Gladiator's Regalia",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 44302 },        }
    },
    [711] = {
        name = "Merciless Gladiator's Sanctuary",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 23218 },        }
    },
    [712] = {
        name = "Merciless Gladiator's Thunderfist",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 44296 },        }
    },
    [713] = {
        name = "Merciless Gladiator's Vestments",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 21975 },        }
    },
    [714] = {
        name = "Merciless Gladiator's Vindication",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 23302 },        }
    },
    [715] = {
        name = "Merciless Gladiator's Wartide",
        bonuses = {            [2] = { spellId = 41463 },            [4] = { spellId = 44299 },        }
    },
    [716] = {
        name = "Merciless Gladiator's Wildhide",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 44293 },        }
    },
    [717] = {
        name = "Field Marshal's Earthshaker",
        bonuses = {            [2] = { spellId = 41896 },            [3] = { spellId = 22804 },            [6] = { spellId = 41895 },        }
    },
    [718] = {
        name = "Lieutenant Commander's Earthshaker",
        bonuses = {            [2] = { spellId = 41713 },            [4] = { spellId = 22804 },            [6] = { spellId = 41712 },        }
    },
    [719] = {
        name = "The Fists of Fury",
        bonuses = {            [2] = { spellId = 41989 },        }
    },
    [720] = {
        name = "Vengeful Gladiator's Refuge",
        bonuses = {            [2] = { spellId = 43478 },            [4] = { spellId = 23218 },        }
    },
    [721] = {
        name = "Vengeful Gladiator's Sanctuary",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 23218 },        }
    },
    [722] = {
        name = "Vengeful Gladiator's Wildhide",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 44293 },        }
    },
    [723] = {
        name = "Vengeful Gladiator's Pursuit",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 44292 },        }
    },
    [724] = {
        name = "Vengeful Gladiator's Regalia",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 44302 },        }
    },
    [725] = {
        name = "Vengeful Gladiator's Redemption",
        bonuses = {            [2] = { spellId = 43478 },            [4] = { spellId = 23302 },        }
    },
    [726] = {
        name = "Vengeful Gladiator's Vindication",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 23302 },        }
    },
    [727] = {
        name = "Vengeful Gladiator's Aegis",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 23302 },        }
    },
    [728] = {
        name = "Vengeful Gladiator's Investiture",
        bonuses = {            [2] = { spellId = 43478 },            [4] = { spellId = 33333 },        }
    },
    [729] = {
        name = "Vengeful Gladiator's Raiment",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 33333 },        }
    },
    [730] = {
        name = "Vengeful Gladiator's Vestments",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 21975 },        }
    },
    [731] = {
        name = "Vengeful Gladiator's Wartide",
        bonuses = {            [2] = { spellId = 43478 },            [4] = { spellId = 44299 },        }
    },
    [732] = {
        name = "Vengeful Gladiator's Earthshaker",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 33018 },        }
    },
    [733] = {
        name = "Vengeful Gladiator's Thunderfist",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 44296 },        }
    },
    [734] = {
        name = "Vengeful Gladiator's Dreadgear",
        bonuses = {            [2] = { spellId = 43481 },            [4] = { spellId = 23047 },        }
    },
    [735] = {
        name = "Vengeful Gladiator's Felshroud",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 23047 },        }
    },
    [736] = {
        name = "Vengeful Gladiator's Battlegear",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 22738 },        }
    },
    [737] = {
        name = "Latro's Flurry",
        bonuses = {            [2] = { spellId = 9336 },        }
    },
    [738] = {
        name = "Dreadweave Battlegear",
        bonuses = {            [2] = { spellId = 46412 },            [4] = { spellId = 23047 },        }
    },
    [739] = {
        name = "Mooncloth Battlegear",
        bonuses = {            [2] = { spellId = 46413 },            [4] = { spellId = 33333 },        }
    },
    [740] = {
        name = "Satin Battlegear",
        bonuses = {            [2] = { spellId = 46414 },            [4] = { spellId = 33333 },        }
    },
    [741] = {
        name = "Evoker's Silk Battlegear",
        bonuses = {            [2] = { spellId = 46415 },            [4] = { spellId = 23025 },        }
    },
    [742] = {
        name = "Dragonhide Battlegear",
        bonuses = {            [2] = { spellId = 46435 },            [4] = { spellId = 23218 },        }
    },
    [743] = {
        name = "Wyrmhide Battlegear",
        bonuses = {            [2] = { spellId = 46436 },            [4] = { spellId = 46832 },        }
    },
    [744] = {
        name = "Kodohide Battlegear",
        bonuses = {            [2] = { spellId = 46437 },            [4] = { spellId = 46834 },        }
    },
    [745] = {
        name = "Opportunist's Battlegear",
        bonuses = {            [2] = { spellId = 46438 },            [4] = { spellId = 23048 },        }
    },
    [746] = {
        name = "Seer's Mail Battlegear",
        bonuses = {            [2] = { spellId = 46454 },            [4] = { spellId = 22804 },        }
    },
    [747] = {
        name = "Seer's Ringmail Battlegear",
        bonuses = {            [2] = { spellId = 46455 },            [4] = { spellId = 38466 },        }
    },
    [748] = {
        name = "Seer's Linked Battlegear",
        bonuses = {            [2] = { spellId = 46456 },            [4] = { spellId = 33018 },        }
    },
    [749] = {
        name = "Stalker's Chain Battlegear",
        bonuses = {            [2] = { spellId = 46456 },            [4] = { spellId = 23158 },        }
    },
    [750] = {
        name = "Savage Plate Battlegear",
        bonuses = {            [2] = { spellId = 46528 },            [4] = { spellId = 22738 },        }
    },
    [751] = {
        name = "Crusader's Ornamented Battlegear",
        bonuses = {            [2] = { spellId = 46530 },            [4] = { spellId = 23302 },        }
    },
    [752] = {
        name = "Crusader's Scaled Battlegear",
        bonuses = {            [2] = { spellId = 46534 },            [4] = { spellId = 23302 },        }
    },
    [2013] = {
        name = "Oathbound's Opportunistic Vestments",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23048 },        }
    },
    [2014] = {
        name = "Oathbound's Savage Plate Battlegear",
        bonuses = {            [2] = { spellId = 46528 },            [4] = { spellId = 22738 },        }
    },
    [2015] = {
        name = "Oathbound's Ornamented Battlegear",
        bonuses = {            [2] = { spellId = 46530 },            [4] = { spellId = 46851 },        }
    },
    [2016] = {
        name = "Oathbound's Scaled Battlegear",
        bonuses = {            [2] = { spellId = 46534 },            [4] = { spellId = 23302 },        }
    },
    [2017] = {
        name = "Oathbound's Ringmail Battlegear",
        bonuses = {            [2] = { spellId = 46455 },            [4] = { spellId = 38466 },        }
    },
    [2018] = {
        name = "Oathbound's Mail Battlegear",
        bonuses = {            [2] = { spellId = 46454 },            [4] = { spellId = 22804 },        }
    },
    [2019] = {
        name = "Oathbound's Linked Battlegear",
        bonuses = {            [2] = { spellId = 46456 },            [4] = { spellId = 33018 },        }
    },
    [2020] = {
        name = "Oathbound's Chain Battlegear",
        bonuses = {            [2] = { spellId = 46456 },            [4] = { spellId = 23158 },        }
    },
    [2021] = {
        name = "Oathbound's Silk Battlegear",
        bonuses = {            [2] = { spellId = 46415 },            [4] = { spellId = 23025 },        }
    },
    [2022] = {
        name = "Oathbound's Dreadweave Battlegear",
        bonuses = {            [2] = { spellId = 46412 },            [4] = { spellId = 23047 },        }
    },
    [2023] = {
        name = "Oathbound's Mooncloth Battlegear",
        bonuses = {            [2] = { spellId = 46413 },            [4] = { spellId = 33333 },        }
    },
    [2024] = {
        name = "Oathbound's Satin Battlegear",
        bonuses = {            [2] = { spellId = 46414 },            [4] = { spellId = 33333 },        }
    },
    [2025] = {
        name = "Oathbound's Dragonhide Battlegear",
        bonuses = {            [2] = { spellId = 46435 },            [4] = { spellId = 23218 },        }
    },
    [2026] = {
        name = "Oathbound's Wyrmhide Battlegear",
        bonuses = {            [2] = { spellId = 46436 },            [4] = { spellId = 46832 },        }
    },
    [2027] = {
        name = "Oathbound's Kodohide Battlegear",
        bonuses = {            [2] = { spellId = 46437 },            [4] = { spellId = 46834 },        }
    },
}