-- Generated by NextActionGuide Data Generator
-- Product: Classic Era
-- Build: 1.15.8.64907
-- Generated: 2025-12-12 20:34:11

local _, ns = ...
ns.data = ns.data or {}
ns.data.vanilla = ns.data.vanilla or {}

ns.data.vanilla.TierSets = {
    [1] = {
        name = "The Gladiator",
        bonuses = {            [2] = { spellId = 9761 },            [3] = { spellId = 7514 },            [4] = { spellId = 9140 },            [5] = { spellId = 7597 },        }
    },
    [41] = {
        name = "Dal'Rend's Arms",
        bonuses = {            [2] = { spellId = 14056 },        }
    },
    [65] = {
        name = "Spider's Kiss",
        bonuses = {            [2] = { spellId = 17332 },        }
    },
    [81] = {
        name = "The Postmaster",
        bonuses = {            [2] = { spellId = 9764 },            [3] = { spellId = { 14712, 14590 } },            [4] = { spellId = 9417 },            [5] = { spellId = { 9106, 17498 } },        }
    },
    [121] = {
        name = "Cadaverous Garb",
        bonuses = {            [2] = { spellId = 7516 },            [3] = { spellId = 9140 },            [4] = { spellId = 18686 },            [5] = { spellId = 15465 },        }
    },
    [122] = {
        name = "Necropile Raiment",
        bonuses = {            [2] = { spellId = 7516 },            [3] = { spellId = 7495 },            [4] = { spellId = 18686 },            [5] = { spellId = 14047 },        }
    },
    [123] = {
        name = "Bloodmail Regalia",
        bonuses = {            [2] = { spellId = 7516 },            [3] = { spellId = 9140 },            [4] = { spellId = 18686 },            [5] = { spellId = 13665 },        }
    },
    [124] = {
        name = "Deathbone Guardian",
        bonuses = {            [2] = { spellId = 7516 },            [3] = { spellId = 9764 },            [4] = { spellId = 18686 },            [5] = { spellId = 13665 },        }
    },
    [141] = {
        name = "Volcanic Armor",
        bonuses = {            [3] = { spellId = 9233 },        }
    },
    [142] = {
        name = "Stormshroud Armor",
        bonuses = {            [2] = { spellId = 18979 },            [3] = { spellId = 23863 },            [4] = { spellId = 9142 },        }
    },
    [143] = {
        name = "Devilsaur Armor",
        bonuses = {            [2] = { spellId = 15465 },        }
    },
    [144] = {
        name = "Ironfeather Armor",
        bonuses = {            [2] = { spellId = 14799 },        }
    },
    [161] = {
        name = "Defias Leather",
        bonuses = {            [2] = { spellId = 9760 },            [3] = { spellId = 14707 },            [4] = { spellId = 7534 },            [5] = { spellId = 9140 },        }
    },
    [162] = {
        name = "Embrace of the Viper",
        bonuses = {            [2] = { spellId = 7694 },            [3] = { spellId = 20607 },            [4] = { spellId = 7679 },            [5] = { spellId = 9106 },        }
    },
    [163] = {
        name = "Chain of the Scarlet Crusade",
        bonuses = {            [2] = { spellId = 9760 },            [3] = { spellId = 7513 },            [4] = { spellId = 14668 },            [5] = { spellId = 20606 },            [6] = { spellId = 15464 },        }
    },
    [181] = {
        name = "Magister's Regalia",
        bonuses = {            [2] = { spellId = 29091 },            [4] = { spellId = 30777 },            [6] = { spellId = 27867 },            [8] = { spellId = 18679 },        }
    },
    [182] = {
        name = "Vestments of the Devout",
        bonuses = {            [2] = { spellId = 14803 },            [4] = { spellId = 30779 },            [6] = { spellId = 27778 },            [8] = { spellId = 18679 },        }
    },
    [183] = {
        name = "Dreadmist Raiment",
        bonuses = {            [2] = { spellId = 29090 },            [4] = { spellId = 30778 },            [6] = { spellId = 27780 },            [8] = { spellId = 18679 },        }
    },
    [184] = {
        name = "Shadowcraft Armor",
        bonuses = {            [2] = { spellId = 29096 },            [4] = { spellId = 30771 },            [6] = { spellId = 27787 },            [8] = { spellId = 18679 },        }
    },
    [185] = {
        name = "Wildheart Raiment",
        bonuses = {            [2] = { spellId = 29097 },            [4] = { spellId = { 9334, 9344 } },            [6] = { spellId = 27781 },            [8] = { spellId = 18679 },        }
    },
    [186] = {
        name = "Beaststalker Armor",
        bonuses = {            [2] = { spellId = 29094 },            [4] = { spellId = 30772 },            [6] = { spellId = 27785 },            [8] = { spellId = 18679 },        }
    },
    [187] = {
        name = "The Elements",
        bonuses = {            [2] = { spellId = 29095 },            [4] = { spellId = 30780 },            [6] = { spellId = 27774 },            [8] = { spellId = 18679 },        }
    },
    [188] = {
        name = "Lightforge Armor",
        bonuses = {            [2] = { spellId = 29093 },            [4] = { spellId = 30775 },            [6] = { spellId = 27498 },            [8] = { spellId = 18679 },        }
    },
    [189] = {
        name = "Battlegear of Valor",
        bonuses = {            [2] = { spellId = 29092 },            [4] = { spellId = 30770 },            [6] = { spellId = 27419 },            [8] = { spellId = 18679 },        }
    },
    [201] = {
        name = "Arcanist Regalia",
        bonuses = {            [3] = { spellId = 9346 },            [5] = { spellId = 26175 },            [8] = { spellId = 23545 },        }
    },
    [202] = {
        name = "Vestments of Prophecy",
        bonuses = {            [3] = { spellId = 21973 },            [5] = { spellId = 21092 },            [8] = { spellId = 23550 },        }
    },
    [203] = {
        name = "Felheart Raiment",
        bonuses = {            [3] = { spellId = 23554 },            [5] = { spellId = 21741 },            [8] = { spellId = 23553 },        }
    },
    [204] = {
        name = "Nightslayer Armor",
        bonuses = {            [3] = { spellId = 21874 },            [5] = { spellId = 21975 },            [8] = { spellId = 23582 },        }
    },
    [205] = {
        name = "Cenarion Raiment",
        bonuses = {            [3] = { spellId = 23557 },            [5] = { spellId = 18382 },            [8] = { spellId = 23556 },        }
    },
    [206] = {
        name = "Giantstalker Armor",
        bonuses = {            [3] = { spellId = 23560 },            [5] = { spellId = 21926 },            [8] = { spellId = 23566 },        }
    },
    [207] = {
        name = "The Earthfury",
        bonuses = {            [3] = { spellId = 21895 },            [5] = { spellId = 23572 },            [8] = { spellId = 23573 },        }
    },
    [208] = {
        name = "Lawbringer Armor",
        bonuses = {            [3] = { spellId = 23564 },            [5] = { spellId = { 7597, 18384 } },            [8] = { spellId = 21747 },        }
    },
    [209] = {
        name = "Battlegear of Might",
        bonuses = {            [3] = { spellId = 23562 },            [5] = { spellId = 21838 },            [8] = { spellId = 23561 },        }
    },
    [210] = {
        name = "Netherwind Regalia",
        bonuses = {            [3] = { spellId = 21879 },            [5] = { spellId = 23549 },            [8] = { spellId = 22007 },        }
    },
    [211] = {
        name = "Vestments of Transcendence",
        bonuses = {            [3] = { spellId = 21894 },            [5] = { spellId = 21853 },            [8] = { spellId = 22010 },        }
    },
    [212] = {
        name = "Nemesis Raiment",
        bonuses = {            [3] = { spellId = 14047 },            [5] = { spellId = 21922 },            [8] = { spellId = 23555 },        }
    },
    [213] = {
        name = "Bloodfang Armor",
        bonuses = {            [3] = { spellId = 21881 },            [5] = { spellId = 23558 },            [8] = { spellId = 23581 },        }
    },
    [214] = {
        name = "Stormrage Raiment",
        bonuses = {            [3] = { spellId = 21894 },            [5] = { spellId = 21872 },            [8] = { spellId = 21871 },        }
    },
    [215] = {
        name = "Dragonstalker Armor",
        bonuses = {            [3] = { spellId = 23559 },            [5] = { spellId = 21928 },            [8] = { spellId = 23578 },        }
    },
    [216] = {
        name = "The Ten Storms",
        bonuses = {            [3] = { spellId = 21899 },            [5] = { spellId = 23570 },            [8] = { spellId = 23551 },        }
    },
    [217] = {
        name = "Judgement Armor",
        bonuses = {            [3] = { spellId = 23565 },            [5] = { spellId = 24196 },            [8] = { spellId = 23591 },        }
    },
    [218] = {
        name = "Battlegear of Wrath",
        bonuses = {            [3] = { spellId = 23563 },            [5] = { spellId = 21890 },            [8] = { spellId = 23548 },        }
    },
    [221] = {
        name = "Garb of Thero-shan",
        bonuses = {            [6] = { spellId = 7597 },        }
    },
    [241] = {
        name = "Shard of the Gods",
        bonuses = {            [2] = { spellId = 18681 },        }
    },
    [261] = {
        name = "Spirit of Eskhandar",
        bonuses = {            [4] = { spellId = 22648 },        }
    },
    [281] = {
        name = "Champion's Battlegear",
        bonuses = {            [2] = { spellId = 13665 },            [4] = { spellId = 22738 },            [6] = { spellId = 14462 },        }
    },
    [282] = {
        name = "Lieutenant Commander's Battlegear",
        bonuses = {            [2] = { spellId = 13665 },            [4] = { spellId = 22738 },            [6] = { spellId = 14462 },        }
    },
    [301] = {
        name = "Champion's Earthshaker",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 22804 },            [6] = { spellId = 14462 },        }
    },
    [321] = {
        name = "Imperial Plate",
        bonuses = {            [2] = { spellId = 15666 },            [4] = { spellId = 9335 },            [6] = { spellId = 14465 },        }
    },
    [341] = {
        name = "Champion's Regalia",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23025 },            [6] = { spellId = 14462 },        }
    },
    [342] = {
        name = "Champion's Raiment",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23044 },            [6] = { spellId = 14462 },        }
    },
    [343] = {
        name = "Lieutenant Commander's Regalia",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23025 },            [6] = { spellId = 14462 },        }
    },
    [344] = {
        name = "Lieutenant Commander's Raiment",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23044 },            [6] = { spellId = 14462 },        }
    },
    [345] = {
        name = "Champion's Threads",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23047 },            [6] = { spellId = 14462 },        }
    },
    [346] = {
        name = "Lieutenant Commander's Threads",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23047 },            [6] = { spellId = 14462 },        }
    },
    [347] = {
        name = "Champion's Vestments",
        bonuses = {            [2] = { spellId = 13665 },            [4] = { spellId = 23048 },            [6] = { spellId = 14462 },        }
    },
    [348] = {
        name = "Lieutenant Commander's Vestments",
        bonuses = {            [2] = { spellId = 13665 },            [4] = { spellId = 23048 },            [6] = { spellId = 14462 },        }
    },
    [361] = {
        name = "Champion's Pursuit",
        bonuses = {            [2] = { spellId = 13665 },            [4] = { spellId = 23158 },            [6] = { spellId = 14462 },        }
    },
    [362] = {
        name = "Lieutenant Commander's Pursuit",
        bonuses = {            [2] = { spellId = 13665 },            [4] = { spellId = 23158 },            [6] = { spellId = 14462 },        }
    },
    [381] = {
        name = "Lieutenant Commander's Sanctuary",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23218 },            [6] = { spellId = 14462 },        }
    },
    [382] = {
        name = "Champion's Sanctuary",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23218 },            [6] = { spellId = 14462 },        }
    },
    [383] = {
        name = "Warlord's Battlegear",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 22738 },            [6] = { spellId = 14049 },        }
    },
    [384] = {
        name = "Field Marshal's Battlegear",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 22738 },            [6] = { spellId = 14049 },        }
    },
    [386] = {
        name = "Warlord's Earthshaker",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 22804 },            [6] = { spellId = 14049 },        }
    },
    [387] = {
        name = "Warlord's Regalia",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23025 },            [6] = { spellId = 14047 },        }
    },
    [388] = {
        name = "Field Marshal's Regalia",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23025 },            [6] = { spellId = 14047 },        }
    },
    [389] = {
        name = "Field Marshal's Raiment",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23044 },            [6] = { spellId = 14047 },        }
    },
    [390] = {
        name = "Warlord's Raiment",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23044 },            [6] = { spellId = 14047 },        }
    },
    [391] = {
        name = "Warlord's Threads",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23047 },            [6] = { spellId = 14047 },        }
    },
    [392] = {
        name = "Field Marshal's Threads",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23047 },            [6] = { spellId = 14047 },        }
    },
    [393] = {
        name = "Warlord's Vestments",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23048 },            [6] = { spellId = 14049 },        }
    },
    [394] = {
        name = "Field Marshal's Vestments",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23048 },            [6] = { spellId = 14049 },        }
    },
    [395] = {
        name = "Field Marshal's Pursuit",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23158 },            [6] = { spellId = 14384 },        }
    },
    [396] = {
        name = "Warlord's Pursuit",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23158 },            [6] = { spellId = 14384 },        }
    },
    [397] = {
        name = "Field Marshal's Sanctuary",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23218 },            [6] = { spellId = 14049 },        }
    },
    [398] = {
        name = "Warlord's Sanctuary",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23218 },            [6] = { spellId = 14049 },        }
    },
    [401] = {
        name = "Lieutenant Commander's Aegis",
        bonuses = {            [2] = { spellId = { 7496, 28118 } },            [4] = { spellId = 23302 },            [6] = { spellId = 14462 },        }
    },
    [402] = {
        name = "Field Marshal's Aegis",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23302 },            [6] = { spellId = 14047 },        }
    },
    [421] = {
        name = "Bloodvine Garb",
        bonuses = {            [3] = { spellId = 18382 },        }
    },
    [441] = {
        name = "Primal Batskin",
        bonuses = {            [3] = { spellId = 24090 },        }
    },
    [442] = {
        name = "Blood Tiger Harness",
        bonuses = {            [2] = { spellId = { 7597, 18384 } },        }
    },
    [443] = {
        name = "Bloodsoul Embrace",
        bonuses = {            [3] = { spellId = 21636 },        }
    },
    [444] = {
        name = "The Darksoul",
        bonuses = {            [3] = { spellId = 21416 },        }
    },
    [461] = {
        name = "The Twin Blades of Hakkari",
        bonuses = {            [2] = { spellId = 15763 },        }
    },
    [462] = {
        name = "Zanzil's Concentration",
        bonuses = {            [2] = { spellId = { 9396, 23727 } },        }
    },
    [463] = {
        name = "Primal Blessing",
        bonuses = {            [2] = { spellId = 24256 },        }
    },
    [464] = {
        name = "Overlord's Resolution",
        bonuses = {            [2] = { spellId = 13669 },        }
    },
    [465] = {
        name = "Prayer of the Primal",
        bonuses = {            [2] = { spellId = 9318 },        }
    },
    [466] = {
        name = "Major Mojo Infusion",
        bonuses = {            [2] = { spellId = 9336 },        }
    },
    [467] = {
        name = "The Highlander's Resolution",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7597 },        }
    },
    [468] = {
        name = "The Highlander's Resolve",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7597 },        }
    },
    [469] = {
        name = "The Highlander's Determination",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7597 },        }
    },
    [470] = {
        name = "The Highlander's Fortitude",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 18384 },        }
    },
    [471] = {
        name = "The Highlander's Purpose",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7597 },        }
    },
    [472] = {
        name = "The Highlander's Will",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 18384 },        }
    },
    [473] = {
        name = "The Highlander's Intent",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 18384 },        }
    },
    [474] = {
        name = "Vindicator's Battlegear",
        bonuses = {            [2] = { spellId = 13675 },            [3] = { spellId = 24456 },            [5] = { spellId = 24431 },        }
    },
    [475] = {
        name = "Freethinker's Armor",
        bonuses = {            [2] = { spellId = 21618 },            [3] = { spellId = 24457 },            [5] = { spellId = 24460 },        }
    },
    [476] = {
        name = "Augur's Regalia",
        bonuses = {            [2] = { spellId = 21618 },            [3] = { spellId = 24461 },            [5] = { spellId = 24462 },        }
    },
    [477] = {
        name = "Predator's Armor",
        bonuses = {            [2] = { spellId = 9331 },            [3] = { spellId = 24465 },            [5] = { spellId = 24467 },        }
    },
    [478] = {
        name = "Madcap's Outfit",
        bonuses = {            [2] = { spellId = 9331 },            [3] = { spellId = 24469 },            [5] = { spellId = 24471 },        }
    },
    [479] = {
        name = "Haruspex's Garb",
        bonuses = {            [2] = { spellId = 21618 },            [3] = { spellId = 24479 },            [5] = { spellId = 24480 },        }
    },
    [480] = {
        name = "Confessor's Raiment",
        bonuses = {            [2] = { spellId = 9408 },            [3] = { spellId = 24482 },            [5] = { spellId = 24483 },        }
    },
    [481] = {
        name = "Demoniac's Threads",
        bonuses = {            [2] = { spellId = 9417 },            [3] = { spellId = 24486 },            [5] = { spellId = 24487 },        }
    },
    [482] = {
        name = "Illusionist's Attire",
        bonuses = {            [2] = { spellId = 9417 },            [3] = { spellId = 24489 },            [5] = { spellId = 24491 },        }
    },
    [483] = {
        name = "The Defiler's Determination",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7597 },        }
    },
    [484] = {
        name = "The Defiler's Fortitude",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7597 },        }
    },
    [485] = {
        name = "The Defiler's Intent",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 18384 },        }
    },
    [486] = {
        name = "The Defiler's Purpose",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7597 },        }
    },
    [487] = {
        name = "The Defiler's Resolution",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7597 },        }
    },
    [488] = {
        name = "The Defiler's Will",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 18384 },        }
    },
    [489] = {
        name = "Black Dragon Mail",
        bonuses = {            [2] = { spellId = 15464 },            [3] = { spellId = 7598 },            [4] = { spellId = 14590 },        }
    },
    [490] = {
        name = "Green Dragon Mail",
        bonuses = {            [2] = { spellId = 21625 },            [3] = { spellId = 21894 },        }
    },
    [491] = {
        name = "Blue Dragon Mail",
        bonuses = {            [2] = { spellId = 18675 },            [3] = { spellId = 14127 },        }
    },
    [492] = {
        name = "Twilight Trappings",
        bonuses = {            [3] = { spellId = 24746 },        }
    },
    [493] = {
        name = "Genesis Raiment",
        bonuses = {            [3] = { spellId = { 15693, 18196 } },            [5] = { spellId = 26106 },        }
    },
    [494] = {
        name = "Symbols of Unending Life",
        bonuses = {            [3] = { spellId = 26107 },        }
    },
    [495] = {
        name = "Battlegear of Unyielding Strength",
        bonuses = {            [3] = { spellId = 26111 },        }
    },
    [496] = {
        name = "Conqueror's Battlegear",
        bonuses = {            [3] = { spellId = 26109 },            [5] = { spellId = 26110 },        }
    },
    [497] = {
        name = "Deathdealer's Embrace",
        bonuses = {            [3] = { spellId = 26112 },            [5] = { spellId = 26113 },        }
    },
    [498] = {
        name = "Emblems of Veiled Shadows",
        bonuses = {            [3] = { spellId = 26114 },        }
    },
    [499] = {
        name = "Doomcaller's Attire",
        bonuses = {            [3] = { spellId = 26116 },            [5] = { spellId = 26117 },        }
    },
    [500] = {
        name = "Implements of Unspoken Names",
        bonuses = {            [3] = { spellId = 26118 },        }
    },
    [501] = {
        name = "Stormcaller's Garb",
        bonuses = {            [3] = { spellId = 26119 },            [5] = { spellId = 26122 },        }
    },
    [502] = {
        name = "Gift of the Gathering Storm",
        bonuses = {            [3] = { spellId = 26123 },        }
    },
    [503] = {
        name = "Enigma Vestments",
        bonuses = {            [3] = { spellId = 26127 },            [5] = { spellId = 26128 },        }
    },
    [504] = {
        name = "Trappings of Vaulted Secrets",
        bonuses = {            [3] = { spellId = 26131 },        }
    },
    [505] = {
        name = "Avenger's Battlegear",
        bonuses = {            [3] = { spellId = 26130 },            [5] = { spellId = 23929 },        }
    },
    [506] = {
        name = "Battlegear of Eternal Justice",
        bonuses = {            [3] = { spellId = 26135 },        }
    },
    [507] = {
        name = "Garments of the Oracle",
        bonuses = {            [3] = { spellId = 26169 },            [5] = { spellId = 26171 },        }
    },
    [508] = {
        name = "Finery of Infinite Wisdom",
        bonuses = {            [3] = { spellId = 26172 },        }
    },
    [509] = {
        name = "Striker's Garb",
        bonuses = {            [3] = { spellId = 26173 },            [5] = { spellId = 26174 },        }
    },
    [510] = {
        name = "Trappings of the Unseen Path",
        bonuses = {            [3] = { spellId = 26176 },        }
    },
    [511] = {
        name = "Battlegear of Heroism",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27419 },            [6] = { spellId = 14049 },            [8] = { spellId = 14803 },        }
    },
    [512] = {
        name = "Darkmantle Armor",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27787 },            [6] = { spellId = 14049 },            [8] = { spellId = 14803 },        }
    },
    [513] = {
        name = "Feralheart Raiment",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27781 },            [6] = { spellId = { 9334, 9344 } },            [8] = { spellId = 14803 },        }
    },
    [514] = {
        name = "Vestments of the Virtuous",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27778 },            [6] = { spellId = 14047 },            [8] = { spellId = 14803 },        }
    },
    [515] = {
        name = "Beastmaster Armor",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27785 },            [6] = { spellId = 14049 },            [8] = { spellId = 14803 },        }
    },
    [516] = {
        name = "Soulforge Armor",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27498 },            [6] = { spellId = 14049 },            [8] = { spellId = 14803 },        }
    },
    [517] = {
        name = "Sorcerer's Regalia",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27867 },            [6] = { spellId = 14047 },            [8] = { spellId = 14803 },        }
    },
    [518] = {
        name = "Deathmist Raiment",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27780 },            [6] = { spellId = 14047 },            [8] = { spellId = 14803 },        }
    },
    [519] = {
        name = "The Five Thunders",
        bonuses = {            [2] = { spellId = 18679 },            [4] = { spellId = 27774 },            [6] = { spellId = 14047 },            [8] = { spellId = 14803 },        }
    },
    [520] = {
        name = "Ironweave Battlesuit",
        bonuses = {            [4] = { spellId = 27733 },            [8] = { spellId = 14803 },        }
    },
    [521] = {
        name = "Dreamwalker Raiment",
        bonuses = {            [2] = { spellId = 28716 },            [4] = { spellId = 28743 },            [6] = { spellId = 28744 },            [8] = { spellId = 28719 },        }
    },
    [522] = {
        name = "Champion's Guard",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23048 },            [6] = { spellId = 14467 },        }
    },
    [523] = {
        name = "Dreadnaught's Battlegear",
        bonuses = {            [2] = { spellId = 28844 },            [4] = { spellId = 28843 },            [6] = { spellId = 28842 },            [8] = { spellId = 28845 },        }
    },
    [524] = {
        name = "Bonescythe Armor",
        bonuses = {            [2] = { spellId = 28816 },            [4] = { spellId = 28812 },            [6] = { spellId = 28811 },            [8] = { spellId = 28814 },        }
    },
    [525] = {
        name = "Vestments of Faith",
        bonuses = {            [2] = { spellId = 28807 },            [4] = { spellId = 28809 },            [6] = { spellId = 28808 },            [8] = { spellId = 28802 },        }
    },
    [526] = {
        name = "Frostfire Regalia",
        bonuses = {            [2] = { spellId = 28763 },            [4] = { spellId = 28764 },            [6] = { spellId = 28771 },            [8] = { spellId = 28761 },        }
    },
    [527] = {
        name = "The Earthshatterer",
        bonuses = {            [2] = { spellId = 28818 },            [4] = { spellId = 29171 },            [6] = { spellId = 28823 },            [8] = { spellId = 28821 },        }
    },
    [528] = {
        name = "Redemption Armor",
        bonuses = {            [2] = { spellId = 28775 },            [4] = { spellId = 28774 },            [6] = { spellId = 28789 },            [8] = { spellId = 28787 },        }
    },
    [529] = {
        name = "Plagueheart Raiment",
        bonuses = {            [2] = { spellId = 28831 },            [4] = { spellId = 28829 },            [6] = { spellId = 28746 },            [8] = { spellId = 28830 },        }
    },
    [530] = {
        name = "Cryptstalker Armor",
        bonuses = {            [2] = { spellId = 28755 },            [4] = { spellId = 28756 },            [6] = { spellId = 28752 },            [8] = { spellId = 28751 },        }
    },
    [533] = {
        name = "Battlegear of Undead Slaying",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [534] = {
        name = "Undead Slayer's Armor",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [535] = {
        name = "Garb of the Undead Slayer",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [536] = {
        name = "Regalia of Undead Cleansing",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [537] = {
        name = "Champion's Battlearmor",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 22738 },            [6] = { spellId = 14467 },        }
    },
    [538] = {
        name = "Champion's Stormcaller",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 22804 },            [6] = { spellId = 14467 },        }
    },
    [539] = {
        name = "Champion's Refuge",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23218 },            [6] = { spellId = 14467 },        }
    },
    [540] = {
        name = "Champion's Investiture",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23044 },            [6] = { spellId = 14467 },        }
    },
    [541] = {
        name = "Champion's Dreadgear",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23047 },            [6] = { spellId = 14467 },        }
    },
    [542] = {
        name = "Champion's Arcanum",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23025 },            [6] = { spellId = 14467 },        }
    },
    [543] = {
        name = "Champion's Pursuance",
        bonuses = {            [2] = { spellId = 14384 },            [4] = { spellId = 23158 },            [6] = { spellId = 14467 },        }
    },
    [544] = {
        name = "Lieutenant Commander's Redoubt",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23302 },            [6] = { spellId = 14467 },        }
    },
    [545] = {
        name = "Lieutenant Commander's Battlearmor",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 22738 },            [6] = { spellId = 14467 },        }
    },
    [546] = {
        name = "Lieutenant Commander's Arcanum",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23025 },            [6] = { spellId = 14467 },        }
    },
    [547] = {
        name = "Lieutenant Commander's Dreadgear",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23047 },            [6] = { spellId = 14467 },        }
    },
    [548] = {
        name = "Lieutenant Commander's Guard",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23048 },            [6] = { spellId = 14467 },        }
    },
    [549] = {
        name = "Lieutenant Commander's Investiture",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23044 },            [6] = { spellId = 14467 },        }
    },
    [550] = {
        name = "Lieutenant Commander's Pursuance",
        bonuses = {            [2] = { spellId = 14384 },            [4] = { spellId = 23158 },            [6] = { spellId = 14467 },        }
    },
    [551] = {
        name = "Lieutenant Commander's Refuge",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23218 },            [6] = { spellId = 14467 },        }
    },
    [1570] = {
        name = "Twilight Invoker's Vestments",
        bonuses = {            [2] = { spellId = 9415 },            [3] = { spellId = 432639 },        }
    },
    [1571] = {
        name = "Judgement Redoubt",
        bonuses = {            [3] = { spellId = 428491 },            [5] = { spellId = 428490 },            [8] = { spellId = 24196 },        }
    },
    [1576] = {
        name = "Battleplate of Might",
        bonuses = {            [3] = { spellId = 429864 },            [5] = { spellId = 429863 },            [8] = { spellId = 429865 },        }
    },
    [1577] = {
        name = "Blackfathom Avenger's Mail",
        bonuses = {            [2] = { spellId = 9141 },            [3] = { spellId = 432639 },        }
    },
    [1578] = {
        name = "Blackfathom Slayer's Leather",
        bonuses = {            [2] = { spellId = 9141 },            [3] = { spellId = 432639 },        }
    },
    [1579] = {
        name = "Blackfathom Elementalist's Hide",
        bonuses = {            [2] = { spellId = 9417 },            [3] = { spellId = 432639 },        }
    },
    [1584] = {
        name = "Irradiated Garments",
        bonuses = {            [2] = { spellId = { 435974, 436239 } },            [3] = { spellId = 435975 },        }
    },
    [1585] = {
        name = "Insulated Leathers",
        bonuses = {            [2] = { spellId = 436239 },            [3] = { spellId = { 435976, 7574 } },        }
    },
    [1586] = {
        name = "Insulated Sorceror's Leathers",
        bonuses = {            [2] = { spellId = 9345 },            [3] = { spellId = 24433 },        }
    },
    [1587] = {
        name = "Hyperconductive Wizard's Attire",
        bonuses = {            [2] = { spellId = { 15666, 432639 } },            [3] = { spellId = 435977 },        }
    },
    [1588] = {
        name = "Hyperconductive Mender's Meditation",
        bonuses = {            [2] = { spellId = 9263 },            [3] = { spellId = 21364 },        }
    },
    [1589] = {
        name = "H.A.Z.A.R.D. Suit",
        bonuses = {            [2] = { spellId = { 9329, 13385 } },            [3] = { spellId = 432639 },        }
    },
    [1590] = {
        name = "Electromantic Devastator's Mail",
        bonuses = {            [2] = { spellId = 14027 },            [3] = { spellId = 435982 },        }
    },
    [1591] = {
        name = "Electromantic Stormbringer's Chain",
        bonuses = {            [2] = { spellId = 9417 },            [3] = { spellId = 435983 },        }
    },
    [1592] = {
        name = "Shockforged Warplate",
        bonuses = {            [2] = { spellId = 9417 },            [3] = { spellId = 436284 },        }
    },
    [1593] = {
        name = "Felheart of the Wicked",
        bonuses = {            [3] = { spellId = 21741 },            [5] = { spellId = 23554 },        }
    },
    [1618] = {
        name = "Blood Guard's Plate",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9336 },        }
    },
    [1619] = {
        name = "Knight-Lieutenant's Plate",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9336 },        }
    },
    [1620] = {
        name = "Knight-Lieutenant's Imbued Plate",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9318 },        }
    },
    [1621] = {
        name = "Knight-Lieutenant's Lamellar Plate",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9346 },        }
    },
    [1622] = {
        name = "Blood Guard's Mail",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9336 },        }
    },
    [1623] = {
        name = "Blood Guard's Pulsing Mail",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9346 },        }
    },
    [1624] = {
        name = "Blood Guard's Inscribed Mail",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9318 },        }
    },
    [1625] = {
        name = "Blood Guard's Chain",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9336 },        }
    },
    [1626] = {
        name = "Knight-Lieutenant's Chain",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9336 },        }
    },
    [1627] = {
        name = "Blood Guard's Leather",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9336 },        }
    },
    [1628] = {
        name = "Knight-Lieutenant's Leather",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9336 },        }
    },
    [1629] = {
        name = "Blood Guard's Restored Leather",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9318 },        }
    },
    [1630] = {
        name = "Knight-Lieutenant's Restored Leather",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9318 },        }
    },
    [1631] = {
        name = "Blood Guard's Crackling Leather",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9346 },        }
    },
    [1632] = {
        name = "Knight-Lieutenant's Crackling Leather",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9346 },        }
    },
    [1633] = {
        name = "Blood Guard's Dreadweave",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9346 },        }
    },
    [1634] = {
        name = "Knight-Lieutenant's Dreadweave",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9346 },        }
    },
    [1635] = {
        name = "Blood Guard's Satin",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9318 },        }
    },
    [1636] = {
        name = "Knight Lieutenant's Satin",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9318 },        }
    },
    [1637] = {
        name = "Nightmare Prophet's Garb",
        bonuses = {            [2] = { spellId = 432639 },            [3] = { spellId = 450012 },        }
    },
    [1638] = {
        name = "Benevolent Prophet's Vestments",
        bonuses = {            [2] = { spellId = 21618 },            [3] = { spellId = 449921 },        }
    },
    [1639] = {
        name = "Malevolent Prophet's Vestments",
        bonuses = {            [2] = { spellId = 436239 },            [3] = { spellId = 449919 },        }
    },
    [1640] = {
        name = "Coagulate Bloodguard's Leathers",
        bonuses = {            [2] = { spellId = 9121 },            [3] = { spellId = { 449924, 449926 } },        }
    },
    [1641] = {
        name = "Blood Corrupted Leathers",
        bonuses = {            [2] = { spellId = 432639 },            [3] = { spellId = 449928 },        }
    },
    [1642] = {
        name = "Lost Worshipper's Armor",
        bonuses = {            [2] = { spellId = 432639 },            [3] = { spellId = 446169 },        }
    },
    [1643] = {
        name = "Exiled Prophet's Raiment",
        bonuses = {            [2] = { spellId = 21618 },            [3] = { spellId = 449929 },        }
    },
    [1644] = {
        name = "Corrupted Spiritweaver's Mail",
        bonuses = {            [2] = { spellId = 21618 },            [3] = { spellId = 449930 },        }
    },
    [1645] = {
        name = "Ostracized Berserker's Battlemail",
        bonuses = {            [2] = { spellId = 9331 },            [3] = { spellId = 449931 },        }
    },
    [1646] = {
        name = "Shunned Devotee's Chainmail",
        bonuses = {            [2] = { spellId = 436239 },            [3] = { spellId = { 449933, 449935 } },        }
    },
    [1647] = {
        name = "Dread Hunter's Chain",
        bonuses = {            [2] = { spellId = 9331 },            [3] = { spellId = { 450083, 450403 } },        }
    },
    [1648] = {
        name = "Obsessed Prophet's Plate",
        bonuses = {            [2] = { spellId = 436239 },            [3] = { spellId = 449933 },        }
    },
    [1649] = {
        name = "Wailing Berserker's Plate Armor",
        bonuses = {            [2] = { spellId = 432639 },            [3] = { spellId = 449970 },        }
    },
    [1650] = {
        name = "Banished Martyr's Full Plate",
        bonuses = {            [2] = { spellId = 432639 },            [3] = { spellId = 449974 },        }
    },
    [1651] = {
        name = "Serpent's Ascension",
        bonuses = {            [2] = { spellId = 446233 },        }
    },
    [1652] = {
        name = "Emerald Dream Plate",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9331 },        }
    },
    [1653] = {
        name = "Emerald Encrusted Battleplate",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9408 },        }
    },
    [1654] = {
        name = "Emerald Scalemail",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9331 },        }
    },
    [1655] = {
        name = "Emerald Laden Chain",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9408 },        }
    },
    [1656] = {
        name = "Emerald Chainmail",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9417 },        }
    },
    [1657] = {
        name = "Emerald Leathers",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9331 },        }
    },
    [1658] = {
        name = "Emerald Dreamkeeper Garb",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9408 },        }
    },
    [1659] = {
        name = "Emerald Watcher Vestments",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9417 },        }
    },
    [1660] = {
        name = "Emerald Enchanted Vestments",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9417 },        }
    },
    [1661] = {
        name = "Emerald Woven Garb",
        bonuses = {            [3] = { spellId = 9117 },            [6] = { spellId = 9408 },        }
    },
    [1664] = {
        name = "Cenarion Eclipse",
        bonuses = {            [5] = { spellId = 447296 },        }
    },
    [1665] = {
        name = "Knight-Lieutenant's Mail",
        bonuses = {            [3] = { spellId = 14462 },            [6] = { spellId = 9336 },        }
    },
    [1666] = {
        name = "Wildheart Raiment",
        bonuses = {            [2] = { spellId = 29097 },            [4] = { spellId = 450512 },            [6] = { spellId = 450608 },            [8] = { spellId = 18679 },        }
    },
    [1667] = {
        name = "Feralheart Raiment",
        bonuses = {            [2] = { spellId = 450512 },            [4] = { spellId = 450608 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1668] = {
        name = "Beaststalker Armor",
        bonuses = {            [2] = { spellId = 29094 },            [4] = { spellId = 30772 },            [6] = { spellId = 450577 },            [8] = { spellId = 18679 },        }
    },
    [1669] = {
        name = "Beastmaster Armor",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 450577 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1670] = {
        name = "Magister's Regalia",
        bonuses = {            [2] = { spellId = 29091 },            [4] = { spellId = 30777 },            [6] = { spellId = 450527 },            [8] = { spellId = 18679 },        }
    },
    [1671] = {
        name = "Sorcerer's Regalia",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 450527 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1672] = {
        name = "Lightforge Armor",
        bonuses = {            [2] = { spellId = 29093 },            [4] = { spellId = 450516 },            [6] = { spellId = 450625 },            [8] = { spellId = 18679 },        }
    },
    [1673] = {
        name = "Soulforge Armor",
        bonuses = {            [2] = { spellId = 450516 },            [4] = { spellId = 450625 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1674] = {
        name = "Vestments of the Devout",
        bonuses = {            [2] = { spellId = 14803 },            [4] = { spellId = 30779 },            [6] = { spellId = 450576 },            [8] = { spellId = 18679 },        }
    },
    [1675] = {
        name = "Vestments of the Virtuous",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 450576 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1676] = {
        name = "Darkmantle Armor",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 27787 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1677] = {
        name = "Shadowcraft Armor",
        bonuses = {            [2] = { spellId = 29096 },            [4] = { spellId = 30771 },            [6] = { spellId = 27787 },            [8] = { spellId = 18679 },        }
    },
    [1678] = {
        name = "The Elements",
        bonuses = {            [2] = { spellId = 29095 },            [4] = { spellId = 450517 },            [6] = { spellId = 450626 },            [8] = { spellId = 18679 },        }
    },
    [1679] = {
        name = "The Five Thunders",
        bonuses = {            [2] = { spellId = 450517 },            [4] = { spellId = 450626 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1680] = {
        name = "Dreadmist Raiment",
        bonuses = {            [2] = { spellId = 29090 },            [4] = { spellId = 30778 },            [6] = { spellId = 450585 },            [8] = { spellId = 18679 },        }
    },
    [1681] = {
        name = "Deathmist Raiment",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 450585 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1682] = {
        name = "Battlegear of Valor",
        bonuses = {            [2] = { spellId = 29092 },            [4] = { spellId = 30770 },            [6] = { spellId = 450587 },            [8] = { spellId = 18679 },        }
    },
    [1698] = {
        name = "Cenarion Eclipse",
        tier = "1",
        bonuses = {            [2] = { spellId = 455852 },            [4] = { spellId = 455858 },            [6] = { spellId = 455859 },        }
    },
    [1699] = {
        name = "Cenarion Cunning",
        tier = "1",
        bonuses = {            [2] = { spellId = 455864 },            [4] = { spellId = 455872 },            [6] = { spellId = 455873 },        }
    },
    [1700] = {
        name = "Cenarion Bounty",
        tier = "1",
        bonuses = {            [2] = { spellId = 456194 },            [4] = { spellId = 456222 },            [6] = { spellId = 456322 },        }
    },
    [1701] = {
        name = "Cenarion Rage",
        tier = "1",
        bonuses = {            [2] = { spellId = 456325 },            [4] = { spellId = 456328 },            [6] = { spellId = 456332 },        }
    },
    [1702] = {
        name = "Giantstalker Pursuit",
        tier = "1",
        bonuses = {            [2] = { spellId = 456337 },            [4] = { spellId = 457324 },            [6] = { spellId = 456379 },        }
    },
    [1703] = {
        name = "Giantstalker Prowess",
        tier = "1",
        bonuses = {            [2] = { spellId = 456389 },            [4] = { spellId = 456341 },            [6] = { spellId = 456394 },        }
    },
    [1704] = {
        name = "Arcanist Insight",
        tier = "1",
        bonuses = {            [2] = { spellId = 456396 },            [4] = { spellId = 456398 },            [6] = { spellId = 456402 },        }
    },
    [1705] = {
        name = "Arcanist Moment",
        tier = "1",
        bonuses = {            [2] = { spellId = 456404 },            [4] = { spellId = 456477 },            [6] = { spellId = 456481 },        }
    },
    [1706] = {
        name = "Lawbringer Mercy",
        tier = "1",
        bonuses = {            [2] = { spellId = 456488 },            [4] = { spellId = 457323 },            [6] = { spellId = 456492 },        }
    },
    [1707] = {
        name = "Lawbringer Radiance",
        tier = "1",
        bonuses = {            [2] = { spellId = 456494 },            [4] = { spellId = 456489 },            [6] = { spellId = 456533 },        }
    },
    [1708] = {
        name = "Lawbringer Will",
        tier = "1",
        bonuses = {            [2] = { spellId = 456536 },            [4] = { spellId = 456538 },            [6] = { spellId = 456541 },        }
    },
    [1709] = {
        name = "Dawn Prophecy",
        tier = "1",
        bonuses = {            [2] = { spellId = 456545 },            [4] = { spellId = 456546 },            [6] = { spellId = 456547 },        }
    },
    [1710] = {
        name = "Twilight Prophecy",
        tier = "1",
        bonuses = {            [2] = { spellId = 456548 },            [4] = { spellId = 457322 },            [6] = { spellId = 457325 },        }
    },
    [1711] = {
        name = "Nightslayer Thrill",
        tier = "1",
        bonuses = {            [2] = { spellId = 457329 },            [4] = { spellId = 457339 },            [6] = { spellId = 457344 },        }
    },
    [1712] = {
        name = "Nightslayer Battlearmor",
        tier = "1",
        bonuses = {            [2] = { spellId = 457349 },            [4] = { spellId = 457440 },            [6] = { spellId = 457464 },        }
    },
    [1713] = {
        name = "Earthfury Relief",
        tier = "1",
        bonuses = {            [2] = { spellId = 457475 },            [4] = { spellId = 457478 },            [6] = { spellId = 457494 },        }
    },
    [1714] = {
        name = "Earthfury Eruption",
        tier = "1",
        bonuses = {            [2] = { spellId = 457475 },            [4] = { spellId = 457520 },            [6] = { spellId = 457524 },        }
    },
    [1715] = {
        name = "Earthfury Impact",
        tier = "1",
        bonuses = {            [2] = { spellId = 457475 },            [4] = { spellId = 457530 },            [6] = { spellId = 457532 },        }
    },
    [1716] = {
        name = "Earthfury Resolve",
        tier = "1",
        bonuses = {            [2] = { spellId = 457540 },            [4] = { spellId = 457541 },            [6] = { spellId = 457544 },        }
    },
    [1717] = {
        name = "Corrupted Felheart",
        tier = "1",
        bonuses = {            [2] = { spellId = 457548 },            [4] = { spellId = 457549 },            [6] = { spellId = 457553 },        }
    },
    [1718] = {
        name = "Wicked Felheart",
        tier = "1",
        bonuses = {            [2] = { spellId = 457571 },            [4] = { spellId = 457572 },            [6] = { spellId = 457642 },        }
    },
    [1719] = {
        name = "Immoveable Might",
        tier = "1",
        bonuses = {            [2] = { spellId = 457645 },            [4] = { spellId = 457646 },            [6] = { spellId = 457651 },        }
    },
    [1720] = {
        name = "Unstoppable Might",
        tier = "1",
        bonuses = {            [2] = { spellId = 457652 },            [4] = { spellId = 457697 },            [6] = { spellId = 457820 },        }
    },
    [1721] = {
        name = "Warlord's Battlegear",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 22738 },            [6] = { spellId = 14049 },        }
    },
    [1722] = {
        name = "Warlord's Sanctuary",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23218 },            [6] = { spellId = 14049 },        }
    },
    [1723] = {
        name = "Warlord's Wildhide",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23218 },            [6] = { spellId = 14047 },        }
    },
    [1724] = {
        name = "Warlord's Refuge",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23218 },            [6] = { spellId = 467550 },        }
    },
    [1725] = {
        name = "Warlord's Pursuit",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23158 },            [6] = { spellId = 14384 },        }
    },
    [1726] = {
        name = "Warlord's Prowess",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 459584 },            [6] = { spellId = 14049 },        }
    },
    [1727] = {
        name = "Warlord's Regalia",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23025 },            [6] = { spellId = 14047 },        }
    },
    [1728] = {
        name = "Warlord's Raiment",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23044 },            [6] = { spellId = 14047 },        }
    },
    [1729] = {
        name = "Warlord's Investiture",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23044 },            [6] = { spellId = 467550 },        }
    },
    [1730] = {
        name = "Warlord's Vestments",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23048 },            [6] = { spellId = 14049 },        }
    },
    [1731] = {
        name = "Warlord's Earthshaker",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 22804 },            [6] = { spellId = 14049 },        }
    },
    [1732] = {
        name = "Warlord's Thunderfist",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 22804 },            [6] = { spellId = 14047 },        }
    },
    [1733] = {
        name = "Warlord's Wartide",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 22804 },            [6] = { spellId = 467550 },        }
    },
    [1734] = {
        name = "Warlord's Threads",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23047 },            [6] = { spellId = 14047 },        }
    },
    [1735] = {
        name = "Field Marshal's Wildhide",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23218 },            [6] = { spellId = 14047 },        }
    },
    [1736] = {
        name = "Field Marshal's Refuge",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23218 },            [6] = { spellId = 467550 },        }
    },
    [1737] = {
        name = "Field Marshal's Sanctuary",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23218 },            [6] = { spellId = 14049 },        }
    },
    [1738] = {
        name = "Field Marshal's Prowess",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 459584 },            [6] = { spellId = 14049 },        }
    },
    [1739] = {
        name = "Field Marshal's Pursuit",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23158 },            [6] = { spellId = 14384 },        }
    },
    [1740] = {
        name = "Field Marshal's Regalia",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23025 },            [6] = { spellId = 14047 },        }
    },
    [1741] = {
        name = "Field Marshal's Raiment",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23044 },            [6] = { spellId = 14047 },        }
    },
    [1742] = {
        name = "Field Marshal's Investiture",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23044 },            [6] = { spellId = 467550 },        }
    },
    [1743] = {
        name = "Field Marshal's Vestments",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23048 },            [6] = { spellId = 14049 },        }
    },
    [1744] = {
        name = "Field Marshal's Vindication",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23302 },            [6] = { spellId = 14049 },        }
    },
    [1745] = {
        name = "Field Marshal's Redemption",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23302 },            [6] = { spellId = 467550 },        }
    },
    [1746] = {
        name = "Field Marshal's Threads",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 23047 },            [6] = { spellId = 14047 },        }
    },
    [1747] = {
        name = "Field Marshal's Battlegear",
        bonuses = {            [2] = { spellId = 14467 },            [3] = { spellId = 22738 },            [6] = { spellId = 14049 },        }
    },
    [1748] = {
        name = "Champion's Wildhide",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23218 },            [6] = { spellId = 14467 },        }
    },
    [1749] = {
        name = "Champion's Refuge",
        bonuses = {            [2] = { spellId = 17371 },            [4] = { spellId = 23218 },            [6] = { spellId = 14467 },        }
    },
    [1750] = {
        name = "Champion's Sanctuary",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23218 },            [6] = { spellId = 14467 },        }
    },
    [1751] = {
        name = "Champion's Prowess",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 459584 },            [6] = { spellId = 14467 },        }
    },
    [1752] = {
        name = "Champion's Pursuit",
        bonuses = {            [2] = { spellId = 14384 },            [4] = { spellId = 23158 },            [6] = { spellId = 14467 },        }
    },
    [1753] = {
        name = "Champion's Regalia",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23025 },            [6] = { spellId = 14467 },        }
    },
    [1754] = {
        name = "Champion's Raiment",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23044 },            [6] = { spellId = 14467 },        }
    },
    [1755] = {
        name = "Champion's Investiture",
        bonuses = {            [2] = { spellId = 17371 },            [4] = { spellId = 23044 },            [6] = { spellId = 14467 },        }
    },
    [1756] = {
        name = "Champion's Vestments",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23048 },            [6] = { spellId = 14467 },        }
    },
    [1757] = {
        name = "Champion's Thunderfist",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 22804 },            [6] = { spellId = 14467 },        }
    },
    [1758] = {
        name = "Champion's Wartide",
        bonuses = {            [2] = { spellId = 17371 },            [4] = { spellId = 22804 },            [6] = { spellId = 14467 },        }
    },
    [1759] = {
        name = "Champion's Earthshaker",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 22804 },            [6] = { spellId = 14467 },        }
    },
    [1760] = {
        name = "Champion's Threads",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23047 },            [6] = { spellId = 14467 },        }
    },
    [1761] = {
        name = "Champion's Battlegear",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 22738 },            [6] = { spellId = 14467 },        }
    },
    [1762] = {
        name = "Lieutenant Commander's Wildhide",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23218 },            [6] = { spellId = 14467 },        }
    },
    [1763] = {
        name = "Lieutenant Commander's Refuge",
        bonuses = {            [2] = { spellId = 17371 },            [4] = { spellId = 23218 },            [6] = { spellId = 14467 },        }
    },
    [1764] = {
        name = "Lieutenant Commander's Sanctuary",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23218 },            [6] = { spellId = 14467 },        }
    },
    [1765] = {
        name = "Lieutenant Commander's Prowess",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 459584 },            [6] = { spellId = 14467 },        }
    },
    [1766] = {
        name = "Lieutenant Commander's Pursuit",
        bonuses = {            [2] = { spellId = 14384 },            [4] = { spellId = 23158 },            [6] = { spellId = 14467 },        }
    },
    [1767] = {
        name = "Lieutenant Commander's Regalia",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23025 },            [6] = { spellId = 14467 },        }
    },
    [1768] = {
        name = "Lieutenant Commander's Raiment",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23044 },            [6] = { spellId = 14467 },        }
    },
    [1769] = {
        name = "Lieutenant Commander's Investiture",
        bonuses = {            [2] = { spellId = 17371 },            [4] = { spellId = 23044 },            [6] = { spellId = 14467 },        }
    },
    [1770] = {
        name = "Lieutenant Commander's Vestments",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23048 },            [6] = { spellId = 14467 },        }
    },
    [1774] = {
        name = "Lieutenant Commander's Threads",
        bonuses = {            [2] = { spellId = 14047 },            [4] = { spellId = 23047 },            [6] = { spellId = 14467 },        }
    },
    [1775] = {
        name = "Lieutenant Commander's Battlegear",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 22738 },            [6] = { spellId = 14467 },        }
    },
    [1776] = {
        name = "Lieutenant Commander's Redemption",
        bonuses = {            [2] = { spellId = 17371 },            [4] = { spellId = 23302 },            [6] = { spellId = 14467 },        }
    },
    [1777] = {
        name = "Lieutenant Commander's Vindication",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 23302 },            [6] = { spellId = 14467 },        }
    },
    [1778] = {
        name = "Battlegear of Heroism",
        bonuses = {            [2] = { spellId = 14049 },            [4] = { spellId = 450587 },            [6] = { spellId = 18679 },            [8] = { spellId = 14803 },        }
    },
    [1779] = {
        name = "Core Hound's Call",
        bonuses = {            [2] = { spellId = 461267 },            [3] = { spellId = 461268 },        }
    },
    [1780] = {
        name = "Shard of the Gods",
        bonuses = {            [2] = { spellId = { 18036, 461698, 461697 } },        }
    },
    [1781] = {
        name = "Spirit of Eskhandar",
        bonuses = {            [2] = { spellId = 432639 },            [3] = { spellId = 436239 },            [4] = { spellId = 461990 },        }
    },
    [1782] = {
        name = "The Postmaster",
        bonuses = {            [2] = { spellId = 9764 },            [3] = { spellId = { 14712, 14590 } },            [4] = { spellId = 9417 },            [5] = { spellId = { 9106, 17498 } },        }
    },
    [1783] = {
        name = "Spider's Kiss",
        bonuses = {            [2] = { spellId = { 17332, 13385 } },        }
    },
    [1784] = {
        name = "Dal'Rend's Arms",
        bonuses = {            [2] = { spellId = 14056 },        }
    },
    [1785] = {
        name = "Ironweave Battlesuit",
        bonuses = {            [2] = { spellId = 27733 },            [4] = { spellId = 14803 },            [6] = { spellId = 14047 },        }
    },
    [1786] = {
        name = "Deathbone Guardian",
        bonuses = {            [2] = { spellId = 7516 },            [3] = { spellId = 9764 },            [4] = { spellId = 18686 },            [5] = { spellId = 13665 },        }
    },
    [1787] = {
        name = "Necropile Raiment",
        bonuses = {            [2] = { spellId = 7503 },            [3] = { spellId = 7495 },            [4] = { spellId = 18686 },            [5] = { spellId = 14047 },        }
    },
    [1788] = {
        name = "Bloodmail Regalia",
        bonuses = {            [2] = { spellId = 7516 },            [3] = { spellId = 9140 },            [4] = { spellId = 18686 },            [5] = { spellId = 13665 },        }
    },
    [1789] = {
        name = "Volcanic Armor",
        bonuses = {            [2] = { spellId = 14590 },            [3] = { spellId = 9233 },        }
    },
    [1790] = {
        name = "Blue Dragon Mail",
        bonuses = {            [2] = { spellId = 18675 },            [3] = { spellId = 14127 },        }
    },
    [1791] = {
        name = "Green Dragon Mail",
        bonuses = {            [2] = { spellId = 21625 },            [3] = { spellId = 21894 },        }
    },
    [1792] = {
        name = "Black Dragon Mail",
        bonuses = {            [2] = { spellId = 432639 },            [3] = { spellId = 448324 },            [4] = { spellId = 14590 },        }
    },
    [1793] = {
        name = "Devilsaur Armor",
        bonuses = {            [2] = { spellId = { 14590, 460230 } },        }
    },
    [1795] = {
        name = "Zanzil's Concentration",
        bonuses = {            [2] = { spellId = { 9396, 432639 } },        }
    },
    [1796] = {
        name = "Prayer of the Primal",
        bonuses = {            [2] = { spellId = 467647 },        }
    },
    [1797] = {
        name = "Major Mojo Infusion",
        bonuses = {            [2] = { spellId = 9336 },        }
    },
    [1798] = {
        name = "Primal Blessing",
        bonuses = {            [2] = { spellId = 467743 },        }
    },
    [1799] = {
        name = "Overlord's Resolution",
        bonuses = {            [2] = { spellId = 13387 },        }
    },
    [1800] = {
        name = "The Twin Blades of Hakkari",
        bonuses = {            [2] = { spellId = { 7523, 468256 } },        }
    },
    [1801] = {
        name = "Eclipse of Stormrage",
        tier = "2",
        bonuses = {            [2] = { spellId = 467077 },            [4] = { spellId = 467084 },            [6] = { spellId = 467090 },        }
    },
    [1802] = {
        name = "Bounty of Stormrage",
        tier = "2-",
        bonuses = {            [2] = { spellId = 467099 },            [4] = { spellId = 467203 },            [6] = { spellId = 467205 },        }
    },
    [1803] = {
        name = "Cunning of Stormrage",
        tier = "2-",
        bonuses = {            [2] = { spellId = 467207 },            [4] = { spellId = 467208 },            [6] = { spellId = 467211 },        }
    },
    [1804] = {
        name = "Fury of Stormrage",
        tier = "2-",
        bonuses = {            [2] = { spellId = 467216 },            [4] = { spellId = 467221 },            [6] = { spellId = 467227 },        }
    },
    [1805] = {
        name = "Dragonstalker's Pursuit",
        tier = "2-",
        bonuses = {            [2] = { spellId = 467235 },            [4] = { spellId = 467312 },            [6] = { spellId = 467326 },        }
    },
    [1806] = {
        name = "Dragonstalker's Prowess",
        tier = "2-",
        bonuses = {            [2] = { spellId = 467329 },            [4] = { spellId = 467333 },            [6] = { spellId = 467334 },        }
    },
    [1807] = {
        name = "Netherwind Insight",
        tier = "2",
        bonuses = {            [2] = { spellId = 467387 },            [4] = { spellId = 467388 },            [6] = { spellId = 467399 },        }
    },
    [1808] = {
        name = "Netherwind Moment",
        tier = "2",
        bonuses = {            [2] = { spellId = 467401 },            [4] = { spellId = 467405 },            [6] = { spellId = 467494 },        }
    },
    [1809] = {
        name = "Merciful Judgement",
        tier = "2",
        bonuses = {            [2] = { spellId = 467506 },            [4] = { spellId = 467507 },            [6] = { spellId = 467513 },        }
    },
    [1810] = {
        name = "Radiant Judgement",
        tier = "2",
        bonuses = {            [2] = { spellId = 467518 },            [4] = { spellId = 467526 },            [6] = { spellId = 467529 },        }
    },
    [1811] = {
        name = "Wilfull Judgement",
        tier = "2",
        bonuses = {            [2] = { spellId = 467531 },            [4] = { spellId = 467532 },            [6] = { spellId = 467536 },        }
    },
    [1812] = {
        name = "Dawn of Transcendence",
        tier = "2",
        bonuses = {            [2] = { spellId = 467539 },            [4] = { spellId = 467544 },            [6] = { spellId = 467586 },        }
    },
    [1813] = {
        name = "Twilight of Transcendence",
        tier = "2",
        bonuses = {            [2] = { spellId = 467604 },            [4] = { spellId = 467608 },            [6] = { spellId = 467624 },        }
    },
    [1814] = {
        name = "Bloodfang Thrill",
        tier = "2",
        bonuses = {            [2] = { spellId = 467708 },            [4] = { spellId = 467737 },            [6] = { spellId = 467739 },        }
    },
    [1815] = {
        name = "Bloodfang Battlearmor",
        tier = "2",
        bonuses = {            [2] = { spellId = 467746 },            [4] = { spellId = 467797 },            [6] = { spellId = 467803 },        }
    },
    [1816] = {
        name = "Relief of the Ten Storms",
        tier = "2",
        bonuses = {            [2] = { spellId = 467804 },            [4] = { spellId = 467809 },            [6] = { spellId = 467814 },        }
    },
    [1817] = {
        name = "Eruption of the Ten Storms",
        tier = "2",
        bonuses = {            [2] = { spellId = 467818 },            [4] = { spellId = 467823 },            [6] = { spellId = 467863 },        }
    },
    [1818] = {
        name = "Impact of the Ten Storms",
        tier = "2",
        bonuses = {            [2] = { spellId = 467877 },            [4] = { spellId = 467879 },            [6] = { spellId = 467882 },        }
    },
    [1819] = {
        name = "Resolve of the Ten Storms",
        tier = "2",
        bonuses = {            [2] = { spellId = 467889 },            [4] = { spellId = 467909 },            [6] = { spellId = 467916 },        }
    },
    [1820] = {
        name = "Corrupted Nemesis",
        tier = "2",
        bonuses = {            [2] = { spellId = 467917 },            [4] = { spellId = 467983 },            [6] = { spellId = 467988 },        }
    },
    [1821] = {
        name = "Wicked Nemesis",
        tier = "2",
        bonuses = {            [2] = { spellId = 468028 },            [4] = { spellId = 468046 },            [6] = { spellId = 468061 },        }
    },
    [1822] = {
        name = "Immoveable Wrath",
        tier = "2",
        bonuses = {            [2] = { spellId = 468065 },            [4] = { spellId = 468067 },            [6] = { spellId = 468069 },        }
    },
    [1823] = {
        name = "Unstoppable Wrath",
        tier = "2",
        bonuses = {            [2] = { spellId = 468072 },            [4] = { spellId = 468235 },            [6] = { spellId = 468236 },        }
    },
    [1824] = {
        name = "Haruspex's Garb",
        bonuses = {            [2] = { spellId = 468395 },            [3] = { spellId = 468415 },            [5] = { spellId = 468416 },        }
    },
    [1825] = {
        name = "Predator's Armor",
        bonuses = {            [2] = { spellId = 468407 },            [3] = { spellId = 468417 },            [5] = { spellId = 468418 },        }
    },
    [1826] = {
        name = "Illusionist's Attire",
        bonuses = {            [2] = { spellId = 468397 },            [3] = { spellId = 468425 },            [5] = { spellId = 468427 },        }
    },
    [1827] = {
        name = "Freethinker's Armor",
        bonuses = {            [2] = { spellId = 468401 },            [3] = { spellId = 468428 },            [5] = { spellId = 468431 },        }
    },
    [1828] = {
        name = "Confessor's Raiment",
        bonuses = {            [2] = { spellId = 468398 },            [3] = { spellId = 468433 },            [5] = { spellId = 468434 },        }
    },
    [1829] = {
        name = "Madcap's Outfit",
        bonuses = {            [2] = { spellId = 468409 },            [3] = { spellId = 468436 },            [5] = { spellId = 468438 },        }
    },
    [1830] = {
        name = "Augur's Regalia",
        tier = "an",
        bonuses = {            [2] = { spellId = 468411 },            [3] = { spellId = 468441 },            [5] = { spellId = 468445 },        }
    },
    [1831] = {
        name = "Demoniac's Threads",
        bonuses = {            [2] = { spellId = 468400 },            [3] = { spellId = 468446 },            [5] = { spellId = 468447 },        }
    },
    [1832] = {
        name = "Vindicator's Battlegear",
        bonuses = {            [2] = { spellId = 468412 },            [3] = { spellId = 468452 },            [5] = { spellId = 468453 },        }
    },
    [1835] = {
        name = "Genesis Bounty",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213159 },            [4] = { spellId = 1213160 },        }
    },
    [1836] = {
        name = "Genesis Eclipse",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213164 },            [4] = { spellId = 1213167 },        }
    },
    [1837] = {
        name = "Genesis Fury",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213188 },            [4] = { spellId = 1213196 },        }
    },
    [1838] = {
        name = "Genesis Cunning",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213171 },            [4] = { spellId = 1213174 },        }
    },
    [1839] = {
        name = "Striker's Pursuit",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213306 },            [4] = { spellId = 1213246 },        }
    },
    [1840] = {
        name = "Striker's Prowess",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213307 },            [4] = { spellId = 1213309 },        }
    },
    [1841] = {
        name = "Enigma Insight",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213318 },            [4] = { spellId = 1213319 },        }
    },
    [1842] = {
        name = "Enigma Moment",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213312 },            [4] = { spellId = 1213314 },        }
    },
    [1843] = {
        name = "Avenger's Mercy",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213349 },            [4] = { spellId = 1213353 },        }
    },
    [1844] = {
        name = "Avenger's Will",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213410 },            [4] = { spellId = 1213413 },        }
    },
    [1845] = {
        name = "Avenger's Radiance",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213397 },            [4] = { spellId = 1213406 },        }
    },
    [1846] = {
        name = "Dawn of the Oracle",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213624 },            [4] = { spellId = 1213631 },        }
    },
    [1847] = {
        name = "Twilight of the Oracle",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213675 },            [4] = { spellId = 1213705 },        }
    },
    [1848] = {
        name = "Deathdealer's Thrill",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213713 },            [4] = { spellId = 1213714 },        }
    },
    [1849] = {
        name = "Deathdealer's Battlearmor",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213754 },            [4] = { spellId = 1213759 },        }
    },
    [1850] = {
        name = "Stormcaller's Relief",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213810 },            [4] = { spellId = 1213894 },        }
    },
    [1851] = {
        name = "Stormcaller's Eruption",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213900 },            [4] = { spellId = 1213902 },        }
    },
    [1852] = {
        name = "Stormcaller's Resolve",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213930 },            [4] = { spellId = 1213937 },        }
    },
    [1853] = {
        name = "Stormcaller's Impact",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1213910 },            [4] = { spellId = 1213918 },        }
    },
    [1854] = {
        name = "Doomcaller's Corruption",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1214085 },            [4] = { spellId = 1214087 },        }
    },
    [1855] = {
        name = "Doomcaller's Malevolence",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1214091 },            [4] = { spellId = 1214095 },        }
    },
    [1856] = {
        name = "Conqueror's Advance",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1214159 },            [4] = { spellId = 1214163 },        }
    },
    [1857] = {
        name = "Conqueror's Bulwark",
        tier = "AQ",
        bonuses = {            [2] = { spellId = 1214160 },            [4] = { spellId = 1214162 },        }
    },
    [1858] = {
        name = "Symbols of Unending Life",
        bonuses = {            [3] = { spellId = 1213201 },        }
    },
    [1859] = {
        name = "Trappings of the Unseen Path",
        bonuses = {            [3] = { spellId = 1213310 },        }
    },
    [1860] = {
        name = "Trappings of Vaulted Secrets",
        bonuses = {            [3] = { spellId = 1213321 },        }
    },
    [1861] = {
        name = "Battlegear of Eternal Justice",
        bonuses = {            [3] = { spellId = 1213467 },        }
    },
    [1862] = {
        name = "Finery of Infinite Wisdom",
        bonuses = {            [3] = { spellId = 1213708 },        }
    },
    [1863] = {
        name = "Emblems of Veiled Shadows",
        bonuses = {            [3] = { spellId = 1213763 },        }
    },
    [1864] = {
        name = "Gift of the Gathering Storm",
        bonuses = {            [3] = { spellId = 1213957 },        }
    },
    [1865] = {
        name = "Implements of Unspoken Names",
        tier = "an",
        bonuses = {            [3] = { spellId = 1214151 },        }
    },
    [1866] = {
        name = "Battlegear of Unyielding Strength",
        tier = "an",
        bonuses = {            [3] = { spellId = 1214165 },        }
    },
    [1881] = {
        name = "Kharon's Decree",
        bonuses = {            [2] = { spellId = 1219073 },        }
    },
    [1882] = {
        name = "Dreadnaught's Battlegear",
        bonuses = {            [2] = { spellId = 1219540 },            [4] = { spellId = 1219543 },            [6] = { spellId = 1219544 },        }
    },
    [1883] = {
        name = "Dreadnaught's Warplate",
        bonuses = {            [2] = { spellId = 1219481 },            [4] = { spellId = 1219483 },            [6] = { spellId = 1219486 },        }
    },
    [1884] = {
        name = "Plagueheart Stitchings",
        tier = "an",
        bonuses = {            [2] = { spellId = 1219474 },            [4] = { spellId = 1219476 },            [6] = { spellId = 1219479 },        }
    },
    [1885] = {
        name = "Plagueheart Raiment",
        bonuses = {            [2] = { spellId = 1219421 },            [4] = { spellId = 1219423 },            [6] = { spellId = 1219462 },        }
    },
    [1886] = {
        name = "The Earthshatterer's Resolve",
        tier = "an",
        bonuses = {            [2] = { spellId = 1219382 },            [4] = { spellId = 1219413 },            [6] = { spellId = 1219414 },        }
    },
    [1887] = {
        name = "The Earthshatterer",
        bonuses = {            [2] = { spellId = 1219361 },            [4] = { spellId = 1219364 },            [6] = { spellId = 1219365 },        }
    },
    [1888] = {
        name = "The Earthshatterer's Rage",
        bonuses = {            [2] = { spellId = 1219373 },            [4] = { spellId = 1219374 },            [6] = { spellId = 1219376 },        }
    },
    [1889] = {
        name = "The Earthshatterer's Storm",
        bonuses = {            [2] = { spellId = 1219367 },            [4] = { spellId = 1219368 },            [6] = { spellId = 1219369 },        }
    },
    [1890] = {
        name = "Bonescythe Leathers",
        tier = "an",
        bonuses = {            [2] = { spellId = 1219356 },            [4] = { spellId = 1219358 },            [6] = { spellId = 1219359 },        }
    },
    [1891] = {
        name = "Bonescythe Armor",
        bonuses = {            [2] = { spellId = 1219260 },            [4] = { spellId = 1219286 },            [6] = { spellId = 1219293 },        }
    },
    [1892] = {
        name = "Vestments of Faith",
        bonuses = {            [2] = { spellId = 1219230 },            [4] = { spellId = 1219233 },            [6] = { spellId = 1219238 },        }
    },
    [1893] = {
        name = "Raiments of Faith",
        bonuses = {            [2] = { spellId = 1219242 },            [4] = { spellId = 1219244 },            [6] = { spellId = 1219250 },        }
    },
    [1894] = {
        name = "Redemption Bulwark",
        bonuses = {            [2] = { spellId = 1219205 },            [4] = { spellId = 1219225 },            [6] = { spellId = 1219226 },        }
    },
    [1895] = {
        name = "Redemption Armor",
        bonuses = {            [2] = { spellId = 1219010 },            [4] = { spellId = 1219059 },            [6] = { spellId = 1219098 },        }
    },
    [1896] = {
        name = "Redemption Warplate",
        bonuses = {            [2] = { spellId = 1219189 },            [4] = { spellId = 1219191 },            [6] = { spellId = 1219193 },        }
    },
    [1897] = {
        name = "Frostfire Vestments",
        bonuses = {            [2] = { spellId = 1218592 },            [4] = { spellId = 1218693 },            [6] = { spellId = 1218697 },        }
    },
    [1898] = {
        name = "Frostfire Regalia",
        bonuses = {            [2] = { spellId = 1218993 },            [4] = { spellId = 1218700 },            [6] = { spellId = 1218995 },        }
    },
    [1899] = {
        name = "Cryptstalker Armor",
        bonuses = {            [2] = { spellId = 1218515 },            [4] = { spellId = 1218514 },            [6] = { spellId = 1218575 },        }
    },
    [1900] = {
        name = "Cryptstalker Prowess",
        bonuses = {            [2] = { spellId = 1218582 },            [4] = { spellId = 1218583 },            [6] = { spellId = 1218589 },        }
    },
    [1901] = {
        name = "Dreamwalker Guardian",
        bonuses = {            [2] = { spellId = 1218482 },            [4] = { spellId = 1218507 },            [6] = { spellId = 1218509 },        }
    },
    [1902] = {
        name = "Dreamwalker Raiment",
        bonuses = {            [2] = { spellId = 1218423 },            [4] = { spellId = 1218427 },            [6] = { spellId = 1218429 },        }
    },
    [1903] = {
        name = "Dreamwalker Ferocity",
        bonuses = {            [2] = { spellId = 1218476 },            [4] = { spellId = 1218477 },            [6] = { spellId = 1218478 },        }
    },
    [1904] = {
        name = "Dreamwalker Eclipse",
        bonuses = {            [2] = { spellId = 1218443 },            [4] = { spellId = 1218444 },            [6] = { spellId = 1218445 },        }
    },
    [1905] = {
        name = "Undead Slayer's Armor",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1906] = {
        name = "Garb of the Undead Slayer",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1907] = {
        name = "Battlegear of Undead Slaying",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1908] = {
        name = "Regalia of Undead Cleansing",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1909] = {
        name = "Battlegear of Undead Warding",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1910] = {
        name = "Battlegear of Undead Purification",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1911] = {
        name = "Garb of the Undead Cleansing",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1912] = {
        name = "Garb of the Undead Warder",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1913] = {
        name = "Garb of the Undead Purifier",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1914] = {
        name = "Undead Cleanser's Armor",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1915] = {
        name = "Undead Purifier's Armor",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1916] = {
        name = "Undead Warder's Armor",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1917] = {
        name = "Regalia of Undead Purification",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1918] = {
        name = "Regalia of Undead Warding",
        bonuses = {            [2] = { spellId = 1223336 },        }
    },
    [1932] = {
        name = "Lightbreaker's Warplate",
        bonuses = {            [2] = { spellId = 1227231 },            [4] = { spellId = 1227232 },            [6] = { spellId = 1227234 },        }
    },
    [1933] = {
        name = "Lightbreaker's Battlegear",
        bonuses = {            [2] = { spellId = 1227237 },            [4] = { spellId = 1227242 },            [6] = { spellId = 1227245 },        }
    },
    [1934] = {
        name = "Duskwraith Armor",
        bonuses = {            [2] = { spellId = 1226843 },            [4] = { spellId = 1226869 },            [6] = { spellId = 1226871 },        }
    },
    [1935] = {
        name = "Duskwraith Leathers",
        tier = "an",
        bonuses = {            [2] = { spellId = 1226874 },            [4] = { spellId = 1226882 },            [6] = { spellId = 1226956 },        }
    },
    [1936] = {
        name = "Dawnstalker Prowess",
        bonuses = {            [2] = { spellId = 1226340 },            [4] = { spellId = 1226359 },            [6] = { spellId = 1226365 },        }
    },
    [1937] = {
        name = "Dawnstalker Armor",
        bonuses = {            [2] = { spellId = 1226132 },            [4] = { spellId = 1226137 },            [6] = { spellId = 1226138 },        }
    },
    [1938] = {
        name = "Raiments of Revelation",
        bonuses = {            [2] = { spellId = 1226585 },            [4] = { spellId = 1226591 },            [6] = { spellId = 1226595 },        }
    },
    [1939] = {
        name = "Vestments of Revelation",
        bonuses = {            [2] = { spellId = 1226499 },            [4] = { spellId = 1226565 },            [6] = { spellId = 1226501 },        }
    },
    [1940] = {
        name = "Inquisition Warplate",
        bonuses = {            [2] = { spellId = 1226460 },            [4] = { spellId = 1226462 },            [6] = { spellId = 1226463 },        }
    },
    [1941] = {
        name = "Inquisition Armor",
        bonuses = {            [2] = { spellId = 1226452 },            [4] = { spellId = 1226454 },            [6] = { spellId = 1226459 },        }
    },
    [1942] = {
        name = "Inquisition Bulwark",
        bonuses = {            [2] = { spellId = 1226467 },            [4] = { spellId = 1226477 },            [6] = { spellId = 1226479 },        }
    },
    [1943] = {
        name = "Fireleaf Regalia",
        bonuses = {            [2] = { spellId = 1226423 },            [4] = { spellId = 1226446 },            [6] = { spellId = 1226432 },        }
    },
    [1944] = {
        name = "Fireleaf Vestments",
        bonuses = {            [2] = { spellId = 1226407 },            [4] = { spellId = 1226415 },            [6] = { spellId = 1226378 },        }
    },
    [1945] = {
        name = "Waywatcher Ferocity",
        bonuses = {            [2] = { spellId = 1226109 },            [4] = { spellId = 1226116 },            [6] = { spellId = 1226119 },        }
    },
    [1946] = {
        name = "Waywatcher Eclipse",
        bonuses = {            [2] = { spellId = 1226092 },            [4] = { spellId = 1226103 },            [6] = { spellId = 1226108 },        }
    },
    [1947] = {
        name = "Waywatcher Raiment",
        bonuses = {            [2] = { spellId = 1226032 },            [4] = { spellId = 1226040 },            [6] = { spellId = 1226044 },        }
    },
    [1948] = {
        name = "Waywatcher Guardian",
        bonuses = {            [2] = { spellId = 1226121 },            [4] = { spellId = 1226125 },            [6] = { spellId = 1226126 },        }
    },
    [1949] = {
        name = "The Soulcrusher's Resolve",
        tier = "an",
        bonuses = {            [2] = { spellId = 1227153 },            [4] = { spellId = 1227159 },            [6] = { spellId = 1227164 },        }
    },
    [1950] = {
        name = "The Soulcrusher",
        bonuses = {            [2] = { spellId = 1227093 },            [4] = { spellId = 1227099 },            [6] = { spellId = 1227111 },        }
    },
    [1951] = {
        name = "The Soulcrusher's Rage",
        bonuses = {            [2] = { spellId = 1226984 },            [4] = { spellId = 1226986 },            [6] = { spellId = 1226997 },        }
    },
    [1952] = {
        name = "The Soulcrusher's Storm",
        bonuses = {            [2] = { spellId = 1226961 },            [4] = { spellId = 1226977 },            [6] = { spellId = 1226978 },        }
    },
    [1953] = {
        name = "Heretic Stitchings",
        tier = "an",
        bonuses = {            [2] = { spellId = 1227214 },            [4] = { spellId = 1227204 },            [6] = { spellId = 1227228 },        }
    },
    [1954] = {
        name = "Heretic Raiment",
        bonuses = {            [2] = { spellId = 1227175 },            [4] = { spellId = 1227186 },            [6] = { spellId = 1227196 },        }
    },
    [1955] = {
        name = "Fallen Regality",
        bonuses = {            [2] = { spellId = 1232184 },        }
    },
    [1956] = {
        name = "Tools of the Nathrezim",
        bonuses = {            [2] = { spellId = 1231556 },        }
    },
    [1959] = {
        name = "Hack and Smash",
        bonuses = {            [2] = { spellId = 1234318 },        }
    },
    [1963] = {
        name = "Inquisition Shockplate",
        bonuses = {            [2] = { spellId = 1240571 },            [4] = { spellId = 1226462 },            [6] = { spellId = 1240573 },        }
    },
}