SLASH_BINDINGS1 = "/fix_bindings"
SLASH_BINDINGS2 = "/fb"
SlashCmdList["BINDINGS"] = FixBindings

local function FixBindings()
	SetBinding("A", "STRAFELEFT")
	SetBinding("D", "STRAFERIGHT")
	SetBinding("Q", "TOGGLEAUTORUN")
	SetBinding("E", "ACTIONBUTTON11")
	SetBinding("X", "MULTIACTIONBAR1BUTTON6")
	SetBinding("BUTTON4", "MULTIACTIONBAR2BUTTON4")
	SetBinding("PAGEUP", "CAMERAZOOMIN")
	SetBinding("PAGEDOWN", "CAMERAZOOMOUT")
	SetBinding("6", "NONE")
	SetBinding("7", "NONE")
	SetBinding("8", "NONE")
	SetBinding("9", "NONE")
	SetBinding("0", "NONE")
	SetBinding("-", "NONE")
	SetBinding("=", "NONE")
	SetBinding("CTRL-1", "NONE")
	SetBinding("CTRL-2", "NONE")
	SetBinding("CTRL-3", "NONE")
	SetBinding("CTRL-4", "NONE")
	SetBinding("CTRL-5", "NONE")
	SetBinding("CTRL-6", "NONE")
	SetBinding("CTRL-7", "NONE")
	SetBinding("CTRL-8", "NONE")
	SetBinding("CTRL-9", "NONE")
	SetBinding("CTRL-0", "NONE")
	SetBinding("SHIFT-1", "MULTIACTIONBAR4BUTTON1")
	SetBinding("SHIFT-2", "MULTIACTIONBAR4BUTTON2")
	SetBinding("SHIFT-3", "MULTIACTIONBAR4BUTTON3")
	SetBinding("SHIFT-4", "MULTIACTIONBAR4BUTTON4")
	SetBinding("SHIFT-5", "MULTIACTIONBAR4BUTTON5")
	SetBinding("SHIFT-6", "NONE")
	SetBinding("SHIFT-UP", "NONE")
	SetBinding("SHIFT-MOUSEWHEELUP", "ACTIONBUTTON8")
	SetBinding("SHIFT-DOWN", "NONE")
	SetBinding("SHIFT-MOUSEWHEELDOWN", "NONE")
	SetBinding("TAB", "ACTIONBUTTON10")
	SetBinding("F1", "MULTIACTIONBAR3BUTTON1")
	SetBinding("F2", "MULTIACTIONBAR3BUTTON2")
	SetBinding("F3", "MULTIACTIONBAR3BUTTON3")
	SetBinding("F4", "MULTIACTIONBAR3BUTTON4")
	SetBinding("F5", "MULTIACTIONBAR3BUTTON5")
	SetBinding("G", "MULTIACTIONBAR1BUTTON3")
	SetBinding("F", "ACTIONBUTTON12")
	SetBinding("V", "MULTIACTIONBAR1BUTTON2")
	SetBinding("SHIFT-V", "NONE")
	SetBinding("CTRL-V", "NONE")
	SetBinding("T", "MULTIACTIONBAR1BUTTON4")
	SetBinding("SHIFT-T", "MULTIACTIONBAR1BUTTON5")
	SetBinding("B", "OPENALLBAGS")
	SetBinding("SHIFT-B", "BAGNON_BANK_TOGGLE")
	SetBinding("F12", "NONE")
	SetBinding("SHIFT-I", "EXAMINER_MOUSEOVER")
	SetBinding("H", "MULTIACTIONBAR1BUTTON1")
	SetBinding("K", "EXTRAACTIONBUTTON1")
	SetBinding("L", "MONKEYQUEST_CLOSE")
	SetBinding("CTRL-M", "NONE")
	SetBinding("CTRL-S", "NONE")
	SetBinding("MOUSEWHEELUP", "MULTIACTIONBAR2BUTTON2")
	SetBinding("MOUSEWHEELDOWN", "MULTIACTIONBAR2BUTTON1")
	SetBinding("CTRL-R", "TOGGLEGROUPFINDER")
	SetBinding("CTRL-Y", "TOGGLEACHIEVEMENT")
	SetBinding("CTRL-Q", "NONE")
	SetBinding("CTRL-T", "INTERACTTARGET")
	SetBinding("CTRL-A", "ATTACKTARGET")
	SetBinding("CTRL-B", "MULTIACTIONBAR4BUTTON8")
	SetBinding("I", "EXAMINER_TARGET")
	SetBinding("CTRL-I", "TOGGLELFGPARENT")
	SetBinding("Y", "NONE")
	SetBinding("J", "NONE")
	SetBinding("ALT-P", "TOGGLEPERFORMANCEDISPLAY")
	SetBinding("SHIFT-G", "NONE")
	SetBinding("SHIFT-S", "MULTIACTIONBAR3BUTTON12")
	SetBinding("F7", "MULTIACTIONBAR3BUTTON7")
	SetBinding("¸", "TARGETNEARESTENEMY")
	SetBinding("ALT-S", "MULTIACTIONBAR3BUTTON11")
	SetBinding("SHIFT-F", "NONE")
	SetBinding("SHIFT-D", "NONE")
	SetBinding("SHIFT-E", "NONE")
	SetBinding("ALT-D", "NONE")
	SetBinding("BUTTON5", "MULTIACTIONBAR2BUTTON3")
	SetBinding("CTRL-X", "AutoBarButtonHeal_X")
	SetBinding("CTRL-H", "TOGGLECHARACTER4")
	SetBinding("CTRL-F", "FOLLOWTARGET")
	SetBinding("ALT-F1", "NONE")
	SetBinding("ALT-F2", "NONE")
	SetBinding("ALT-F3", "NONE")
	SetBinding("F6", "MULTIACTIONBAR3BUTTON6")
	SetBinding("SHIFT-K", "BAGNON_KEYS_TOGGLE")
	SetBinding("CTRL-SHIFT-V", "NAMEPLATES")
	SetBinding("ALT-1", "BONUSACTIONBUTTON1")
	SetBinding("ALT-2", "BONUSACTIONBUTTON2")
	SetBinding("ALT-3", "BONUSACTIONBUTTON3")
	SetBinding("ALT-MOUSEWHEELUP", "ACTIONBUTTON7")
	SetBinding("ALT-X", "NONE")
	SetBinding("ALT-R", "NONE")
	SetBinding("CTRL-D", "MULTIACTIONBAR4BUTTON9")
	SetBinding("ALT-4", "NONE")
	SetBinding("ALT-5", "NONE")
	SetBinding("ALT-6", "NONE")
	SetBinding("CTRL-SHIFT-M", "TOGGLEMOUNTJOURNAL")
	SetBinding("CTRL-SHIFT-C", "TOGGLECOMPANIONJOURNAL")
	SetBinding("CTRL-SHIFT-P", "TOGGLEPETJOURNAL")
	SetBinding("CTRL-SHIFT-R", "TOGGLEFPS")
	SetBinding("CTRL-G", "NONE")
	SetBinding("SHIFT-7", "NONE")
	SetBinding("SHIFT-8", "NONE")
	SetBinding("SHIFT-9", "NONE")
	SetBinding("CTRL-F12", "NONE")
	SetBinding("CTRL-SHIFT-B", "NONE")
	SetBinding("CTRL-+", "TOGGLESOUND")
	SetBinding("CTRL-L", "NONE")
	SetBinding("SHIFT-'", "CLICK TopAbyssUIClassic_InspectTarget:LeftButton")
	SetBinding("CTRL-'", "CLICK TopAbyssUIClassic_ConfirmPopUps:LeftButton")
	SetBinding("SHIFT-C", "CLICK BT4Button21:LeftButton")
	SetBinding("SHIFT-R", "CLICK BT4Button22:LeftButton")
	SetBinding("ALT-E", "CLICK BT4Button39:LeftButton")
	SetBinding("ALT-MOUSEWHEELDOWN", "CLICK BT4Button112:LeftButton")
end

local f = CreateFrame("Frame")
f:SetScript("OnEvent", FixBindings())
f:RegisterEvent("PLAYER_LOGIN")
