-- Generated by NextActionGuide Data Generator
-- Product: Classic Titan
-- Build: 3.80.0.64859
-- Generated: 2025-12-10 22:28:15

local _, ns = ...
ns.data = ns.data or {}
ns.data.wrath = ns.data.wrath or {}

ns.data.wrath.TierSets = {
    [1] = {
        name = "The Gladiator",
        bonuses = {            [2] = { spellId = 41863 },            [3] = { spellId = 41864 },            [4] = { spellId = 41861 },            [5] = { spellId = 41862 },        }
    },
    [41] = {
        name = "Dal'Rend's Arms",
        bonuses = {            [2] = { spellId = 41719 },        }
    },
    [65] = {
        name = "Spider's Kiss",
        bonuses = {            [2] = { spellId = 17332 },        }
    },
    [81] = {
        name = "The Postmaster",
        bonuses = {            [2] = { spellId = 41873 },            [3] = { spellId = { 41870, 41871 } },            [4] = { spellId = 41872 },            [5] = { spellId = { 41869, 17498 } },        }
    },
    [121] = {
        name = "Cadaverous Garb",
        bonuses = {            [2] = { spellId = 41681 },            [3] = { spellId = 41645 },            [4] = { spellId = 41680 },            [5] = { spellId = 41679 },        }
    },
    [122] = {
        name = "Necropile Raiment",
        bonuses = {            [2] = { spellId = 41642 },            [3] = { spellId = 41827 },            [4] = { spellId = 41826 },            [5] = { spellId = 41825 },        }
    },
    [123] = {
        name = "Bloodmail Regalia",
        bonuses = {            [2] = { spellId = 41671 },            [3] = { spellId = 41672 },            [4] = { spellId = 41673 },            [5] = { spellId = 41674 },        }
    },
    [124] = {
        name = "Deathbone Guardian",
        bonuses = {            [2] = { spellId = 41726 },            [3] = { spellId = 41725 },            [4] = { spellId = 41724 },            [5] = { spellId = 41723 },        }
    },
    [141] = {
        name = "Volcanic Armor",
        bonuses = {            [3] = { spellId = 9233 },        }
    },
    [142] = {
        name = "Stormshroud Armor",
        bonuses = {            [2] = { spellId = 18979 },            [3] = { spellId = 23863 },            [4] = { spellId = 41845 },        }
    },
    [143] = {
        name = "Devilsaur Armor",
        bonuses = {            [2] = { spellId = 39516 },        }
    },
    [144] = {
        name = "Ironfeather Armor",
        bonuses = {            [2] = { spellId = 41780 },        }
    },
    [161] = {
        name = "Defias Leather",
        bonuses = {            [2] = { spellId = 41731 },            [3] = { spellId = 41732 },            [4] = { spellId = 41730 },            [5] = { spellId = 41733 },        }
    },
    [162] = {
        name = "Embrace of the Viper",
        bonuses = {            [2] = { spellId = 41740 },            [3] = { spellId = 41739 },            [4] = { spellId = 41644 },            [5] = { spellId = 41741 },        }
    },
    [163] = {
        name = "Chain of the Scarlet Crusade",
        bonuses = {            [2] = { spellId = 41686 },            [3] = { spellId = 41641 },            [4] = { spellId = 41685 },            [5] = { spellId = 41684 },            [6] = { spellId = 41683 },        }
    },
    [181] = {
        name = "Magister's Regalia",
        bonuses = {            [2] = { spellId = 29091 },            [4] = { spellId = 30777 },            [6] = { spellId = 27867 },            [8] = { spellId = 41822 },        }
    },
    [182] = {
        name = "Vestments of the Devout",
        bonuses = {            [2] = { spellId = 41881 },            [4] = { spellId = 41879 },            [6] = { spellId = 27778 },            [8] = { spellId = 41880 },        }
    },
    [183] = {
        name = "Dreadmist Raiment",
        bonuses = {            [2] = { spellId = 41738 },            [4] = { spellId = 41736 },            [6] = { spellId = 27780 },            [8] = { spellId = 41737 },        }
    },
    [184] = {
        name = "Shadowcraft Armor",
        bonuses = {            [2] = { spellId = 29096 },            [4] = { spellId = 41835 },            [6] = { spellId = 27787 },            [8] = { spellId = 41836 },        }
    },
    [185] = {
        name = "Wildheart Raiment",
        bonuses = {            [2] = { spellId = 29097 },            [4] = { spellId = { 41892, 41891 } },            [6] = { spellId = 27781 },            [8] = { spellId = 41893 },        }
    },
    [186] = {
        name = "Beaststalker Armor",
        bonuses = {            [2] = { spellId = 29094 },            [4] = { spellId = 30772 },            [6] = { spellId = 27785 },            [8] = { spellId = 41668 },        }
    },
    [187] = {
        name = "The Elements",
        bonuses = {            [2] = { spellId = 29095 },            [4] = { spellId = 41856 },            [6] = { spellId = 27774 },            [8] = { spellId = 41857 },        }
    },
    [188] = {
        name = "Lightforge Armor",
        bonuses = {            [2] = { spellId = 29093 },            [4] = { spellId = 41818 },            [6] = { spellId = 27498 },            [8] = { spellId = 41819 },        }
    },
    [189] = {
        name = "Battlegear of Valor",
        bonuses = {            [2] = { spellId = 29092 },            [4] = { spellId = 30770 },            [6] = { spellId = 27419 },            [8] = { spellId = 18679 },        }
    },
    [201] = {
        name = "Arcanist Regalia",
        bonuses = {            [3] = { spellId = 41657 },            [5] = { spellId = 41656 },            [8] = { spellId = 23545 },        }
    },
    [202] = {
        name = "Vestments of Prophecy",
        bonuses = {            [3] = { spellId = 21973 },            [5] = { spellId = 21092 },            [8] = { spellId = 23550 },        }
    },
    [203] = {
        name = "Felheart Raiment",
        bonuses = {            [3] = { spellId = 23554 },            [5] = { spellId = 21741 },            [8] = { spellId = 23553 },        }
    },
    [204] = {
        name = "Nightslayer Armor",
        bonuses = {            [3] = { spellId = 21874 },            [5] = { spellId = 21975 },            [8] = { spellId = 23582 },        }
    },
    [205] = {
        name = "Cenarion Raiment",
        bonuses = {            [3] = { spellId = 23557 },            [5] = { spellId = 39507 },            [8] = { spellId = 23556 },        }
    },
    [206] = {
        name = "Giantstalker Armor",
        bonuses = {            [3] = { spellId = 23560 },            [5] = { spellId = 21926 },            [8] = { spellId = 23566 },        }
    },
    [207] = {
        name = "The Earthfury",
        bonuses = {            [3] = { spellId = 21895 },            [5] = { spellId = 23572 },            [8] = { spellId = 23573 },        }
    },
    [208] = {
        name = "Lawbringer Armor",
        bonuses = {            [3] = { spellId = 23564 },            [5] = { spellId = 41784 },            [8] = { spellId = 21747 },        }
    },
    [209] = {
        name = "Battlegear of Might",
        bonuses = {            [3] = { spellId = 23562 },            [5] = { spellId = 21838 },            [8] = { spellId = 23561 },        }
    },
    [210] = {
        name = "Netherwind Regalia",
        bonuses = {            [3] = { spellId = 21879 },            [5] = { spellId = 23549 },            [8] = { spellId = 22007 },        }
    },
    [211] = {
        name = "Vestments of Transcendence",
        bonuses = {            [3] = { spellId = 21894 },            [5] = { spellId = 21853 },            [8] = { spellId = 22010 },        }
    },
    [212] = {
        name = "Nemesis Raiment",
        bonuses = {            [3] = { spellId = 32449 },            [5] = { spellId = 21922 },            [8] = { spellId = 23555 },        }
    },
    [213] = {
        name = "Bloodfang Armor",
        bonuses = {            [3] = { spellId = 21881 },            [5] = { spellId = 23558 },            [8] = { spellId = 23581 },        }
    },
    [214] = {
        name = "Stormrage Raiment",
        bonuses = {            [3] = { spellId = 21894 },            [5] = { spellId = 21872 },            [8] = { spellId = 21871 },        }
    },
    [215] = {
        name = "Dragonstalker Armor",
        bonuses = {            [3] = { spellId = 23559 },            [5] = { spellId = 21928 },            [8] = { spellId = 23578 },        }
    },
    [216] = {
        name = "The Ten Storms",
        bonuses = {            [3] = { spellId = 21899 },            [5] = { spellId = 23570 },            [8] = { spellId = 23551 },        }
    },
    [217] = {
        name = "Judgement Armor",
        bonuses = {            [3] = { spellId = 23565 },            [5] = { spellId = 41782 },            [8] = { spellId = 23591 },        }
    },
    [218] = {
        name = "Battlegear of Wrath",
        bonuses = {            [3] = { spellId = 23563 },            [5] = { spellId = 21890 },            [8] = { spellId = 23548 },        }
    },
    [221] = {
        name = "Garb of Thero-shan",
        bonuses = {            [6] = { spellId = 41772 },        }
    },
    [241] = {
        name = "Shard of the Gods",
        bonuses = {            [2] = { spellId = 41838 },        }
    },
    [261] = {
        name = "Spirit of Eskhandar",
        bonuses = {            [2] = { spellId = 22648 },        }
    },
    [281] = {
        name = "Champion's Battlegear",
        bonuses = {            [2] = { spellId = 41690 },            [4] = { spellId = 22738 },            [6] = { spellId = 41653 },        }
    },
    [282] = {
        name = "Lieutenant Commander's Battlegear",
        bonuses = {            [2] = { spellId = 41793 },            [4] = { spellId = 22738 },            [6] = { spellId = 41792 },        }
    },
    [301] = {
        name = "Champion's Earthshaker",
        bonuses = {            [2] = { spellId = 41693 },            [4] = { spellId = 22804 },            [6] = { spellId = 41692 },        }
    },
    [321] = {
        name = "Imperial Plate",
        bonuses = {            [2] = { spellId = 41779 },            [4] = { spellId = 41647 },            [6] = { spellId = 41778 },        }
    },
    [341] = {
        name = "Champion's Regalia",
        bonuses = {            [2] = { spellId = 41709 },            [4] = { spellId = 23025 },            [6] = { spellId = 41708 },        }
    },
    [342] = {
        name = "Champion's Raiment",
        bonuses = {            [2] = { spellId = 41703 },            [4] = { spellId = 23044 },            [6] = { spellId = 41702 },        }
    },
    [343] = {
        name = "Lieutenant Commander's Regalia",
        bonuses = {            [2] = { spellId = 41811 },            [4] = { spellId = 23025 },            [6] = { spellId = 41810 },        }
    },
    [344] = {
        name = "Lieutenant Commander's Raiment",
        bonuses = {            [2] = { spellId = 41805 },            [4] = { spellId = 23044 },            [6] = { spellId = 41804 },        }
    },
    [345] = {
        name = "Champion's Threads",
        bonuses = {            [2] = { spellId = 41715 },            [4] = { spellId = 23047 },            [6] = { spellId = 41714 },        }
    },
    [346] = {
        name = "Lieutenant Commander's Threads",
        bonuses = {            [2] = { spellId = 41815 },            [4] = { spellId = 23047 },            [6] = { spellId = 41814 },        }
    },
    [347] = {
        name = "Champion's Vestments",
        bonuses = {            [2] = { spellId = 41717 },            [4] = { spellId = 23048 },            [6] = { spellId = 41716 },        }
    },
    [348] = {
        name = "Lieutenant Commander's Vestments",
        bonuses = {            [2] = { spellId = 41817 },            [4] = { spellId = 23048 },            [6] = { spellId = 41816 },        }
    },
    [361] = {
        name = "Champion's Pursuit",
        bonuses = {            [2] = { spellId = 41701 },            [4] = { spellId = 23158 },            [6] = { spellId = 41700 },        }
    },
    [362] = {
        name = "Lieutenant Commander's Pursuit",
        bonuses = {            [2] = { spellId = 41803 },            [4] = { spellId = 23158 },            [6] = { spellId = 41802 },        }
    },
    [381] = {
        name = "Lieutenant Commander's Sanctuary",
        bonuses = {            [2] = { spellId = 41813 },            [4] = { spellId = 23218 },            [6] = { spellId = 41812 },        }
    },
    [382] = {
        name = "Champion's Sanctuary",
        bonuses = {            [2] = { spellId = 41711 },            [4] = { spellId = 23218 },            [6] = { spellId = 41710 },        }
    },
    [383] = {
        name = "Warlord's Battlegear",
        bonuses = {            [2] = { spellId = 41887 },            [3] = { spellId = 22738 },            [6] = { spellId = 41888 },        }
    },
    [384] = {
        name = "Field Marshal's Battlegear",
        bonuses = {            [2] = { spellId = 41756 },            [3] = { spellId = 22738 },            [6] = { spellId = 41755 },        }
    },
    [386] = {
        name = "Warlord's Earthshaker",
        bonuses = {            [2] = { spellId = 41896 },            [3] = { spellId = 22804 },            [6] = { spellId = 41895 },        }
    },
    [387] = {
        name = "Warlord's Regalia",
        bonuses = {            [2] = { spellId = 41901 },            [3] = { spellId = 23025 },            [6] = { spellId = 41902 },        }
    },
    [388] = {
        name = "Field Marshal's Regalia",
        bonuses = {            [2] = { spellId = 41761 },            [3] = { spellId = 23025 },            [6] = { spellId = 41762 },        }
    },
    [389] = {
        name = "Field Marshal's Raiment",
        bonuses = {            [2] = { spellId = 41759 },            [3] = { spellId = 23044 },            [6] = { spellId = 41760 },        }
    },
    [390] = {
        name = "Warlord's Raiment",
        bonuses = {            [2] = { spellId = 41899 },            [3] = { spellId = 23044 },            [6] = { spellId = 41900 },        }
    },
    [391] = {
        name = "Warlord's Threads",
        bonuses = {            [2] = { spellId = 41906 },            [3] = { spellId = 23047 },            [6] = { spellId = 41905 },        }
    },
    [392] = {
        name = "Field Marshal's Threads",
        bonuses = {            [2] = { spellId = 41765 },            [3] = { spellId = 23047 },            [6] = { spellId = 41766 },        }
    },
    [393] = {
        name = "Warlord's Vestments",
        bonuses = {            [2] = { spellId = 41908 },            [3] = { spellId = 23048 },            [6] = { spellId = 41907 },        }
    },
    [394] = {
        name = "Field Marshal's Vestments",
        bonuses = {            [2] = { spellId = 41767 },            [3] = { spellId = 23048 },            [6] = { spellId = 41768 },        }
    },
    [395] = {
        name = "Field Marshal's Pursuit",
        bonuses = {            [2] = { spellId = 41757 },            [3] = { spellId = 23158 },            [6] = { spellId = 41758 },        }
    },
    [396] = {
        name = "Warlord's Pursuit",
        bonuses = {            [2] = { spellId = 41898 },            [3] = { spellId = 23158 },            [6] = { spellId = 41897 },        }
    },
    [397] = {
        name = "Field Marshal's Sanctuary",
        bonuses = {            [2] = { spellId = 41764 },            [3] = { spellId = 23218 },            [6] = { spellId = 41763 },        }
    },
    [398] = {
        name = "Warlord's Sanctuary",
        bonuses = {            [2] = { spellId = 41903 },            [3] = { spellId = 23218 },            [6] = { spellId = 41904 },        }
    },
    [401] = {
        name = "Lieutenant Commander's Aegis",
        bonuses = {            [2] = { spellId = { 41636, 41787 } },            [4] = { spellId = 23302 },            [6] = { spellId = 41786 },        }
    },
    [402] = {
        name = "Field Marshal's Aegis",
        bonuses = {            [2] = { spellId = 41754 },            [3] = { spellId = 23302 },            [6] = { spellId = 41753 },        }
    },
    [421] = {
        name = "Bloodvine Garb",
        bonuses = {            [3] = { spellId = 41676 },        }
    },
    [441] = {
        name = "Primal Batskin",
        bonuses = {            [3] = { spellId = 24090 },        }
    },
    [442] = {
        name = "Blood Tiger Harness",
        bonuses = {            [2] = { spellId = { 41650, 41670 } },        }
    },
    [443] = {
        name = "Bloodsoul Embrace",
        bonuses = {            [3] = { spellId = 41675 },        }
    },
    [444] = {
        name = "The Darksoul",
        bonuses = {            [3] = { spellId = 41847 },        }
    },
    [461] = {
        name = "The Twin Blades of Hakkari",
        bonuses = {            [2] = { spellId = 41874 },        }
    },
    [462] = {
        name = "Zanzil's Concentration",
        bonuses = {            [2] = { spellId = { 41894, 39702 } },        }
    },
    [463] = {
        name = "Primal Blessing",
        bonuses = {            [2] = { spellId = 24256 },        }
    },
    [464] = {
        name = "Overlord's Resolution",
        bonuses = {            [2] = { spellId = 39880 },        }
    },
    [465] = {
        name = "Prayer of the Primal",
        bonuses = {            [2] = { spellId = 41830 },        }
    },
    [466] = {
        name = "Major Mojo Infusion",
        bonuses = {            [2] = { spellId = 41823 },        }
    },
    [467] = {
        name = "The Highlander's Resolution",
        bonuses = {            [2] = { spellId = 41868 },            [3] = { spellId = 39548 },        }
    },
    [468] = {
        name = "The Highlander's Resolve",
        bonuses = {            [2] = { spellId = 41640 },            [3] = { spellId = 41041 },        }
    },
    [469] = {
        name = "The Highlander's Determination",
        bonuses = {            [2] = { spellId = 41865 },            [3] = { spellId = 39418 },        }
    },
    [470] = {
        name = "The Highlander's Fortitude",
        bonuses = {            [2] = { spellId = 41638 },            [3] = { spellId = 39447 },        }
    },
    [471] = {
        name = "The Highlander's Purpose",
        bonuses = {            [2] = { spellId = 41867 },            [3] = { spellId = 39433 },        }
    },
    [472] = {
        name = "The Highlander's Will",
        bonuses = {            [2] = { spellId = 41639 },            [3] = { spellId = 39420 },        }
    },
    [473] = {
        name = "The Highlander's Intent",
        bonuses = {            [2] = { spellId = 41866 },            [3] = { spellId = 39422 },        }
    },
    [474] = {
        name = "Vindicator's Battlegear",
        bonuses = {            [2] = { spellId = 41885 },            [3] = { spellId = 24456 },            [5] = { spellId = 24431 },        }
    },
    [475] = {
        name = "Freethinker's Armor",
        bonuses = {            [2] = { spellId = 41770 },            [3] = { spellId = 24457 },            [5] = { spellId = 24460 },        }
    },
    [476] = {
        name = "Augur's Regalia",
        bonuses = {            [2] = { spellId = 41659 },            [3] = { spellId = 24461 },            [5] = { spellId = 24462 },        }
    },
    [477] = {
        name = "Predator's Armor",
        bonuses = {            [2] = { spellId = 41831 },            [3] = { spellId = 24465 },            [5] = { spellId = 24467 },        }
    },
    [478] = {
        name = "Madcap's Outfit",
        bonuses = {            [2] = { spellId = 41821 },            [3] = { spellId = 24469 },            [5] = { spellId = 24471 },        }
    },
    [479] = {
        name = "Haruspex's Garb",
        bonuses = {            [2] = { spellId = 41776 },            [3] = { spellId = 24479 },            [5] = { spellId = 24480 },        }
    },
    [480] = {
        name = "Confessor's Raiment",
        bonuses = {            [2] = { spellId = 41718 },            [3] = { spellId = 24482 },            [5] = { spellId = 24483 },        }
    },
    [481] = {
        name = "Demoniac's Threads",
        bonuses = {            [2] = { spellId = 41734 },            [3] = { spellId = 24486 },            [5] = { spellId = 24487 },        }
    },
    [482] = {
        name = "Illusionist's Attire",
        bonuses = {            [2] = { spellId = 41777 },            [3] = { spellId = 24489 },            [5] = { spellId = 24491 },        }
    },
    [483] = {
        name = "The Defiler's Determination",
        bonuses = {            [2] = { spellId = 41848 },            [3] = { spellId = 39884 },        }
    },
    [484] = {
        name = "The Defiler's Fortitude",
        bonuses = {            [2] = { spellId = 41849 },            [3] = { spellId = 41643 },        }
    },
    [485] = {
        name = "The Defiler's Intent",
        bonuses = {            [2] = { spellId = 41851 },            [3] = { spellId = 41850 },        }
    },
    [486] = {
        name = "The Defiler's Purpose",
        bonuses = {            [2] = { spellId = 41852 },            [3] = { spellId = 39545 },        }
    },
    [487] = {
        name = "The Defiler's Resolution",
        bonuses = {            [2] = { spellId = 41853 },            [3] = { spellId = 39486 },        }
    },
    [488] = {
        name = "The Defiler's Will",
        bonuses = {            [2] = { spellId = 41855 },            [3] = { spellId = 41854 },        }
    },
    [489] = {
        name = "Black Dragon Mail",
        bonuses = {            [2] = { spellId = 39510 },            [3] = { spellId = 39509 },            [4] = { spellId = 41669 },        }
    },
    [490] = {
        name = "Green Dragon Mail",
        bonuses = {            [2] = { spellId = 41775 },            [3] = { spellId = 21894 },        }
    },
    [491] = {
        name = "Blue Dragon Mail",
        bonuses = {            [2] = { spellId = 41677 },            [3] = { spellId = 41651 },        }
    },
    [492] = {
        name = "Twilight Trappings",
        bonuses = {            [3] = { spellId = 24746 },        }
    },
    [493] = {
        name = "Genesis Raiment",
        bonuses = {            [3] = { spellId = { 41774, 41773 } },            [5] = { spellId = 26106 },        }
    },
    [494] = {
        name = "Symbols of Unending Life",
        bonuses = {            [3] = { spellId = 26107 },        }
    },
    [495] = {
        name = "Battlegear of Unyielding Strength",
        bonuses = {            [3] = { spellId = 26111 },        }
    },
    [496] = {
        name = "Conqueror's Battlegear",
        bonuses = {            [3] = { spellId = 26109 },            [5] = { spellId = 26110 },        }
    },
    [497] = {
        name = "Deathdealer's Embrace",
        bonuses = {            [3] = { spellId = 26112 },            [5] = { spellId = 26113 },        }
    },
    [498] = {
        name = "Emblems of Veiled Shadows",
        bonuses = {            [3] = { spellId = 26114 },        }
    },
    [499] = {
        name = "Doomcaller's Attire",
        bonuses = {            [3] = { spellId = 26116 },            [5] = { spellId = 26117 },        }
    },
    [500] = {
        name = "Implements of Unspoken Names",
        bonuses = {            [3] = { spellId = 26118 },        }
    },
    [501] = {
        name = "Stormcaller's Garb",
        bonuses = {            [3] = { spellId = 26119 },            [5] = { spellId = 26122 },        }
    },
    [502] = {
        name = "Gift of the Gathering Storm",
        bonuses = {            [3] = { spellId = 26123 },        }
    },
    [503] = {
        name = "Enigma Vestments",
        bonuses = {            [3] = { spellId = 26127 },            [5] = { spellId = 26128 },        }
    },
    [504] = {
        name = "Trappings of Vaulted Secrets",
        bonuses = {            [3] = { spellId = 26131 },        }
    },
    [505] = {
        name = "Avenger's Battlegear",
        bonuses = {            [3] = { spellId = 26130 },            [5] = { spellId = 41648 },        }
    },
    [506] = {
        name = "Battlegear of Eternal Justice",
        bonuses = {            [3] = { spellId = 26135 },        }
    },
    [507] = {
        name = "Garments of the Oracle",
        bonuses = {            [3] = { spellId = 26169 },            [5] = { spellId = 26171 },        }
    },
    [508] = {
        name = "Finery of Infinite Wisdom",
        bonuses = {            [3] = { spellId = 26172 },        }
    },
    [509] = {
        name = "Striker's Garb",
        bonuses = {            [3] = { spellId = 26173 },            [5] = { spellId = 26174 },        }
    },
    [510] = {
        name = "Trappings of the Unseen Path",
        bonuses = {            [3] = { spellId = 26176 },        }
    },
    [511] = {
        name = "Battlegear of Heroism",
        bonuses = {            [2] = { spellId = 41662 },            [4] = { spellId = 27419 },            [6] = { spellId = 41649 },            [8] = { spellId = 41661 },        }
    },
    [512] = {
        name = "Darkmantle Armor",
        bonuses = {            [2] = { spellId = 41721 },            [4] = { spellId = 27787 },            [6] = { spellId = 41722 },            [8] = { spellId = 41720 },        }
    },
    [513] = {
        name = "Feralheart Raiment",
        bonuses = {            [2] = { spellId = 41751 },            [4] = { spellId = 27781 },            [6] = { spellId = { 41646, 41752 } },            [8] = { spellId = 41750 },        }
    },
    [514] = {
        name = "Vestments of the Virtuous",
        bonuses = {            [2] = { spellId = 41883 },            [4] = { spellId = 27778 },            [6] = { spellId = 41884 },            [8] = { spellId = 41882 },        }
    },
    [515] = {
        name = "Beastmaster Armor",
        bonuses = {            [2] = { spellId = 41666 },            [4] = { spellId = 27785 },            [6] = { spellId = 41667 },            [8] = { spellId = 41665 },        }
    },
    [516] = {
        name = "Soulforge Armor",
        bonuses = {            [2] = { spellId = 41843 },            [4] = { spellId = 27498 },            [6] = { spellId = 41844 },            [8] = { spellId = 41842 },        }
    },
    [517] = {
        name = "Sorcerer's Regalia",
        bonuses = {            [2] = { spellId = 41839 },            [4] = { spellId = 27867 },            [6] = { spellId = 32451 },            [8] = { spellId = 41840 },        }
    },
    [518] = {
        name = "Deathmist Raiment",
        bonuses = {            [2] = { spellId = 41728 },            [4] = { spellId = 27780 },            [6] = { spellId = 41729 },            [8] = { spellId = 41727 },        }
    },
    [519] = {
        name = "The Five Thunders",
        bonuses = {            [2] = { spellId = 41859 },            [4] = { spellId = 27774 },            [6] = { spellId = 41860 },            [8] = { spellId = 41858 },        }
    },
    [520] = {
        name = "Ironweave Battlesuit",
        bonuses = {            [4] = { spellId = 27733 },            [8] = { spellId = 41781 },        }
    },
    [521] = {
        name = "Dreamwalker Raiment",
        bonuses = {            [2] = { spellId = 28716 },            [4] = { spellId = 28743 },            [6] = { spellId = 28744 },            [8] = { spellId = 28719 },        }
    },
    [522] = {
        name = "Champion's Guard",
        bonuses = {            [2] = { spellId = 41695 },            [4] = { spellId = 23048 },            [6] = { spellId = 41694 },        }
    },
    [523] = {
        name = "Dreadnaught's Battlegear",
        bonuses = {            [2] = { spellId = 28844 },            [4] = { spellId = 28843 },            [6] = { spellId = 28842 },            [8] = { spellId = 28845 },        }
    },
    [524] = {
        name = "Bonescythe Armor",
        bonuses = {            [2] = { spellId = 28816 },            [4] = { spellId = 28812 },            [6] = { spellId = 28811 },            [8] = { spellId = 28814 },        }
    },
    [525] = {
        name = "Vestments of Faith",
        bonuses = {            [2] = { spellId = 28807 },            [4] = { spellId = 28809 },            [6] = { spellId = 28808 },            [8] = { spellId = 28802 },        }
    },
    [526] = {
        name = "Frostfire Regalia",
        bonuses = {            [2] = { spellId = 28763 },            [4] = { spellId = 28764 },            [6] = { spellId = 28771 },            [8] = { spellId = 28761 },        }
    },
    [527] = {
        name = "The Earthshatterer",
        bonuses = {            [2] = { spellId = 28818 },            [4] = { spellId = 29171 },            [6] = { spellId = 28823 },            [8] = { spellId = 28821 },        }
    },
    [528] = {
        name = "Redemption Armor",
        bonuses = {            [2] = { spellId = 28775 },            [4] = { spellId = 28774 },            [6] = { spellId = 28789 },            [8] = { spellId = 28787 },        }
    },
    [529] = {
        name = "Plagueheart Raiment",
        bonuses = {            [2] = { spellId = 28831 },            [4] = { spellId = 28829 },            [6] = { spellId = 28746 },            [8] = { spellId = 28830 },        }
    },
    [530] = {
        name = "Cryptstalker Armor",
        bonuses = {            [2] = { spellId = 28755 },            [4] = { spellId = 28756 },            [6] = { spellId = 28752 },            [8] = { spellId = 28751 },        }
    },
    [533] = {
        name = "Battlegear of Undead Slaying",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [534] = {
        name = "Undead Slayer's Armor",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [535] = {
        name = "Garb of the Undead Slayer",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [536] = {
        name = "Regalia of Undead Cleansing",
        bonuses = {            [3] = { spellId = 29068 },        }
    },
    [537] = {
        name = "Champion's Battlearmor",
        bonuses = {            [2] = { spellId = 41689 },            [4] = { spellId = 22738 },            [6] = { spellId = 41688 },        }
    },
    [538] = {
        name = "Champion's Stormcaller",
        bonuses = {            [2] = { spellId = 41713 },            [4] = { spellId = 22804 },            [6] = { spellId = 41712 },        }
    },
    [539] = {
        name = "Champion's Refuge",
        bonuses = {            [2] = { spellId = 41707 },            [4] = { spellId = 23218 },            [6] = { spellId = 41706 },        }
    },
    [540] = {
        name = "Champion's Investiture",
        bonuses = {            [2] = { spellId = 41697 },            [4] = { spellId = 23044 },            [6] = { spellId = 41696 },        }
    },
    [541] = {
        name = "Champion's Dreadgear",
        bonuses = {            [2] = { spellId = 41654 },            [4] = { spellId = 23047 },            [6] = { spellId = 41691 },        }
    },
    [542] = {
        name = "Champion's Arcanum",
        bonuses = {            [2] = { spellId = 41687 },            [4] = { spellId = 23025 },            [6] = { spellId = 41652 },        }
    },
    [543] = {
        name = "Champion's Pursuance",
        bonuses = {            [2] = { spellId = 41698 },            [4] = { spellId = 23158 },            [6] = { spellId = 41699 },        }
    },
    [544] = {
        name = "Lieutenant Commander's Redoubt",
        bonuses = {            [2] = { spellId = 41807 },            [4] = { spellId = 23302 },            [6] = { spellId = 41806 },        }
    },
    [545] = {
        name = "Lieutenant Commander's Battlearmor",
        bonuses = {            [2] = { spellId = 41790 },            [4] = { spellId = 22738 },            [6] = { spellId = 41791 },        }
    },
    [546] = {
        name = "Lieutenant Commander's Arcanum",
        bonuses = {            [2] = { spellId = 41789 },            [4] = { spellId = 23025 },            [6] = { spellId = 41788 },        }
    },
    [547] = {
        name = "Lieutenant Commander's Dreadgear",
        bonuses = {            [2] = { spellId = 41795 },            [4] = { spellId = 23047 },            [6] = { spellId = 41794 },        }
    },
    [548] = {
        name = "Lieutenant Commander's Guard",
        bonuses = {            [2] = { spellId = 41796 },            [4] = { spellId = 23048 },            [6] = { spellId = 41797 },        }
    },
    [549] = {
        name = "Lieutenant Commander's Investiture",
        bonuses = {            [2] = { spellId = 41799 },            [4] = { spellId = 23044 },            [6] = { spellId = 41798 },        }
    },
    [550] = {
        name = "Lieutenant Commander's Pursuance",
        bonuses = {            [2] = { spellId = 41800 },            [4] = { spellId = 23158 },            [6] = { spellId = 41801 },        }
    },
    [551] = {
        name = "Lieutenant Commander's Refuge",
        bonuses = {            [2] = { spellId = 41808 },            [4] = { spellId = 23218 },            [6] = { spellId = 41809 },        }
    },
    [552] = {
        name = "Wrath of Spellfire",
        bonuses = {            [3] = { spellId = 32196 },        }
    },
    [553] = {
        name = "Shadow's Embrace",
        bonuses = {            [3] = { spellId = 39372 },        }
    },
    [554] = {
        name = "Primal Mooncloth",
        bonuses = {            [3] = { spellId = 32102 },        }
    },
    [555] = {
        name = "Netherweave Vestments",
        bonuses = {            [2] = { spellId = 39543 },            [4] = { spellId = 41829 },        }
    },
    [556] = {
        name = "Imbued Netherweave",
        bonuses = {            [3] = { spellId = 39881 },        }
    },
    [557] = {
        name = "Soulcloth Embrace",
        bonuses = {            [3] = { spellId = 41841 },        }
    },
    [558] = {
        name = "Arcanoweave Vestments",
        bonuses = {            [3] = { spellId = 41658 },        }
    },
    [559] = {
        name = "Spellstrike Infusion",
        bonuses = {            [2] = { spellId = 32106 },        }
    },
    [560] = {
        name = "Fel Iron Plate",
        bonuses = {            [2] = { spellId = 42155 },            [4] = { spellId = 41744 },        }
    },
    [561] = {
        name = "Fel Iron Chain",
        bonuses = {            [2] = { spellId = 41561 },            [4] = { spellId = 41562 },        }
    },
    [562] = {
        name = "Adamantite Battlegear",
        bonuses = {            [3] = { spellId = 41655 },        }
    },
    [563] = {
        name = "Enchanted Adamantite Armor",
        bonuses = {            [3] = { spellId = 41742 },        }
    },
    [564] = {
        name = "Flame Guard",
        bonuses = {            [3] = { spellId = 41769 },        }
    },
    [565] = {
        name = "Khorium Ward",
        bonuses = {            [3] = { spellId = 41783 },        }
    },
    [566] = {
        name = "Burning Rage",
        bonuses = {            [2] = { spellId = 41678 },        }
    },
    [567] = {
        name = "Gladiator's Battlegear",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 22738 },        }
    },
    [568] = {
        name = "Gladiator's Dreadgear",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 23047 },        }
    },
    [569] = {
        name = "Faith in Felsteel",
        bonuses = {            [3] = { spellId = 41743 },        }
    },
    [570] = {
        name = "The Unyielding",
        bonuses = {            [2] = { spellId = 41876 },        }
    },
    [571] = {
        name = "Whitemend Wisdom",
        bonuses = {            [2] = { spellId = 32200 },        }
    },
    [572] = {
        name = "Battlecast Garb",
        bonuses = {            [2] = { spellId = 41660 },        }
    },
    [573] = {
        name = "Fel Skin",
        bonuses = {            [3] = { spellId = 41746 },        }
    },
    [574] = {
        name = "Strength of the Clefthoof",
        bonuses = {            [3] = { spellId = 41846 },        }
    },
    [575] = {
        name = "Felstalker Armor",
        bonuses = {            [3] = { spellId = 41749 },        }
    },
    [576] = {
        name = "Fury of the Nether",
        bonuses = {            [3] = { spellId = 41771 },        }
    },
    [577] = {
        name = "Gladiator's Vestments",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 21975 },        }
    },
    [578] = {
        name = "Gladiator's Earthshaker",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 33018 },        }
    },
    [579] = {
        name = "Gladiator's Regalia",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 44302 },        }
    },
    [580] = {
        name = "Gladiator's Thunderfist",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 44299 },        }
    },
    [581] = {
        name = "Gladiator's Raiment",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 33333 },        }
    },
    [582] = {
        name = "Gladiator's Aegis",
        bonuses = {            [2] = { spellId = 40044 },            [4] = { spellId = 61776 },        }
    },
    [583] = {
        name = "Gladiator's Vindication",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 61776 },        }
    },
    [584] = {
        name = "Gladiator's Sanctuary",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 23218 },        }
    },
    [585] = {
        name = "Gladiator's Wildhide",
        bonuses = {            [2] = { spellId = 40042 },            [4] = { spellId = 46832 },        }
    },
    [586] = {
        name = "Gladiator's Pursuit",
        bonuses = {            [2] = { spellId = 32145 },            [4] = { spellId = 44292 },        }
    },
    [587] = {
        name = "High Warlord's Aegis",
        bonuses = {            [2] = { spellId = 40052 },            [4] = { spellId = 23302 },        }
    },
    [588] = {
        name = "High Warlord's Battlegear",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 22738 },        }
    },
    [589] = {
        name = "Grand Marshal's Aegis",
        bonuses = {            [2] = { spellId = 40048 },            [4] = { spellId = 23302 },        }
    },
    [590] = {
        name = "Grand Marshal's Battlegear",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 22738 },        }
    },
    [591] = {
        name = "Grand Marshal's Dreadgear",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 23047 },        }
    },
    [592] = {
        name = "High Warlord's Dreadgear",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 23047 },        }
    },
    [593] = {
        name = "Grand Marshal's Earthshaker",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 33018 },        }
    },
    [594] = {
        name = "High Warlord's Earthshaker",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 33018 },        }
    },
    [595] = {
        name = "Grand Marshal's Pursuit",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23158 },        }
    },
    [596] = {
        name = "High Warlord's Pursuit",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 23158 },        }
    },
    [597] = {
        name = "Grand Marshal's Raiment",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 33333 },        }
    },
    [598] = {
        name = "High Warlord's Raiment",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 33333 },        }
    },
    [599] = {
        name = "Grand Marshal's Regalia",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 23025 },        }
    },
    [600] = {
        name = "High Warlord's Regalia",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 23025 },        }
    },
    [601] = {
        name = "Grand Marshal's Sanctuary",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23218 },        }
    },
    [602] = {
        name = "High Warlord's Sanctuary",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 23218 },        }
    },
    [603] = {
        name = "Grand Marshal's Thunderfist",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 22804 },        }
    },
    [604] = {
        name = "High Warlord's Thunderfist",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 22804 },        }
    },
    [605] = {
        name = "Grand Marshal's Vestments",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23048 },        }
    },
    [606] = {
        name = "High Warlord's Vestments",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 23048 },        }
    },
    [607] = {
        name = "Grand Marshal's Vindication",
        bonuses = {            [2] = { spellId = 40046 },            [4] = { spellId = 23302 },        }
    },
    [608] = {
        name = "High Warlord's Vindication",
        bonuses = {            [2] = { spellId = 40050 },            [4] = { spellId = 23302 },        }
    },
    [609] = {
        name = "Grand Marshal's Wildhide",
        bonuses = {            [2] = { spellId = 40047 },            [4] = { spellId = 33877 },        }
    },
    [610] = {
        name = "High Warlord's Wildhide",
        bonuses = {            [2] = { spellId = 40051 },            [4] = { spellId = 33877 },        }
    },
    [611] = {
        name = "Felscale Armor",
        bonuses = {            [2] = { spellId = 41748 },            [4] = { spellId = 41747 },        }
    },
    [612] = {
        name = "Scaled Draenic Armor",
        bonuses = {            [2] = { spellId = 41833 },            [4] = { spellId = 41834 },        }
    },
    [613] = {
        name = "Thick Draenic Armor",
        bonuses = {            [2] = { spellId = 41878 },            [4] = { spellId = 41877 },        }
    },
    [614] = {
        name = "Wild Draenish Armor",
        bonuses = {            [2] = { spellId = 41890 },            [4] = { spellId = 41889 },        }
    },
    [615] = {
        name = "Gladiator's Felshroud",
        bonuses = {            [2] = { spellId = 40053 },            [4] = { spellId = 23047 },        }
    },
    [616] = {
        name = "Netherscale Armor",
        bonuses = {            [3] = { spellId = 39982 },        }
    },
    [617] = {
        name = "Netherstrike Armor",
        bonuses = {            [3] = { spellId = 41828 },        }
    },
    [618] = {
        name = "Windhawk Armor",
        bonuses = {            [3] = { spellId = 41591 },        }
    },
    [619] = {
        name = "Primal Intent",
        bonuses = {            [3] = { spellId = 41832 },        }
    },
    [620] = {
        name = "Assassination Armor",
        bonuses = {            [2] = { spellId = 37165 },            [4] = { spellId = 37166 },        }
    },
    [621] = {
        name = "Netherblade",
        bonuses = {            [2] = { spellId = 37167 },            [4] = { spellId = 37168 },        }
    },
    [622] = {
        name = "Deathmantle",
        tier = "5",
        bonuses = {            [2] = { spellId = 37169 },            [4] = { spellId = 37170 },        }
    },
    [623] = {
        name = "Righteous Armor",
        bonuses = {            [2] = { spellId = 37180 },            [4] = { spellId = 37181 },        }
    },
    [624] = {
        name = "Justicar Raiment",
        bonuses = {            [2] = { spellId = 37182 },            [4] = { spellId = 37183 },        }
    },
    [625] = {
        name = "Justicar Armor",
        bonuses = {            [2] = { spellId = 37184 },            [4] = { spellId = 37185 },        }
    },
    [626] = {
        name = "Justicar Battlegear",
        bonuses = {            [2] = { spellId = 37186 },            [4] = { spellId = 37187 },        }
    },
    [627] = {
        name = "Crystalforge Raiment",
        tier = "5",
        bonuses = {            [2] = { spellId = 37188 },            [4] = { spellId = 37189 },        }
    },
    [628] = {
        name = "Crystalforge Armor",
        tier = "5",
        bonuses = {            [2] = { spellId = 37190 },            [4] = { spellId = 37191 },        }
    },
    [629] = {
        name = "Crystalforge Battlegear",
        tier = "5",
        bonuses = {            [2] = { spellId = 37195 },            [4] = { spellId = 37194 },        }
    },
    [630] = {
        name = "Tidefury Raiment",
        bonuses = {            [2] = { spellId = 37207 },            [4] = { spellId = 37209 },        }
    },
    [631] = {
        name = "Cyclone Raiment",
        bonuses = {            [2] = { spellId = 37210 },            [4] = { spellId = 37211 },        }
    },
    [632] = {
        name = "Cyclone Regalia",
        bonuses = {            [2] = { spellId = 37212 },            [4] = { spellId = 37213 },        }
    },
    [633] = {
        name = "Cyclone Harness",
        bonuses = {            [2] = { spellId = 37223 },            [4] = { spellId = 37224 },        }
    },
    [634] = {
        name = "Cataclysm Raiment",
        tier = "5",
        bonuses = {            [2] = { spellId = 37225 },            [4] = { spellId = 37227 },        }
    },
    [635] = {
        name = "Cataclysm Regalia",
        tier = "5",
        bonuses = {            [2] = { spellId = 37237 },            [4] = { spellId = 37228 },        }
    },
    [636] = {
        name = "Cataclysm Harness",
        tier = "5",
        bonuses = {            [2] = { spellId = 37239 },            [4] = { spellId = 37241 },        }
    },
    [637] = {
        name = "Moonglade Raiment",
        bonuses = {            [2] = { spellId = 37286 },            [4] = { spellId = 37287 },        }
    },
    [638] = {
        name = "Malorne Raiment",
        bonuses = {            [2] = { spellId = 37288 },            [4] = { spellId = 37292 },        }
    },
    [639] = {
        name = "Malorne Regalia",
        bonuses = {            [2] = { spellId = 37295 },            [4] = { spellId = 37297 },        }
    },
    [640] = {
        name = "Malorne Harness",
        bonuses = {            [2] = { spellId = { 37311, 37306 } },            [4] = { spellId = { 37299, 37298 } },        }
    },
    [641] = {
        name = "Nordrassil Harness",
        tier = "5",
        bonuses = {            [2] = { spellId = 37315 },            [4] = { spellId = 37333 },        }
    },
    [642] = {
        name = "Nordrassil Raiment",
        tier = "5",
        bonuses = {            [2] = { spellId = 37313 },            [4] = { spellId = 37314 },        }
    },
    [643] = {
        name = "Nordrassil Regalia",
        tier = "5",
        bonuses = {            [2] = { spellId = 37324 },            [4] = { spellId = 37327 },        }
    },
    [644] = {
        name = "Oblivion Raiment",
        bonuses = {            [2] = { spellId = 37375 },            [4] = { spellId = 37376 },        }
    },
    [645] = {
        name = "Voidheart Raiment",
        bonuses = {            [2] = { spellId = { 37377, 39437 } },            [4] = { spellId = 37380 },        }
    },
    [646] = {
        name = "Corruptor Raiment",
        tier = "5",
        bonuses = {            [2] = { spellId = 1272015 },            [4] = { spellId = 61992 },        }
    },
    [647] = {
        name = "Incanter's Regalia",
        bonuses = {            [2] = { spellId = 37423 },            [4] = { spellId = 37424 },        }
    },
    [648] = {
        name = "Aldor Regalia",
        bonuses = {            [2] = { spellId = 37438 },            [4] = { spellId = 37439 },        }
    },
    [649] = {
        name = "Tirisfal Regalia",
        tier = "5",
        bonuses = {            [2] = { spellId = 37441 },            [4] = { spellId = 37443 },        }
    },
    [650] = {
        name = "Beast Lord Armor",
        bonuses = {            [2] = { spellId = 37481 },            [4] = { spellId = 37483 },        }
    },
    [651] = {
        name = "Demon Stalker Armor",
        bonuses = {            [2] = { spellId = 37484 },            [4] = { spellId = 37485 },        }
    },
    [652] = {
        name = "Rift Stalker Armor",
        tier = "5",
        bonuses = {            [2] = { spellId = 37381 },            [4] = { spellId = 37505 },        }
    },
    [653] = {
        name = "Bold Armor",
        bonuses = {            [2] = { spellId = 37512 },            [4] = { spellId = 37513 },        }
    },
    [654] = {
        name = "Warbringer Armor",
        bonuses = {            [2] = { spellId = 37514 },            [4] = { spellId = 37516 },        }
    },
    [655] = {
        name = "Warbringer Battlegear",
        bonuses = {            [2] = { spellId = 37518 },            [4] = { spellId = 37519 },        }
    },
    [656] = {
        name = "Destroyer Armor",
        tier = "5",
        bonuses = {            [2] = { spellId = 37522 },            [4] = { spellId = 37525 },        }
    },
    [657] = {
        name = "Destroyer Battlegear",
        tier = "5",
        bonuses = {            [2] = { spellId = 37535 },            [4] = { spellId = 37528 },        }
    },
    [658] = {
        name = "Mana-Etched Regalia",
        bonuses = {            [2] = { spellId = 37607 },            [4] = { spellId = 37619 },        }
    },
    [659] = {
        name = "Wastewalker Armor",
        bonuses = {            [2] = { spellId = 37608 },            [4] = { spellId = 37618 },        }
    },
    [660] = {
        name = "Desolation Battlegear",
        bonuses = {            [2] = { spellId = 37609 },            [4] = { spellId = 37617 },        }
    },
    [661] = {
        name = "Doomplate Battlegear",
        bonuses = {            [2] = { spellId = 37610 },            [4] = { spellId = 37611 },        }
    },
    [662] = {
        name = "Hallowed Raiment",
        bonuses = {            [2] = { spellId = 37556 },            [4] = { spellId = 37558 },        }
    },
    [663] = {
        name = "Incarnate Raiment",
        bonuses = {            [2] = { spellId = 37564 },            [4] = { spellId = 37568 },        }
    },
    [664] = {
        name = "Incarnate Regalia",
        bonuses = {            [2] = { spellId = 37570 },            [4] = { spellId = 37571 },        }
    },
    [665] = {
        name = "Avatar Raiment",
        tier = "5",
        bonuses = {            [2] = { spellId = 37594 },            [4] = { spellId = 26171 },        }
    },
    [666] = {
        name = "Avatar Regalia",
        tier = "5",
        bonuses = {            [2] = { spellId = 37600 },            [4] = { spellId = 37603 },        }
    },
    [667] = {
        name = "The Twin Stars",
        bonuses = {            [2] = { spellId = 41875 },        }
    },
    [668] = {
        name = "Slayer's Armor",
        bonuses = {            [2] = { spellId = 38388 },            [4] = { spellId = 38389 },        }
    },
    [669] = {
        name = "Gronnstalker's Armor",
        bonuses = {            [2] = { spellId = 38390 },            [4] = { spellId = 38392 },        }
    },
    [670] = {
        name = "Malefic Raiment",
        bonuses = {            [2] = { spellId = 38394 },            [4] = { spellId = 38393 },        }
    },
    [671] = {
        name = "Tempest Regalia",
        bonuses = {            [2] = { spellId = 38396 },            [4] = { spellId = 38397 },        }
    },
    [672] = {
        name = "Onslaught Battlegear",
        bonuses = {            [2] = { spellId = 38398 },            [4] = { spellId = 38399 },        }
    },
    [673] = {
        name = "Onslaught Armor",
        bonuses = {            [2] = { spellId = 38408 },            [4] = { spellId = 38407 },        }
    },
    [674] = {
        name = "Absolution Regalia",
        bonuses = {            [2] = { spellId = 38413 },            [4] = { spellId = 38412 },        }
    },
    [675] = {
        name = "Vestments of Absolution",
        bonuses = {            [2] = { spellId = 38410 },            [4] = { spellId = 38411 },        }
    },
    [676] = {
        name = "Thunderheart Harness",
        bonuses = {            [2] = { spellId = 38447 },            [4] = { spellId = 38416 },        }
    },
    [677] = {
        name = "Thunderheart Regalia",
        bonuses = {            [2] = { spellId = 38414 },            [4] = { spellId = 38415 },        }
    },
    [678] = {
        name = "Thunderheart Raiment",
        bonuses = {            [2] = { spellId = 38417 },            [4] = { spellId = 38420 },        }
    },
    [679] = {
        name = "Lightbringer Armor",
        bonuses = {            [2] = { spellId = 38421 },            [4] = { spellId = 38422 },        }
    },
    [680] = {
        name = "Lightbringer Battlegear",
        bonuses = {            [2] = { spellId = 38427 },            [4] = { spellId = 38424 },        }
    },
    [681] = {
        name = "Lightbringer Raiment",
        bonuses = {            [2] = { spellId = 38425 },            [4] = { spellId = 38426 },        }
    },
    [682] = {
        name = "Skyshatter Harness",
        bonuses = {            [2] = { spellId = 38429 },            [4] = { spellId = 38432 },        }
    },
    [683] = {
        name = "Skyshatter Raiment",
        bonuses = {            [2] = { spellId = 38434 },            [4] = { spellId = 38435 },        }
    },
    [684] = {
        name = "Skyshatter Regalia",
        bonuses = {            [2] = { spellId = 38443 },            [4] = { spellId = 38436 },        }
    },
    [685] = {
        name = "Gladiator's Refuge",
        bonuses = {            [2] = { spellId = 40043 },            [4] = { spellId = 46834 },        }
    },
    [686] = {
        name = "Gladiator's Wartide",
        bonuses = {            [2] = { spellId = 40043 },            [4] = { spellId = 44299 },        }
    },
    [687] = {
        name = "Gladiator's Investiture",
        bonuses = {            [2] = { spellId = 40043 },            [4] = { spellId = 33333 },        }
    },
    [688] = {
        name = "Grand Marshal's Refuge",
        bonuses = {            [2] = { spellId = 40045 },            [4] = { spellId = 46834 },        }
    },
    [689] = {
        name = "High Warlord's Refuge",
        bonuses = {            [2] = { spellId = 40049 },            [4] = { spellId = 46834 },        }
    },
    [690] = {
        name = "Gladiator's Redemption",
        bonuses = {            [2] = { spellId = 40043 },            [4] = { spellId = 46851 },        }
    },
    [691] = {
        name = "Grand Marshal's Investiture",
        bonuses = {            [2] = { spellId = 40045 },            [4] = { spellId = 33333 },        }
    },
    [692] = {
        name = "High Warlord's Investiture",
        bonuses = {            [2] = { spellId = 40049 },            [4] = { spellId = 33333 },        }
    },
    [693] = {
        name = "Grand Marshal's Redemption",
        bonuses = {            [2] = { spellId = 40045 },            [4] = { spellId = 46851 },        }
    },
    [694] = {
        name = "High Warlord's Redemption",
        bonuses = {            [2] = { spellId = 40049 },            [4] = { spellId = 46851 },        }
    },
    [695] = {
        name = "Grand Marshal's Wartide",
        bonuses = {            [2] = { spellId = 40045 },            [4] = { spellId = 38499 },        }
    },
    [696] = {
        name = "High Warlord's Wartide",
        bonuses = {            [2] = { spellId = 40049 },            [4] = { spellId = 38499 },        }
    },
    [697] = {
        name = "Champion's Redoubt",
        bonuses = {            [2] = { spellId = 41705 },            [3] = { spellId = 23302 },            [6] = { spellId = 41704 },        }
    },
    [698] = {
        name = "Warlord's Aegis",
        bonuses = {            [2] = { spellId = 41886 },            [3] = { spellId = 23302 },            [6] = { spellId = 30778 },        }
    },
    [699] = {
        name = "The Twin Blades of Azzinoth",
        bonuses = {            [2] = { spellId = { 41433, 41434 } },        }
    },
    [700] = {
        name = "Merciless Gladiator's Aegis",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 61776 },        }
    },
    [701] = {
        name = "Merciless Gladiator's Battlegear",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 22738 },        }
    },
    [702] = {
        name = "Merciless Gladiator's Dreadgear",
        bonuses = {            [2] = { spellId = 41474 },            [4] = { spellId = 23047 },        }
    },
    [703] = {
        name = "Merciless Gladiator's Earthshaker",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 33018 },        }
    },
    [704] = {
        name = "Merciless Gladiator's Felshroud",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 23047 },        }
    },
    [705] = {
        name = "Merciless Gladiator's Investiture",
        bonuses = {            [2] = { spellId = 41463 },            [4] = { spellId = 33333 },        }
    },
    [706] = {
        name = "Merciless Gladiator's Pursuit",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 44292 },        }
    },
    [707] = {
        name = "Merciless Gladiator's Raiment",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 33333 },        }
    },
    [708] = {
        name = "Merciless Gladiator's Redemption",
        bonuses = {            [2] = { spellId = 41463 },            [4] = { spellId = 46851 },        }
    },
    [709] = {
        name = "Merciless Gladiator's Refuge",
        bonuses = {            [2] = { spellId = 41463 },            [4] = { spellId = 23218 },        }
    },
    [710] = {
        name = "Merciless Gladiator's Regalia",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 44302 },        }
    },
    [711] = {
        name = "Merciless Gladiator's Sanctuary",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 23218 },        }
    },
    [712] = {
        name = "Merciless Gladiator's Thunderfist",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 44299 },        }
    },
    [713] = {
        name = "Merciless Gladiator's Vestments",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 21975 },        }
    },
    [714] = {
        name = "Merciless Gladiator's Vindication",
        bonuses = {            [2] = { spellId = 41464 },            [4] = { spellId = 61776 },        }
    },
    [715] = {
        name = "Merciless Gladiator's Wartide",
        bonuses = {            [2] = { spellId = 41463 },            [4] = { spellId = 44299 },        }
    },
    [716] = {
        name = "Merciless Gladiator's Wildhide",
        bonuses = {            [2] = { spellId = 41462 },            [4] = { spellId = 44293 },        }
    },
    [717] = {
        name = "Field Marshal's Earthshaker",
        bonuses = {            [2] = { spellId = 41896 },            [3] = { spellId = 22804 },            [6] = { spellId = 41895 },        }
    },
    [718] = {
        name = "Lieutenant Commander's Earthshaker",
        bonuses = {            [2] = { spellId = 41713 },            [4] = { spellId = 22804 },            [6] = { spellId = 41712 },        }
    },
    [719] = {
        name = "The Fists of Fury",
        bonuses = {            [2] = { spellId = 41989 },        }
    },
    [720] = {
        name = "Vengeful Gladiator's Refuge",
        bonuses = {            [2] = { spellId = 43478 },            [4] = { spellId = 23218 },        }
    },
    [721] = {
        name = "Vengeful Gladiator's Sanctuary",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 23218 },        }
    },
    [722] = {
        name = "Vengeful Gladiator's Wildhide",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 44293 },        }
    },
    [723] = {
        name = "Vengeful Gladiator's Pursuit",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 44292 },        }
    },
    [724] = {
        name = "Vengeful Gladiator's Regalia",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 44302 },        }
    },
    [725] = {
        name = "Vengeful Gladiator's Redemption",
        bonuses = {            [2] = { spellId = 43478 },            [4] = { spellId = 23302 },        }
    },
    [726] = {
        name = "Vengeful Gladiator's Vindication",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 61776 },        }
    },
    [727] = {
        name = "Vengeful Gladiator's Aegis",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 61776 },        }
    },
    [728] = {
        name = "Vengeful Gladiator's Investiture",
        bonuses = {            [2] = { spellId = 43478 },            [4] = { spellId = 33333 },        }
    },
    [729] = {
        name = "Vengeful Gladiator's Raiment",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 33333 },        }
    },
    [730] = {
        name = "Vengeful Gladiator's Vestments",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 21975 },        }
    },
    [731] = {
        name = "Vengeful Gladiator's Wartide",
        bonuses = {            [2] = { spellId = 43478 },            [4] = { spellId = 44299 },        }
    },
    [732] = {
        name = "Vengeful Gladiator's Earthshaker",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 33018 },        }
    },
    [733] = {
        name = "Vengeful Gladiator's Thunderfist",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 44299 },        }
    },
    [734] = {
        name = "Vengeful Gladiator's Dreadgear",
        bonuses = {            [2] = { spellId = 43481 },            [4] = { spellId = 23047 },        }
    },
    [735] = {
        name = "Vengeful Gladiator's Felshroud",
        bonuses = {            [2] = { spellId = 43480 },            [4] = { spellId = 23047 },        }
    },
    [736] = {
        name = "Vengeful Gladiator's Battlegear",
        bonuses = {            [2] = { spellId = 43479 },            [4] = { spellId = 22738 },        }
    },
    [737] = {
        name = "Latro's Flurry",
        bonuses = {            [2] = { spellId = 9336 },        }
    },
    [738] = {
        name = "Dreadweave Battlegear",
        bonuses = {            [2] = { spellId = 46412 },            [4] = { spellId = 23047 },        }
    },
    [739] = {
        name = "Mooncloth Battlegear",
        bonuses = {            [2] = { spellId = 46413 },            [4] = { spellId = 33333 },        }
    },
    [740] = {
        name = "Satin Battlegear",
        bonuses = {            [2] = { spellId = 46414 },            [4] = { spellId = 33333 },        }
    },
    [741] = {
        name = "Evoker's Silk Battlegear",
        bonuses = {            [2] = { spellId = 46415 },            [4] = { spellId = 23025 },        }
    },
    [742] = {
        name = "Dragonhide Battlegear",
        bonuses = {            [2] = { spellId = 46435 },            [4] = { spellId = 23218 },        }
    },
    [743] = {
        name = "Wyrmhide Battlegear",
        bonuses = {            [2] = { spellId = 46436 },            [4] = { spellId = 46832 },        }
    },
    [744] = {
        name = "Kodohide Battlegear",
        bonuses = {            [2] = { spellId = 46437 },            [4] = { spellId = 46834 },        }
    },
    [745] = {
        name = "Opportunist's Battlegear",
        bonuses = {            [2] = { spellId = 46438 },            [4] = { spellId = 23048 },        }
    },
    [746] = {
        name = "Seer's Mail Battlegear",
        bonuses = {            [2] = { spellId = 46454 },            [4] = { spellId = 22804 },        }
    },
    [747] = {
        name = "Seer's Ringmail Battlegear",
        bonuses = {            [2] = { spellId = 46455 },            [4] = { spellId = 48109 },        }
    },
    [748] = {
        name = "Seer's Linked Battlegear",
        bonuses = {            [2] = { spellId = 46456 },            [4] = { spellId = 33018 },        }
    },
    [749] = {
        name = "Stalker's Chain Battlegear",
        bonuses = {            [2] = { spellId = 46456 },            [4] = { spellId = 23158 },        }
    },
    [750] = {
        name = "Savage Plate Battlegear",
        bonuses = {            [2] = { spellId = 46528 },            [4] = { spellId = 22738 },        }
    },
    [751] = {
        name = "Crusader's Ornamented Battlegear",
        bonuses = {            [2] = { spellId = 46530 },            [4] = { spellId = 23302 },        }
    },
    [752] = {
        name = "Crusader's Scaled Battlegear",
        bonuses = {            [2] = { spellId = 46534 },            [4] = { spellId = 23302 },        }
    },
    [754] = {
        name = "Borean Embrace",
        bonuses = {            [2] = { spellId = 51273 },            [4] = { spellId = 51274 },        }
    },
    [755] = {
        name = "Nerubian Hive",
        bonuses = {            [2] = { spellId = 51262 },            [4] = { spellId = 51263 },        }
    },
    [756] = {
        name = "Frostscale Binding",
        bonuses = {            [2] = { spellId = 51223 },            [4] = { spellId = 51225 },        }
    },
    [757] = {
        name = "Iceborne Embrace",
        bonuses = {            [3] = { spellId = 61633 },        }
    },
    [759] = {
        name = "Raine's Revenge",
        bonuses = {            [2] = { spellId = 9417 },        }
    },
    [760] = {
        name = "Gladiator's Dreadplate",
        bonuses = {            [2] = { spellId = 40044 },            [4] = { spellId = 14507 },        }
    },
    [761] = {
        name = "Winter Garb",
        bonuses = {            [3] = { spellId = 55000 },        }
    },
    [762] = {
        name = "Brewfest Garb",
        bonuses = {            [3] = { spellId = 55005 },        }
    },
    [763] = {
        name = "Frostwoven Power",
        bonuses = {            [2] = { spellId = 55565 },            [4] = { spellId = 55564 },        }
    },
    [764] = {
        name = "Duskweaver",
        bonuses = {            [2] = { spellId = 55595 },            [4] = { spellId = 55596 },        }
    },
    [765] = {
        name = "Gladiator's Battlegear",
        bonuses = {            [2] = { spellId = { 71850, 56449 } },            [4] = { spellId = { 22738, 71858 } },        }
    },
    [766] = {
        name = "Gladiator's Vindication",
        bonuses = {            [2] = { spellId = { 71850, 56449 } },            [4] = { spellId = { 61776, 71858 } },        }
    },
    [767] = {
        name = "Gladiator's Redemption",
        bonuses = {            [2] = { spellId = { 71851, 56450 } },            [4] = { spellId = { 58000, 71853 } },        }
    },
    [768] = {
        name = "Gladiator's Desecration",
        bonuses = {            [2] = { spellId = { 71850, 56449 } },            [4] = { spellId = { 61257, 71858 } },        }
    },
    [769] = {
        name = "Gladiator's Thunderfist",
        bonuses = {            [2] = { spellId = { 56509, 71852 } },            [4] = { spellId = { 44299, 71860 } },        }
    },
    [770] = {
        name = "Gladiator's Earthshaker",
        bonuses = {            [2] = { spellId = { 71850, 56449 } },            [4] = { spellId = { 33018, 71858 } },        }
    },
    [771] = {
        name = "Gladiator's Wartide",
        bonuses = {            [2] = { spellId = { 71851, 56450 } },            [4] = { spellId = { 44299, 71853 } },        }
    },
    [772] = {
        name = "Gladiator's Pursuit",
        bonuses = {            [2] = { spellId = { 71850, 56449 } },            [4] = { spellId = { 61256, 71858 } },        }
    },
    [773] = {
        name = "Gladiator's Refuge",
        bonuses = {            [2] = { spellId = { 71851, 56450 } },            [4] = { spellId = { 38417, 71853 } },        }
    },
    [774] = {
        name = "Gladiator's Wildhide",
        bonuses = {            [2] = { spellId = { 56509, 71852 } },            [4] = { spellId = { 46832, 71860 } },        }
    },
    [775] = {
        name = "Gladiator's Sanctuary",
        bonuses = {            [2] = { spellId = { 71850, 56449 } },            [4] = { spellId = { 23218, 71858 } },        }
    },
    [776] = {
        name = "Gladiator's Vestments",
        bonuses = {            [2] = { spellId = { 71850, 56449 } },            [4] = { spellId = { 21975, 71858 } },        }
    },
    [777] = {
        name = "Gladiator's Investiture",
        bonuses = {            [2] = { spellId = { 71851, 56450 } },            [4] = { spellId = { 33333, 71853 } },        }
    },
    [778] = {
        name = "Gladiator's Raiment",
        bonuses = {            [2] = { spellId = { 56509, 71852 } },            [4] = { spellId = { 33333, 71860 } },        }
    },
    [779] = {
        name = "Gladiator's Regalia",
        bonuses = {            [2] = { spellId = { 56509, 71852 } },            [4] = { spellId = { 44302, 71860 } },        }
    },
    [780] = {
        name = "Gladiator's Felshroud",
        bonuses = {            [2] = { spellId = { 56509, 71852 } },            [4] = { spellId = { 23047, 71860 } },        }
    },
    [781] = {
        name = "Blessed Regalia of Undead Cleansing",
        bonuses = {            [2] = { spellId = 57943 },            [3] = { spellId = 29068 },            [4] = { spellId = 57944 },        }
    },
    [782] = {
        name = "Undead Slayer's Blessed Armor",
        bonuses = {            [2] = { spellId = 57943 },            [3] = { spellId = 29068 },            [4] = { spellId = 57944 },        }
    },
    [783] = {
        name = "Blessed Garb of the Undead Slayer",
        bonuses = {            [2] = { spellId = 57943 },            [3] = { spellId = 29068 },            [4] = { spellId = 57944 },        }
    },
    [784] = {
        name = "Blessed Battlegear of Undead Slaying",
        bonuses = {            [2] = { spellId = 57943 },            [3] = { spellId = 29068 },            [4] = { spellId = 57944 },        }
    },
    [785] = {
        name = "Midsummer Reveler",
        bonuses = {            [3] = { spellId = 58933 },        }
    },
    [787] = {
        name = "Dreadnaught Plate",
        bonuses = {            [2] = { spellId = 60173 },            [4] = { spellId = 60175 },        }
    },
    [788] = {
        name = "Dreadnaught Battlegear",
        bonuses = {            [2] = { spellId = 60174 },            [4] = { spellId = 60176 },        }
    },
    [789] = {
        name = "Redemption Battlegear",
        bonuses = {            [2] = { spellId = 60152 },            [4] = { spellId = 60153 },        }
    },
    [790] = {
        name = "Redemption Regalia",
        bonuses = {            [2] = { spellId = 60147 },            [4] = { spellId = 60148 },        }
    },
    [791] = {
        name = "Redemption Plate",
        bonuses = {            [2] = { spellId = 60149 },            [4] = { spellId = 60150 },        }
    },
    [792] = {
        name = "Scourgeborne Battlegear",
        bonuses = {            [2] = { spellId = 60134 },            [4] = { spellId = 60132 },        }
    },
    [793] = {
        name = "Scourgeborne Plate",
        bonuses = {            [2] = { spellId = 60130 },            [4] = { spellId = 60133 },        }
    },
    [794] = {
        name = "Cryptstalker Battlegear",
        bonuses = {            [2] = { spellId = 60143 },            [4] = { spellId = 60144 },        }
    },
    [795] = {
        name = "Earthshatter Battlegear",
        bonuses = {            [2] = { spellId = 60168 },            [4] = { spellId = 60169 },        }
    },
    [796] = {
        name = "Earthshatter Garb",
        bonuses = {            [2] = { spellId = 60164 },            [4] = { spellId = 60165 },        }
    },
    [797] = {
        name = "Earthshatter Regalia",
        bonuses = {            [2] = { spellId = 60166 },            [4] = { spellId = 60167 },        }
    },
    [798] = {
        name = "Dreamwalker Battlegear",
        bonuses = {            [2] = { spellId = 60141 },            [4] = { spellId = 60142 },        }
    },
    [799] = {
        name = "Dreamwalker Regalia",
        bonuses = {            [2] = { spellId = 60135 },            [4] = { spellId = 60137 },        }
    },
    [800] = {
        name = "Dreamwalker Garb",
        bonuses = {            [2] = { spellId = 60138 },            [4] = { spellId = 60139 },        }
    },
    [801] = {
        name = "Bonescythe Battlegear",
        bonuses = {            [2] = { spellId = 60162 },            [4] = { spellId = 60163 },        }
    },
    [802] = {
        name = "Plagueheart Garb",
        bonuses = {            [2] = { spellId = 60170 },            [4] = { spellId = 60172 },        }
    },
    [803] = {
        name = "Frostfire Garb",
        bonuses = {            [2] = { spellId = 61062 },            [4] = { spellId = 60146 },        }
    },
    [804] = {
        name = "Regalia of Faith",
        bonuses = {            [2] = { spellId = 60154 },            [4] = { spellId = 60155 },        }
    },
    [805] = {
        name = "Garb of Faith",
        bonuses = {            [2] = { spellId = 60156 },            [4] = { spellId = 60157 },        }
    },
    [812] = {
        name = "Spring Tuxedo",
        bonuses = {            [2] = { spellId = 62181 },        }
    },
    [813] = {
        name = "Eviscerator's Battlegear",
        bonuses = {            [4] = { spellId = 63973 },            [6] = { spellId = 63972 },        }
    },
    [814] = {
        name = "Ornate Saronite Battlegear",
        bonuses = {            [4] = { spellId = 63973 },            [6] = { spellId = 63972 },        }
    },
    [815] = {
        name = "Overcaster Battlegear",
        bonuses = {            [4] = { spellId = 63973 },            [6] = { spellId = 63972 },        }
    },
    [816] = {
        name = "Savage Saronite Battlegear",
        bonuses = {            [4] = { spellId = 63973 },            [6] = { spellId = 63972 },        }
    },
    [817] = {
        name = "Stormhide Battlegear",
        bonuses = {            [4] = { spellId = 63973 },            [6] = { spellId = 63972 },        }
    },
    [818] = {
        name = "Swiftarrow Battlegear",
        bonuses = {            [4] = { spellId = 63973 },            [6] = { spellId = 63972 },        }
    },
    [819] = {
        name = "Frostsavage Battlegear",
        bonuses = {            [4] = { spellId = 63973 },            [6] = { spellId = 63972 },        }
    },
    [820] = {
        name = "Aegis Battlegear",
        tier = "8",
        bonuses = {            [2] = { spellId = 64878 },            [4] = { spellId = 64879 },        }
    },
    [821] = {
        name = "Aegis Plate",
        tier = "8",
        bonuses = {            [2] = { spellId = 64881 },            [4] = { spellId = 64882 },        }
    },
    [822] = {
        name = "Aegis Regalia",
        tier = "8",
        bonuses = {            [2] = { spellId = 64890 },            [4] = { spellId = 64895 },        }
    },
    [823] = {
        name = "Worldbreaker Battlegear",
        tier = "8",
        bonuses = {            [2] = { spellId = 64916 },            [4] = { spellId = 64917 },        }
    },
    [824] = {
        name = "Worldbreaker Garb",
        tier = "8",
        bonuses = {            [2] = { spellId = 64925 },            [4] = { spellId = 64928 },        }
    },
    [825] = {
        name = "Worldbreaker Regalia",
        tier = "8",
        bonuses = {            [2] = { spellId = 64921 },            [4] = { spellId = 64922 },        }
    },
    [826] = {
        name = "Terrorblade Battlegear",
        tier = "8",
        bonuses = {            [2] = { spellId = 64914 },            [4] = { spellId = 64915 },        }
    },
    [827] = {
        name = "Nightsong Battlegear",
        tier = "8",
        bonuses = {            [2] = { spellId = 64752 },            [4] = { spellId = 64754 },        }
    },
    [828] = {
        name = "Nightsong Garb",
        tier = "8",
        bonuses = {            [2] = { spellId = 64818 },            [4] = { spellId = 64824 },        }
    },
    [829] = {
        name = "Nightsong Regalia",
        tier = "8",
        bonuses = {            [2] = { spellId = 64756 },            [4] = { spellId = 64760 },        }
    },
    [830] = {
        name = "Siegebreaker Battlegear",
        tier = "8",
        bonuses = {            [2] = { spellId = 64938 },            [4] = { spellId = 64939 },        }
    },
    [831] = {
        name = "Siegebreaker Plate",
        tier = "8",
        bonuses = {            [2] = { spellId = 64933 },            [4] = { spellId = 64936 },        }
    },
    [832] = {
        name = "Sanctification Garb",
        tier = "8",
        bonuses = {            [2] = { spellId = 64906 },            [4] = { spellId = 64908 },        }
    },
    [833] = {
        name = "Sanctification Regalia",
        tier = "8",
        bonuses = {            [2] = { spellId = 64910 },            [4] = { spellId = 64912 },        }
    },
    [834] = {
        name = "Darkruned Battlegear",
        tier = "8",
        bonuses = {            [2] = { spellId = 64735 },            [4] = { spellId = 64736 },        }
    },
    [835] = {
        name = "Darkruned Plate",
        tier = "8",
        bonuses = {            [2] = { spellId = 64744 },            [4] = { spellId = 64745 },        }
    },
    [836] = {
        name = "Kirin Tor Garb",
        tier = "8",
        bonuses = {            [2] = { spellId = 64867 },            [4] = { spellId = 64869 },        }
    },
    [837] = {
        name = "Deathbringer Garb",
        tier = "8",
        bonuses = {            [2] = { spellId = 64931 },            [4] = { spellId = 64932 },        }
    },
    [838] = {
        name = "Scourgestalker Battlegear",
        tier = "8",
        bonuses = {            [2] = { spellId = 64854 },            [4] = { spellId = 64860 },        }
    },
    [843] = {
        name = "Khadgar's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67164 },            [4] = { spellId = 67185 },        }
    },
    [844] = {
        name = "Sunstrider's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67164 },            [4] = { spellId = 67185 },        }
    },
    [845] = {
        name = "Gul'dan's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67230 },            [4] = { spellId = 67231 },        }
    },
    [846] = {
        name = "Kel'Thuzad's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67230 },            [4] = { spellId = 67231 },        }
    },
    [847] = {
        name = "Velen's Raiment",
        tier = "9",
        bonuses = {            [2] = { spellId = 67201 },            [4] = { spellId = 67202 },        }
    },
    [848] = {
        name = "Zabra's Raiment",
        tier = "9",
        bonuses = {            [2] = { spellId = 67201 },            [4] = { spellId = 67202 },        }
    },
    [849] = {
        name = "Velen's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67193 },            [4] = { spellId = 67198 },        }
    },
    [850] = {
        name = "Zabra's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67193 },            [4] = { spellId = 67198 },        }
    },
    [851] = {
        name = "Malfurion's Garb",
        tier = "9",
        bonuses = {            [2] = { spellId = 67127 },            [4] = { spellId = 67128 },        }
    },
    [852] = {
        name = "Runetotem's Garb",
        tier = "9",
        bonuses = {            [2] = { spellId = 67127 },            [4] = { spellId = 67128 },        }
    },
    [853] = {
        name = "Malfurion's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67125 },            [4] = { spellId = 67126 },        }
    },
    [854] = {
        name = "Runetotem's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67125 },            [4] = { spellId = 67126 },        }
    },
    [855] = {
        name = "Malfurion's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67121 },            [4] = { spellId = 67123 },        }
    },
    [856] = {
        name = "Runetotem's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67121 },            [4] = { spellId = 67123 },        }
    },
    [857] = {
        name = "VanCleef's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67209 },            [4] = { spellId = 67211 },        }
    },
    [858] = {
        name = "Garona's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67209 },            [4] = { spellId = 67211 },        }
    },
    [859] = {
        name = "Windrunner's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67150 },            [4] = { spellId = 67151 },        }
    },
    [860] = {
        name = "Windrunner's Pursuit",
        tier = "9",
        bonuses = {            [2] = { spellId = 67150 },            [4] = { spellId = 67151 },        }
    },
    [861] = {
        name = "Nobundo's Garb",
        tier = "9",
        bonuses = {            [2] = { spellId = 67225 },            [4] = { spellId = 67226 },        }
    },
    [862] = {
        name = "Thrall's Garb",
        tier = "9",
        bonuses = {            [2] = { spellId = 67225 },            [4] = { spellId = 67226 },        }
    },
    [863] = {
        name = "Thrall's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67227 },            [4] = { spellId = 67228 },        }
    },
    [864] = {
        name = "Nobundo's Regalia",
        tier = "9",
        bonuses = {            [2] = { spellId = 67227 },            [4] = { spellId = 67228 },        }
    },
    [865] = {
        name = "Nobundo's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67220 },            [4] = { spellId = 67221 },        }
    },
    [866] = {
        name = "Thrall's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67220 },            [4] = { spellId = 67221 },        }
    },
    [867] = {
        name = "Wrynn's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67234 },            [4] = { spellId = 67268 },        }
    },
    [868] = {
        name = "Hellscream's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67234 },            [4] = { spellId = 67268 },        }
    },
    [869] = {
        name = "Wrynn's Plate",
        tier = "9",
        bonuses = {            [2] = { spellId = 67269 },            [4] = { spellId = 67273 },        }
    },
    [870] = {
        name = "Hellscream's Plate",
        tier = "9",
        bonuses = {            [2] = { spellId = 67269 },            [4] = { spellId = 67273 },        }
    },
    [871] = {
        name = "Thassarian's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67115 },            [4] = { spellId = 67118 },        }
    },
    [872] = {
        name = "Koltira's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67115 },            [4] = { spellId = 67118 },        }
    },
    [873] = {
        name = "Thassarian's Plate",
        tier = "9",
        bonuses = {            [2] = { spellId = 67119 },            [4] = { spellId = 67120 },        }
    },
    [874] = {
        name = "Koltira's Plate",
        tier = "9",
        bonuses = {            [2] = { spellId = 67119 },            [4] = { spellId = 67120 },        }
    },
    [875] = {
        name = "Turalyon's Garb",
        tier = "9",
        bonuses = {            [2] = { spellId = 67190 },            [4] = { spellId = 67191 },        }
    },
    [876] = {
        name = "Liadrin's Garb",
        tier = "9",
        bonuses = {            [2] = { spellId = 67190 },            [4] = { spellId = 67191 },        }
    },
    [877] = {
        name = "Turalyon's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67188 },            [4] = { spellId = 67189 },        }
    },
    [878] = {
        name = "Liadrin's Battlegear",
        tier = "9",
        bonuses = {            [2] = { spellId = 67188 },            [4] = { spellId = 67189 },        }
    },
    [879] = {
        name = "Turalyon's Plate",
        tier = "9",
        bonuses = {            [2] = { spellId = 67186 },            [4] = { spellId = 67187 },        }
    },
    [880] = {
        name = "Liadrin's Plate",
        tier = "9",
        bonuses = {            [2] = { spellId = 67186 },            [4] = { spellId = 67187 },        }
    },
    [881] = {
        name = "Purified Shard of the Gods",
        bonuses = {            [2] = { spellId = { 69599, 69755 } },        }
    },
    [882] = {
        name = "Shiny Shard of the Gods",
        bonuses = {            [2] = { spellId = { 69709, 69739 } },        }
    },
    [883] = {
        name = "Bloodmage's Regalia",
        tier = "10",
        bonuses = {            [2] = { spellId = 70752 },            [4] = { spellId = 70748 },        }
    },
    [884] = {
        name = "Dark Coven's Regalia",
        tier = "10",
        bonuses = {            [2] = { spellId = 70839 },            [4] = { spellId = 70841 },        }
    },
    [885] = {
        name = "Crimson Acolyte's Raiment",
        tier = "10",
        bonuses = {            [2] = { spellId = 70770 },            [4] = { spellId = 70798 },        }
    },
    [886] = {
        name = "Crimson Acolyte's Regalia",
        tier = "10",
        bonuses = {            [2] = { spellId = 70800 },            [4] = { spellId = 70801 },        }
    },
    [887] = {
        name = "Lasherweave Garb",
        tier = "10",
        bonuses = {            [2] = { spellId = 70658 },            [4] = { spellId = 70664 },        }
    },
    [888] = {
        name = "Lasherweave Regalia",
        tier = "10",
        bonuses = {            [2] = { spellId = 70718 },            [4] = { spellId = 70723 },        }
    },
    [889] = {
        name = "Lasherweave Battlegear",
        tier = "10",
        bonuses = {            [2] = { spellId = 70724 },            [4] = { spellId = 70726 },        }
    },
    [890] = {
        name = "Shadowblade's Battlegear",
        tier = "10",
        bonuses = {            [2] = { spellId = 70805 },            [4] = { spellId = 70803 },        }
    },
    [891] = {
        name = "Ahn'Kahar Blood Hunter's Battlegear",
        tier = "10",
        bonuses = {            [2] = { spellId = 70727 },            [4] = { spellId = 70730 },        }
    },
    [892] = {
        name = "Frost Witch's Garb",
        tier = "10",
        bonuses = {            [2] = { spellId = 70807 },            [4] = { spellId = 70808 },        }
    },
    [893] = {
        name = "Frost Witch's Regalia",
        tier = "10",
        bonuses = {            [2] = { spellId = 70811 },            [4] = { spellId = 70817 },        }
    },
    [894] = {
        name = "Frost Witch's Battlegear",
        tier = "10",
        bonuses = {            [2] = { spellId = 70830 },            [4] = { spellId = 70832 },        }
    },
    [895] = {
        name = "Ymirjar Lord's Battlegear",
        tier = "10",
        bonuses = {            [2] = { spellId = 70854 },            [4] = { spellId = 70847 },        }
    },
    [896] = {
        name = "Ymirjar Lord's Plate",
        tier = "10",
        bonuses = {            [2] = { spellId = 70843 },            [4] = { spellId = 70844 },        }
    },
    [897] = {
        name = "Scourgelord's Battlegear",
        tier = "10",
        bonuses = {            [2] = { spellId = 70655 },            [4] = { spellId = 70656 },        }
    },
    [898] = {
        name = "Scourgelord's Plate",
        tier = "10",
        bonuses = {            [2] = { spellId = 70650 },            [4] = { spellId = 70652 },        }
    },
    [899] = {
        name = "Lightsworn Garb",
        tier = "10",
        bonuses = {            [2] = { spellId = 70755 },            [4] = { spellId = 70756 },        }
    },
    [900] = {
        name = "Lightsworn Battlegear",
        tier = "10",
        bonuses = {            [2] = { spellId = 70765 },            [4] = { spellId = 70762 },        }
    },
    [901] = {
        name = "Lightsworn Plate",
        tier = "10",
        bonuses = {            [2] = { spellId = 70758 },            [4] = { spellId = 70761 },        }
    },
    [1991] = {
        name = "Nightslayer Armor",
        tier = "1",
        bonuses = {            [2] = { spellId = 1261265 },            [4] = { spellId = 1261275 },        }
    },
    [1992] = {
        name = "Arcanist Regalia",
        tier = "1",
        bonuses = {            [2] = { spellId = 1261811 },            [4] = { spellId = 1261813 },        }
    },
    [1993] = {
        name = "Giantstalker Armor",
        tier = "1",
        bonuses = {            [2] = { spellId = 1261825 },            [4] = { spellId = 1261830 },        }
    },
    [1994] = {
        name = "Felheart Raiment",
        tier = "1",
        bonuses = {            [2] = { spellId = 1261834 },            [4] = { spellId = 1261836 },        }
    },
    [1995] = {
        name = "Vestments of Prophecy",
        tier = "1",
        bonuses = {            [2] = { spellId = 1261845 },            [4] = { spellId = 1261846 },        }
    },
    [1996] = {
        name = "Shadow of Prophecy",
        tier = "1",
        bonuses = {            [2] = { spellId = 1261988 },            [4] = { spellId = 1261993 },        }
    },
    [1997] = {
        name = "Battlegear of the North",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262093 },            [4] = { spellId = 1262105 },        }
    },
    [1998] = {
        name = "Dreadplate of the North",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262261 },            [4] = { spellId = 1262262 },        }
    },
    [1999] = {
        name = "Plate of Might",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262265 },            [4] = { spellId = 1262266 },        }
    },
    [2000] = {
        name = "Battlegear of Might",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262286 },            [4] = { spellId = 1262288 },        }
    },
    [2001] = {
        name = "Lawbringer Armor",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262311 },            [4] = { spellId = 1262314 },        }
    },
    [2002] = {
        name = "Lawbringer Plate",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262319 },            [4] = { spellId = 1262325 },        }
    },
    [2003] = {
        name = "Lawbringer Battlegear",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262348 },            [4] = { spellId = 1262346 },        }
    },
    [2004] = {
        name = "Cenarion Raiment",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262350 },            [4] = { spellId = 1262353 },        }
    },
    [2005] = {
        name = "Cenarion Leathers",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262362 },            [4] = { spellId = 1262363 },        }
    },
    [2006] = {
        name = "Cenarion Garb",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262368 },            [4] = { spellId = 1262369 },        }
    },
    [2007] = {
        name = "The Earthfury",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262415 },            [4] = { spellId = 1262416 },        }
    },
    [2008] = {
        name = "Echo of the Earthfury",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262425 },            [4] = { spellId = 1262427 },        }
    },
    [2009] = {
        name = "Might of the Earthfury",
        tier = "1",
        bonuses = {            [2] = { spellId = 1262436 },            [4] = { spellId = 1262438 },        }
    },
    [2010] = {
        name = "Spirit of Eskhandar",
        bonuses = {            [3] = { spellId = 22648 },        }
    },
    [2011] = {
        name = "Desecrator Dreadplate",
        tier = "5",
        bonuses = {            [2] = { spellId = 1272020 },            [4] = { spellId = 1272021 },        }
    },
    [2012] = {
        name = "Desecrator Battlegear",
        tier = "5",
        bonuses = {            [2] = { spellId = 1272017 },            [4] = { spellId = 1272018 },        }
    },
}